### ISSUE TITLE
idpf repositories

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1004]
Related to #998, but more general, is that we need to figure out both the hosting and ownership of the various repositories that we split off from the core specs (i.e., how do we bring them under w3c, do they all have to be converted to respec docs or just skinned in some different fashion, and what is the process for publishing them).

From what I see, all of the following have documents referenced by the core specs:

- https://github.com/IDPF/epub-vocabs
- https://github.com/IDPF/epub-cmt
- https://github.com/IDPF/epub-prefixes
- https://github.com/IDPF/epub-registries
- https://github.com/IDPF/epub-guides

/cc @iherman @GarthConboy @dauwhe

**Comment by murata2makoto** [comment]
I am happy as long as we continue to use IDPF addresses such as https://idpf.github.io/epub-cmt/v3/.  Redirection to GitHub is fine to me.

**Comment by GarthConboy** [comment]
I have to say I don't have strong feelings on this one.  I don't really have the same "address stability" concerns that Makoto does (as long as said are only in the spec, not in content) -- but if you two (Matt, Makoto) are happy with keeping IDPF, it doesn't bother me.  

Also, re the actual IDPF domain, I'l pretty sure we'll continue to be able to control it.

**Comment by mattgarrish** [comment]
This is more about preparing these repositories and documents so we can begin working on them in w3c, which we need @iherman for.

We need to take them under the w3c umbrella, even if the URIs to reference them don't change. We also need to figure out the format for the documents, and publishing process for them so we aren't stuck figuring out what to do with them when the revision begins in earnest.

**Comment by iherman** [comment]
@mattgarrish I do not really have strong feelings about this. It is perfectly possible to keep the document where they are and publish W3C CG reports from there, look at, for example, the [JSON-LD 1.1](https://json-ld.org/spec/latest/json-ld/) draft, published from under https://github.com/json-ld/json-ld.org. Actually, if we need W3C URI-s at some point nevertheless, we can also set up a redirection to any github place. Ie, we do not have to bring all the repositories to under W3C. 

The only advantage of, nevertheless, migrating to W3C would be that, eventually, W3C will set up a backup procedure for the whole of the `github.com/w3c/` organization, meaning that the EPUB3.2 document would also benefit from such backup. Otherwise we are on our own, in the case github goes down.

As for using respec: the real issue is, I believe, what exactly we do with ISO. *If* the decision is that the primary goal is to get these documents into ISO, then it may be worth, while doing the update, to use an ISO structure and terminology. Respec _might_ stand in the way for doing that (to be checked).

**Comment by mattgarrish** [comment]
Thanks, I'm fine leaving them as IDPF-owned repositories and publishing as github pages if that's acceptable. I'm just trying to figure out what, if anything, we need to do.

Should we swap the IDPF logos in favour of W3C, update the legalese to W3C and call it a day?

**Comment by iherman** [comment]
> Thanks, I'm fine leaving them as IDPF-owned repositories and publishing as github pages if that's acceptable. I'm just trying to figure out what, if anything, we need to do.
> Should we swap the IDPF logos in favour of W3C, update the legalese to W3C and call it a day?
> 
Yep!

**Comment by mattgarrish** [comment]
Okay, I'll get on doing that and close this off.
