### ISSUE TITLE
Alternative Style Tags in 3.2

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#1023]
Suppose that we would like to create an ISO/IEC standard for EPUB 3.2 in the future.  Then, every normative reference should be a standard from a standardization organization recognized by JTC1.  But Alternative Style Tags is not such a standard, although the latest draft of Content Documents 3.2 normatively references it.

There are three options:

1. Stop normatively referencing Alternate Style Tags from Content Documents 3.2.
2. Publish Alternate Style Tags as part of the EPUB 3.2 family.
3. Prepare a Reference Explanatory Report for Alternate Style Tags when EPUB 3.0.2 is balloted in JTC1.

I think that the first option is the easiest.  Options 2 and 3 require more work, as I see it.

**Comment by mattgarrish** [comment]
Alt Style Tags really isn't a technology that IDPF should have standardized; it belongs in the open web if it's to exist.

I recall saying something to the same effect as 1. when we were first discussing 3(.0).2 - that alt style tags should be pulled from the core and that we should remove specific reference to the satellite IDPF specifications, since there have been no plans to move them forward in W3C (and most don't have meaningful support).

**Comment by dauwhe** [comment]
Current draft [says](http://w3c.github.io/publ-epub-revision/epub32/spec/epub-contentdocs.html#sec-xhtml-alternate-style-tags), 

> In accordance with [AltStyleTags](http://www.idpf.org/epub/altss-tags/) , the link element class attribute MAY include any of the following values: horizontal, vertical, day and night. These values inherit the semantics defined by that specification for their use.

> Reading Systems SHOULD select and utilize such tagged style sets as appropriate, and as described in that specification.

1. How much are these used today? The EBPAJ guidelines I have (v113) state, "Alternative Style Sheets Not Used". Can we just remove this section from the spec? Do any reading systems actually implement this?

2. Am I correct in thinking that this doesn't affect validation, as we are only suggesting certain values for class attributes, which are not restricted in HTML?

**Comment by JayPanoz** [comment]
> Do any reading systems actually implement this?

It’s at least been a popular request but is really tricky to handle e.g. switching stylesheets at runtime, on user settings change for instance, which may create repaint issues… as usual – we already have an awful lot of tricks to force a recalc for reading modes in ReadiumCSS because images will disappear, or multicol will not update fragmentation, etc.

**Comment by bduga** [comment]
Play Books implements them for horizontal/vertical style sheets, but doesn't expose them to the user. So we grab the vertical styles and use them instead of getting the default styles. Of course, if the default styles just used vertical styling, nothing would break if the alternate sets were removed.

**Comment by mattgarrish** [comment]
> Am I correct in thinking that this doesn't affect validation

Yes, the authoring guidance is contrived, since there's nothing that prevents anyone from doing what it says. It lets alt style tags be acknowledged as existing, but it's not actually allowing something that would otherwise be invalid.

Dropping alternative style sheets wouldn't be a lot different from what we did to epubcfi. You can still include, and reading systems can still opt to support, but the core specs become silent about the existence of these technologies.

**Comment by murata2makoto** [comment]
How about an entry in the bibliography?  We mention it as an example value list of the class attribute.

**Comment by mattgarrish** [comment]
Closing this as it was addressed in PR #1035.
