### ISSUE TITLE
Merge the manifest properties vocabulary into the main spec?

### ISSUE THREAD

**Issue by dauwhe** [w3c/epub-specs#1047]
Allowed values for properties attribute of item in the manifest are listed at https://idpf.github.io/epub-vocabs/package/item/

Worth merging this into the spec? These are used everywhere, and seem relatively stable.

**Comment by GarthConboy** [comment]
Indeed.  Don't see a reason to keep these external.  Matt?

**Comment by mattgarrish** [comment]
If we bring one in, why aren't we bringing them all back in? That would also mean pulling in the rendition vocabulary in addition to the metadata. It'll really bloat the specification.

But if it has to be done, let's at least dump them as appendixes in the back.

Alternatively, what about just listing the key values in the corresponding attribute definitions? In this case, instead of:

> This specification reserves the [ManifestVocab] for use with the properties attribute. Terms from other vocabularies MAY be used provided they have a prefix (refer to Reserved Prefixes for a list of prefixes that do not have to be declared).

We might reword as:

> This specification reserves the [ManifestVocab] for use with the properties attribute. Key terms from this vocabulary include:
> 
> - cover-image
> - ...
> 
> Terms from other vocabularies MAY be used provided they have a prefix (refer to Reserved Prefixes for a list of prefixes that do not have to be declared).

**Comment by mattgarrish** [comment]
Here's an idea of what it will look like if we squash them all back in:

https://rawgit.com/w3c/publ-epub-revision/vocab-test/epub32/spec/epub-packages.html

**Comment by murata2makoto** [comment]
> Here's an idea of what it will look like if we squash them all back in:

Nice work.  I see nothing wrong.  Unless some vocabulary has to be updated more than once in a year, consolidation is better.

**Comment by dauwhe** [comment]
Closed via #1049
