### ISSUE TITLE
Consider removing the Note from the "4.3.3.1.2 Allowed values" / scrolled-continuous section 

### ISSUE THREAD

**Issue by mustlaz** [w3c/epub-specs#1092]
The note refers to a future version of the specification but it doesn't seem we'd update it.

**Comment by dauwhe** [comment]
Just for convenience, the section is [here](http://w3c.github.io/publ-epub-revision/epub32/spec/epub-packages.html#layout-property-flow-values).

The note reads:

> It is expected that a future version of this specification will provide more information about Reading System behaviors for scrolled-continuous.

**Comment by mattgarrish** [comment]
Here's what prompted the note: https://github.com/w3c/publ-epub-revision/issues/823

Dropping the note without answering this question doesn't seem like the best approach, but the note could be more specific about its purpose. I only vaguely remembered our adding it, and wouldn't have been able to say why without looking up the issue.

**Comment by dauwhe** [comment]
How about:

> Continuous scroll might not be possible between content documents with differing writing modes.

**Comment by mattgarrish** [comment]
Do we also need to mention ppd?

> Continuous scroll might not be possible for when the writing modes or page progression direction of all EPUB Content Documents in the scroll are not uniform.

Or even make it normative:

> Authors SHOULD NOT create continuous scrolls on EPUB Content Documents with different writing modes and/or page progression direction, as their rendering in EPUB Reading Systems is problematic.

(or something like that)

**Comment by dauwhe** [comment]
Isn't [page-progression-direction](
https://drafts.csswg.org/css-writing-modes-4/#page-direction) for content documents determined by the principle writing mode?

I also wonder what it actually means to have the package PPD different from the PPD of a particular content doc. Most reading systems use the same UI control/gesture to move between pages and to move between content docs. Let's say you have a RTL content doc in a LTR epub, and that you have only left and right arrow keys (or buttons or swipes) to navigate. Within the RTL content doc, you click the left arrow to get to the next page. When you get to the last page, you can't suddenly switch to using the right arrow to get to the next content document, regardless of the global PPD, because you need that gesture to go back.

**Comment by mattgarrish** [comment]
> I also wonder what it actually means to have the package PPD different from the PPD of a particular content doc.

Ya, I'm now more confused than before. The old issue seemed to hinge on problems with FXL documents and PPD, but we also have this:

> Reading Systems MUST ignore the page progression direction defined in pre-paginated XHTML Content Documents. The page-progression-direction attribute defines the flow direction from one fixed-layout page to the next.

Maybe it is just conflicting writing modes.

@murata2makoto ?

**Comment by llemeurfr** [comment]
So, we have a spine level `page-progression-direction` from one resource to the next (let's call it a reading progression (RP) like in WP for the sake of clarity) and a resource level page progression direction (PPD). 

As stated by @dauwhe, the RP and the PPD of a reflow document must have the same value (ltr/rtl). If it is not the case, the publication will become a maze for the user. 

IMO this rule should be normative -> Authors SHOULD NOT create publications in which a resource level page progression direction is different from the spine level `page-progression-direction` set in the OPF, as their rendering in EPUB Reading Systems would be problematic.

An FXL resource is neutral because it has a single "page", therefore the issue does not exist for 100% FXL publications (and the very notion of continuous scroll on FXL publication is incongruous).  

Back to continuous scroll: vertically written publications are scrolled horizontally and vice-versa. It's impossible to mix vertical + horizontal scroll. More, a vertical-rl publication is scrolled to the left, a vertical-lr to the right. 

Therefore, Authors also SHOULD NOT create publications in which different resources have different [writing modes](https://drafts.csswg.org/css-writing-modes-4/#block-flow).

If the preceding rules are followed, continuous scroll is possible. Vertical / top-down scroll if the writing mode is horizontal (rtl or ltr), horizontal / rtl scroll if the writing mode is vertical and rtl, horizontal / ltr scroll if the writing mode is vertical and ltr.

If this is consensual, we'll adapt accordingly the [document Jiminy Panoz has written on i18n processing in Readium software](https://github.com/readium/readium-css/blob/master/docs/CSS16-internationalization.md) (a set of rules for developers, which take into account some authoring mistakes).

**Comment by danielweck** [comment]
> the very notion of continuous scroll on FXL publication is incongruous

One classic example comes to mind: A4 portrait PDF documents, pages laid out on a vertical axis, inside a continuously-scrolled viewport.

**Comment by llemeurfr** [comment]
> One classic example comes to mind: A4 portrait PDF documents, pages laid out on a vertical axis, inside a continuously-scrolled viewport.

@danielweck yes it is stitching visible pages together; but is this still what we call continuous scrolling in EPUB? But I'm ok to call it continuous scrolling after all. 

The only weird think in the FXL case is that the spine level `page-progression-direction` is of no use, as the scroll direction is logically based on the resource level [bloc flow direction](https://drafts.csswg.org/css-writing-modes-4/#block-flow-direction) instead (to be confirmed by experts).

**Comment by murata2makoto** [comment]
@llemeurfr and @danielweck I do not think that the spec has to clearly specify the continuous scroll of FXL.

When every content document in a publication is reflowable and has the same writing mode, the semantics of scrolled-continuous is obvious.  In all other cases, I think that we should admit that the semantics is not clear.

**Comment by murata2makoto** [comment]
@llemeurfr  PPD is not useful when we do not have pages.

**Comment by llemeurfr** [comment]
@murata2makoto let's not confuse the spine level page-progression-direction (EPUB vocabulary) from one resource to the next (let's call it a reading progression (RP) like in WP for the sake of clarity) and the resource level page progression direction (HTML vocabulary) (=PPD)

**Comment by murata2makoto** [comment]
@llemeurfr I think that the PPD is completely irrelevant to scrolled-continuous, since no pages are involved.  What is important is the [block flow direction](https://www.w3.org/TR/css-writing-modes-3/#text-flow), as defined in CSS Writing Modes.

**Comment by llemeurfr** [comment]
@murata2makoto that's exactly what I said above. 

One pratical issue is still that the block flow direction is set at the level of each html document, and not relayed at the spine level. Therefore, in practice, most Reading Systems will use the language metadata as a hint to infer horizontal (+ rtl or ltr) vs vertical scroll between "stitched together" documents. This is a weak workaround.

**Comment by danielweck** [comment]
I agree in principle that the (*inter-*) "direction of progression" between adjacent / contiguous documents inside an ordered collection (aka spine / publication reading order) can logically be inferred from the (*intra-*) "direction of progression" between content fragments within a single document (e.g. paginated columns), which is itself dictated by the CSS writing mode of the top-level document root (block flow). Naturally, the following caveat applies:

Transitioning between documents with opposite "direction of progression" ; in a continuous fashion, or using discrete content viewports ; at the very least causes major user experience issues (e.g. inconsistent left/right gestures mapping with previous/next commands). From a reading system implementer's perspective, this is also problematic at a technical level due to resource pre-loading and pre-rendering (i.e. preparing the layout for populating adjacent out-of-view content viewports in order to provide seamless / uninterrupted inter-document transitions).

Practically-speaking, inferring the publication-wide "page progression direction" (as per EPUB http://www.idpf.org/epub/31/spec/epub-packages.html#attrdef-spine-page-progression-direction ) based on a individual document's writing mode assumes consistent direction in all documents, which isn't necessarily the case.

So, how far down this specification rabbit hole are we willing to go? Can this be a situation of "undefined semantics" / "unspecified behaviour", or should this translate to hard content conformance requirements (which form the basis of validation fail/warning/pass rules) and/or to normative user-agent conformance statements? (processing algorithm, graceful degradation, etc.)

A corollary question is whether publication-wide "page progression direction" declarative metadata is indeed needed at all, given that it can either be inferred from individual documents at rendering time, or that this may in fact be relatively useless information as far as reading system implementations are concerned (because paginated / fragmented document flows are dictated by individual document's writing modes anyway).

My personal bias is based on my own development experience: unlike vanilla web browsers, reading systems have to carefully implement *both* intra- and inter- document transitions in order to deliver a fluid "paginated" reading experience. The authored publication-wide "page progression direction" metadata provides information "ahead of time" ; i.e. before a reading system even starts rendering any document ; which allows a reading system engine to prepare adjacent out-of-view viewports, setup pre-fetch + pre-render strategies, etc.

I'd love to hear more from other implementers though.

**Comment by danielweck** [comment]
PS: references to related Web Publications "reading progression direction":

https://w3c.github.io/wpub/#reading-progression-direction

...as previously discussed here:

https://github.com/w3c/wpub/issues/126

**Comment by murata2makoto** [comment]
First, let me point out that the PPD cannot indicate the block flow direction.  In BIDI, the PPD is from right to left, but the block flow direction is from top to bottom.  In Asian vertical writing mode, the PPD is also from right to left, but the block flow direction is from right to left.  In Asian horizontal writing mode, the PPD is from left to right, and the block flow direction is from top to bottom.  (Thus, DC:language cannot indicate the block flow direction.)

Second, EGLS of the EPUB3 WG very carefully considered the mixture of the rtl PPD and ltr PPD.  Some printed books do have such mixture.  But we concluded that we should not pursue such mixture.  Unfortunately, we did not make this point clear in EPUB3.

IMHO,  we should admit that 

- (1) the interaction of FXL and scrolled-continuous is not well-defined; and
- (2) the semantics of scrolled-continuous is clear only when every content document in the spine is reflowable and of the same block flow direction. 

Do we have to specify how implementers should make sure that "every content document in the spine is reflowable and of the same block flow direction"?  I am not convinced.

> A corollary question is whether publication-wide "page progression direction" declarative metadata is indeed needed at all, given that it can either be inferred from individual documents at rendering time, or that this may in fact be relatively useless information as far as reading system implementations are concerned (because paginated / fragmented document flows are dictated by individual document's writing modes anyway).

Actually, most FXL manga has mixture.  Each single-page content document has the ltr PPD,  But the spine has the rtl PPD.  (See the EBPAJ profile.)

**Comment by danielweck** [comment]
> Actually, most FXL manga has mixture. Each single-page content document has the ltr PPD, But the spine has the rtl PPD. (See the EBPAJ profile.)

Excellent reminder of why a publication-wide "progression direction" indicator is effectively required (much more convincing argument than my comments about pre-rendering / layout preparation / optimization in reading system implementations).

So the central question is can we improve informative and/or normative statements about potentially-conflicting inter- and intra- "progression direction" indicators.

**Comment by llemeurfr** [comment]
@murata2makoto, I have two questions: 
- in reflow documents written in vertical writing, displayed in scroll continuous, I suppose that the "line width" (vertical line) should not be not too large (if it was I suppose reading would be tedious). 
Do authors create sections with constrains in a page to avoid such issue?
-  in FXL documents written in vertical writing, if the user scrolls continuously (à la PDF reader), should the scroll be vertical (like in western cultures) or horizontal? Has Acrobat PDF a specific way to handle such writings?

**Comment by murata2makoto** [comment]
> in reflow documents written in vertical writing, displayed in scroll continuous, I suppose that the "line width" (vertical line) should not be not too large (if it was I suppose reading would be tedious).

Certainly, yes.

> Do authors create sections with constrains in a page to avoid such issue?

Authors do not specify anything.  The width should be automatically determined so that the width (which is perpendicular) fits in the screen.

> in FXL documents written in vertical writing, if the user scrolls continuously (à la PDF reader), should the scroll be vertical (like in western cultures) or horizontal? Has Acrobat PDF a specific way to handle such writings?

In FXL documents, the writing mode does not really mean much, since different regions may well have different writing modes.   I think that the PPD of the spine should control the scroll direction.

That said, some publications (most notably calendars) may use vertical PPD.  Nobody will blame you even if you ignore such publications.

**Comment by llemeurfr** [comment]
>   I think that the PPD of the spine should control the scroll direction.

If vertical scrolling is desired (and it is at least in western cultures) then it means that one should be able to express "vertical scrolling please" in the spine (as the PPD values are only ltr and rtl, this cannot be used). Isn't it?

**Comment by danielweck** [comment]
What is currently missing for fixed-layout publications (let's ignore the edge-case of mixed reflow + FXL publications for now, this is hard-enough as it is! ;) is the ability for content creators to specify the "continuous scroll" axis, i.e. vertical vs. horizontal (irrespective of the possible combinations of writing mode and direction *within* any particular FXL document). Yet reading systems are ; in principle ; capable of the following visualization modes:

* By default most reading systems "paginate" FXL documents on the horizontal axis from either LTR or RTL (depending on the inter-document spine-level publication-wide "page progression direction"), *accounting for* "spread" metadata (single or double page, left/centre/right slot alignment).
* Some reading systems implement vertical continuous scrolling for FXL publications: display consecutive documents (i.e. pages) *ignoring* "spread" metadata, along the "y" axis from top-to-bottom (similar to reflow documents with horizontal principal writing mode, and either RTL or LTR direction).
* Some reading systems may also additionally implement horizontal scrolling for FXL publications: display consecutive documents (i.e. pages) *ignoring* "spread" metadata, along the "x" axis from LTR or from RTL (similar to reflow documents with vertical writing mode, and either RTL or LTR direction).

If we really wanted to go down this road, one solution would be to offer content creators the following values: `scroll:doc`, `scroll:continuous` (both "legacy" / original values), `scroll:continuous-vertical` (synonym to previous value, implies top-to-bottom), and `scroll:continuous-horizontal` (which, when combined with "page progression direction" LTR or RTL, provides reading systems with non-ambiguous information about the expected page layout).

Otherwise, we can just leave it as it is, and continue to assume that (some) reading systems offer users configurable presentation modes, to override / complement the basic "direction" and "scroll" authored publication metadata.

Note that for reflow publications, the missing vertical vs. horizontal "scroll:continuous" metadata hint can be inferred by reading systems by picking-up the principal writing mode from within one of the spine documents (assuming we can "safely" rely on consistency across all documents in the reading order). This can then be combined with the "page progression direction" in order to determine the appropriate scroll layout (as per the above 3 choices).

**Comment by llemeurfr** [comment]
reminder: in western languages, continuous scroll from page to page should be vertical (what we see in Word, Acrobat etc.). But in CJK languages written vertically, scroll from page to page should be horizontal & rtl. 
 
@danielweck, if we follow your path, the rule "If a Reading Systems supports the rendition:layout property, it MUST ignore the rendition:flow property when it has been set on a spine item that also specifies the rendition:layout value pre-paginated." in [4.3.3.1](http://w3c.github.io/publ-epub-revision/epub32/spec/epub-packages.html#layout-property-flow-usage) must be changed. But it would mean a non-compatible change vs EPUB 3.0, isn't it? this is annoying. 

Note: the rule is in fact wrongly expressed, as individual spine items have a properties with value layout-pre-paginated.  rendition:layout  is a global property. 

@murata2makoto 
> the interaction of FXL and scrolled-continuous is not well-defined

Would you let such note in a W3C spec? it's like stating "it is too much complicated for us".  And the paragraph of the spec copied above implies that there is something (under-)defined. 

IMO we should define UA behavior for FXL document relative to the scroll direction, as a function of the block flow direction of the content of the publication; and they are two main solutions, both keeping backward compatibility with EPUB 3.0:

- avoid touching the EPUB markup and consider that it's up to the UA and/or user to select a scroll direction (hoping that the UA/user will find a way to have a vertical scroll for publications in horizontal-tb writing mode and an rtl scroll for vertical-rl writing mode (etc.).
- add a new property to EPUB 3.2, which values indicate the preference of the author for the scroll direction (rtl, ltr, tb). This value should be compatible with block flow directions of every spine item. 

I suspect that the consensus will be around the first solution. 
In such a case, in the Readium case, I'll push the idea that for users selection "scroll" as a display mode, if the spine level page-progression-direction is not set, the first spine item in reading order gives the necessary information (block flow direction). It's a hack I know. It will work both for reflow and FXL publications. 

Whatever the consensus, there is a rule to set: 
Authors SHOULD NOT create publications in which different resources have different [block flow directions](https://drafts.csswg.org/css-writing-modes-4/#block-flow), as continuous scrolled rendition in EPUB Reading Systems would be problematic

**Comment by murata2makoto** [comment]
@llemeurfr 

>>the interaction of FXL and scrolled-continuous is not well-defined
>Would you let such note in a W3C spec?

Since EPUB 3.2 is just a CG report, I do not see any problems.  After all, EPUB 3 is underspecified as a W3C recommendation.  Admitting underspecifiednesss is better than pretending that EPUB is well-defined.

> avoid touching the EPUB markup and consider that it's up to the UA and/or user to select a scroll direction (hoping that the UA/user will find a way to have a vertical scroll for publications in horizontal-tb writing mode and an rtl scroll for vertical-rl writing mode (etc.).

I oppose to the idea of preventing such touching.  Some RSs will examine content documents and then decide the block flow direction.

>Authors SHOULD NOT create publications in which different resources have different block flow directions, as continuous scrolled rendition in EPUB Reading Systems would be problematic

Agreed.  Also, authors should not introduce FXL within a single EPUB publication while specifying scrolled-continuous.

**Comment by dauwhe** [comment]
Closed via #1103
