### ISSUE TITLE
Is "Content" in "Content, Scripting, and Media Overlays" a bit ambiguous?

### ISSUE THREAD

**Issue by ghost** [w3c/epub-specs#1095]
In "3.1.2 Supported Media Types" there is a category names "Content, Scripting, and Media Overlays",  I don't know why we changed from "Application Types" to "Content, Scripting, and Media Overlays"("Application Types" seems confusing though) but feel the term "Content" here might be ambiguous since all those mpeg, mp4 also can be "content". Maybe here we just use "XHTML Content" is good enough?

**Comment by dauwhe** [comment]
We changed "Application Types" because we felt the previous organization wasn't great, especially as it split fonts into different categories based on media types. I wish I could have called this category "Miscellaneous" or something like that :)

I don't have a problem with the current name. The heading isn't normative, and it's hard to find a common thread between those various media types. I'd be happy to hear other suggestions.

**Comment by mattgarrish** [comment]
I'd be fine with calling it "Other" and just dropping it to the bottom of the table. It's a dumping ground of media types that aren't referenced anywhere as a group.

But I don't care too much either way.

**Comment by ghost** [comment]
"Other" works for me. It's minor issue and just prevent from getting confused when we add more Supported Media Types in the future.

**Comment by dauwhe** [comment]
Fixed with #1099
