### ISSUE TITLE
Update links in Microdata section, and remove mention of DOM API

### ISSUE THREAD

**Issue by dauwhe** [w3c/epub-specs#1100]
From Avneesh via email: 

> 2.4.2.3 Microdata
> In this paragraph, DOM API link points to older version of microdata.
> https://www.w3.org/TR/2013/NOTE-microdata-20131029/#microdata-dom-api

Ah, the DOM API from Microdata has been removed. Looks like some other links in this section need to be updated, too.

**Comment by dauwhe** [comment]
OK. So our spec [says](
http://w3c.github.io/publ-epub-revision/epub32/spec/epub-contentdocs.html#sec-xhtml-sementic-enrichment-microdata), 

> EPUB Reading System support for the attribute processing model is OPTIONAL

So... the [attribute processing model](https://www.w3.org/TR/microdata/#encoding-microdata) is section 5 of the microdata spec. This is the part that actually talks about itemscope, itemtype, etc. Are we saying that you can include microdata in EPUB, but that reading systems can just completely ignore it?

**Comment by mattgarrish** [comment]
> Are we saying that you can include microdata in EPUB, but that reading systems can just completely ignore it?

Sure, no different than they can ignore RDFa attributes.

Is there a case for requiring them to process either of these?

**Comment by dauwhe** [comment]
> Is there a case for requiring them to process either of these?

No, just wanted to make sure I understood. Thanks!

**Comment by mattgarrish** [comment]
The API question is a little trickier. 3.1 was referencing the W3C note, which still included the API even though it was abundantly apparent that it was dead and buried at the time. It's kind of awkward that we're now referencing a working draft, as we've been burned by those before (hello, aria-describedat!).

It's probably one of those things that just doesn't need saying, since the market has already dictated the outcome, whatever version gets referenced in the end.

**Comment by dauwhe** [comment]
I'm OK with pointing to the WD...

> The editors believe the specification is complete and ready to become a Candidate Recommendation.

...especially since this doesn't obligate reading systems to do anything but not reject the markup.

**Comment by dauwhe** [comment]
Closed by #1103 and CG resolution 23 Aug 2018.
