### ISSUE TITLE
Icon fonts as glyphs: Accessibility problems

### ISSUE THREAD

**Issue by deborahgu** [w3c/epub-specs#1105]
@dauwhe mentioned [using icon fonts as glyphs](https://github.com/w3c/publ-epub-revision/issues/1101#issuecomment-415116308), which can cause accessibility problems without extra effort made to convey a text alternative.  While this is absolutely covered by [WCAG 1.1.1](https://www.w3.org/TR/WCAG21/#non-text-content), text alternatives for non-text content, it is also a widely misunderstoof case which is broadly mishandled in HTML in practice.  Should we consider WCAG 1.1.1 adequate coverage for this use case, or should we call it out?

References:

* [1.1.1 techniques](https://www.w3.org/WAI/WCAG21/quickref/?versions=2.1#qr-text-equiv-all)
* [Icon Font with an On-Screen Text Alternative](https://www.w3.org/WAI/GL/wiki/Icon_Font_with_an_On-Screen_Text_Alternative)
* [Using aria-hidden=true on an icon font that AT should ignore](https://www.w3.org/WAI/GL/wiki/Using_aria-hidden%3Dtrue_on_an_icon_font_that_AT_should_ignore)
* [Alternative text in CSS](https://drafts.csswg.org/css-content-3/#alt)

**Comment by mattgarrish** [comment]
We have a technique to draw attention to the problems of mapping glyphs in the unicode private use area: http://www.idpf.org/epub/a11y/techniques/#text-001

Might be useful to expand on that technique to highlight icon fonts, too.

I don't believe there's any way we could prevent this sort of practice, so I'm not sure there's anything we can formally say in the content docs specification.

**Comment by mattgarrish** [comment]
A new WCAG technique for identifying icon fonts has been added since this issue was raised: https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA24

We've tried to draw the line on what to cover in the EPUB techniques to issues specific to EPUB or understanding EPUB in the context of WCAG, so if additional guidance is needed we should look at raising issue with the WCAG folks.

I'm going to close this issue for now, but feel free to re-open if you feel there's a unique EPUB angle to it.
