### ISSUE TITLE
References to CSS 2.1

### ISSUE THREAD

**Issue by bduga** [w3c/epub-specs#1123]
There are several links from EPUB Content Documents 3.2 directly to CSS 2.1 in section 6 (Fixed Layouts). These are typically followed by links to [CSSSnapshot], which is the Jan 2017 snapshot for CSS. I don't think we have a normative reference to CSS 2.1, and probably shouldn't add one. Is there a better way to link these?

For instance, see section 6.2, normative MUST pointing to https://www.w3.org/TR/CSS2/visudet.html#containing-block-details

**Comment by dauwhe** [comment]
I'm comfortable with a normative reference to CSS 2. The links are undated, and much of the fundamental machinery of CSS is defined only there.

**Comment by dauwhe** [comment]
Closed via #1124

**Comment by bduga** [comment]
Hmm... I am not sure about this change. First off, this replaces references to our normative links for CSSSnapshot to CSS2, but CSS2 isn't in that section. Second, I think we intentionally removed references to CSS2 at some point, preferring the snapshot instead. I am not sure if we should just re-add a normative reference to CSS2.

**Comment by dauwhe** [comment]
We already have normative references to the Snapshot, CSS Fonts 3, CSS Text Decoration 3, CSS Values 3, CSS Writing Modes 3, and CSS Device Adaptation 1. I'm not sure of the risk posed by having a normative references to CSS 2, which is already part of the snapshot. 

I do find the earlier solution confusing, where we link to CSS 2 directly, and then have  reference to the snapshot after it, which would then require lots of clicks to end up at the definition we want.

**Comment by bduga** [comment]
I thought the point of going through the snapshot was to leave CSS to the CSSWG. If they remove CSS2 from the snapshot, we don't have to do anything. It's a handle, essentially.

**Comment by mattgarrish** [comment]
> It's a handle, essentially.

That was generally the idea.

The links are going to break if CSS 2.x is ever replaced, as there isn't a generic reference like /TR/HTML available. TR/CSS is claimed by the snapshot, so if the 2.x strain dies, our links die.

In theory, if CSS 2.x dies, the idea is that you could go to the snapshot and try to find out what it was replaced by. It was sort of a hack on not really having a permanently moving reference, in other words.

I'm fine referencing CSS2 where we reference CSS2, as the snapshot is really more important in terms of defining the CSS profile. Otherwise, it is kind of weird that we reference specific CSS 3 modules.

**Comment by dauwhe** [comment]
I'm confident that CSS2 is going to be with us for a long, long time. Many foundational concepts are defined there, it would take an immense effort to replace those sections, and I'm not aware of anyone willing to pay for that work. So I think we're safe for five years, at least.

**Comment by dauwhe** [comment]
close via CG resolution
