### ISSUE TITLE
clarify the content model of MathML `annotation-xml`

### ISSUE THREAD

**Issue by rdeltour** [w3c/epub-specs#1212]
the current language is the _content conformance_ section for Embedded MathML says:

> The `math` element MUST contain only Presentation MathML, with the exception of the `annotation-xml` element as defined below.

and then it defines the constraints for how Content MathML and XHTML can be used in said `annotation-xml` element.

However, it is a bit vague as to whether other markup can appear in `annotation-xml`.

- can SVG be used as `annotation-xml`? with an SVG media type or only as embedded in XHTML?
- can presentation MathML be used as `annotation-xml`? (I don't know if it's common practice but in theory it might be used to store an equivalent markup of a formula with the `contentequiv` keyword?).

The Nu Html Checker allows both of the above. Current EPUBCheck rejects both.

Can the spec be clarified?

**Comment by rdeltour** [comment]
> Current EPUBCheck rejects both.

In fact, it allows presentation MathML with the encoding `MathML-Presentation` or `application/mathml-presentation+xml`

**Comment by mattgarrish** [comment]
> However, it is a bit vague as to whether other markup can appear in `annotation-xml`.

Ya, going by the usual patterns of language, the fact that it says "as defined below" means that is a hard restriction: you can only have presentational math with xhtml annotations. If the intention were to be permissive, the sentence would have ended without bothering to mention the `annotation-xml` element at all, since by definition it is permissive.

I expect this was done to ensure that the annotations do no break core media type requirements. You can include SVG without having to allow it as a media type, since an SVG -- referenced or embedded -- is a valid xhtml fragment. But that isn't an argument for not explicitly allowing SVG, as it seems like it should be allowed, too.

**Comment by GeorgeKerscher** [comment]
Hi,
 
I know that MathML includes markup for chemistry, but Assistive Technology has no way of knowing if it is math or chemistry, so it is presented as math. Is it possible to use the annotation to indicate that this is chemistry?
 
Best
George
Best
George

**Comment by dauwhe** [comment]
I'm wondering about 

>   When an XHTML Content Document fragment is included as per the above paragraph, the given annotation-xml element's encoding attribute MUST be set to application/xhtml+xml and its name attribute MUST be set to alternate-representation.

This is a really strong restriction on the name attribute, essentially saying that the XHTML content doc fragment must be equivalent semantically to the the MathML. That's obviously unenforceable, and also seems to break some of the extension mechanisms defined in MathML. Why do we do this?

**Comment by mattgarrish** [comment]
> Why do we do this?

They were originally only intended to provide fallbacks. Going back in time, we used to have this support bullet:

> When producing alternative textual content for MathML markup, it should be able to dynamically generate such content from the given Presentation MathML, and if not, must give preference to XHTML Content Document fragments followed by the alttext attribute on the m:math element.

We dropped that when we got out of the business of explaining fallbacks, but per the intro the content model was always intended to be very limited to encourage support in reading systems.

While a noble intention, I'd hazard to say it really hasn't achieved its ambition.

And with that said, I'm not sure I can find the passion to take any position on this one...

**Comment by dauwhe** [comment]
Hmmmm. So all of this happens in an `semantics` element, which is required to start with a MathML expression. And then we find:

> The default rendering of a semantics element is the default rendering of its first child. A renderer may use the information contained in the annotations to customize its rendering of the annotated element. 

> While there is no default rendering for the annotation-xml element, a renderer may use the information contained in an annotation to customize its rendering of the annotated element. 

So I'm not seeing the need for any restrictions. A reading system must already be able to render the MathML expression that's the first child of annotations. And it has no obligation to do anything with the subsequent annotation or annotation-xml elements. 

As a general principle I think we should be as delicate as possible when restricting external languages. I think we should

[1] remove the restrictions on XHTML Content Document fragments

[2] remove "as defined below" so that annotation-xml can be used as designed

**Comment by dauwhe** [comment]
CG seems to agree that we should remove the restrictions as I proposed above. I'll make the edits.
