### ISSUE TITLE
Why should a reading system parse an identifier?

### ISSUE THREAD

**Issue by dauwhe** [w3c/epub-specs#1216]
The packages spec says,

> To determine whether an identifier conforms to an established system or has been granted by an issuing authority, Reading Systems SHOULD attempt to parse the value of the element.

What is a reading system supposed to do with this information? We don't offer any guidance on what a reading system should do differently, depending on what it finds. 

This seems to be untestable, and I wonder what value it is adding to the spec.

**Comment by laudrain** [comment]
Do RS do something like parsing the value of the element ? 
Particularly if the no clue is given on the established system it should conform.
But if the "Authors attach an identifier-type property to assist in Reading System identification", then the RS could parse it.

**Comment by mattgarrish** [comment]
I believe this particular statement is also indicating that precedence is given to the identifier itself (because we were pushing URNs at one point) rather than to the more circuitous alternatives like a "refined" `identifier-type`.

As to what the reading system should do, that's never been in scope for the package metadata. It uses it however it needs to for whatever design and features it wishes to provide based on the information made available. We've really only ever laid out precedence rules to avoid inconsistencies when RSes attempt the same actions with the information. Any attempts to go further than that have usually run into strong objections.

**Comment by dauwhe** [comment]
Is the only use for this if the reading system wants to display the value of the identifier to the user, and would like to label the type of identifier? And we're saying you can try to guess the type of the identifier from the string itself, but if there's an `identifier-type` then you SHOULD use that instead of guessing?

**Comment by mattgarrish** [comment]
> and would like to label the type of identifier

Or make it an active link if it's a doi, or use it to query a database for more information (isbn search?), or any other creative idea someone might come up with. That's why we don't try to lay out what has to be done with the metadata.

> And we're saying you can try to guess the type of the identifier from the string itself, but if there's an `identifier-type` then you SHOULD use that instead of guessing?

Well, there's no guessing necessary in the case of URNs or DOIs, since the scheme is included in the value. You don't have to go looking to see if there is another piece of metadata somewhere else to spell out what is already there. The next paragraph explains why you can also add `identifier-type`:

> For additional precision (e.g., if the scheme cannot be determined from the value or could lead to an ambiguous result), Authors MAY attach an identifier-type property to assist in Reading System identification.

If `identifier-type` is attached, and the reading system processes refinement metadata, the reading system should use that value, yes. The problem with refines is that, except in a few cases like fixed layouts and media overlays, there's no requirement to process or do anything with refinement metadata.

**Comment by dauwhe** [comment]
> Or make it an active link if it's a doi, or use it to query a database for more information (isbn search?), or any other creative idea someone might come up with. That's why we don't try to lay out what has to be done with the metadata.

I think this is a case where we are starting to lay out what to do with the metadata, but then stopping before we get anywhere interesting. We say the reading system should parse the identifier, but we don't say why. 

I don't know of any reading systems that do this I believe some reading systems will display ISBNs, but I bet they get them from ONIX rather than from the EPUBs. 

The package spec is huge and covers a lot of ground. I wonder if it would be more productive to have a general statement that reading systems may choose to expose or not expose metadata to users however they see fit, with the existing exceptions about title and creator.

**Comment by murata2makoto** [comment]
I am wondering if any RS uses the unique identifier to remove existing publications of the same unique identifier in the local inventory.

**Comment by dauwhe** [comment]
> I am wondering if any RS uses the unique identifier to remove existing publications of the same unique identifier in the local inventory.

If so, I assume they first wouldn't determine what type of identifier it is, and then do something different if it was an ISBN instead of a UUID.

**Comment by mattgarrish** [comment]
> I think this is a case where we are starting to lay out what to do with the metadata, but then stopping before we get anywhere interesting.

Right, the general philosophy has been that the package document enables the creation of reading systems, it doesn't try to define the interfaces. The interesting things are supposed to happen outside the specification, and not be held back by the specification.

> We say the reading system should parse the identifier, but we don't say why.

We say how it should look for a scheme if one is needed, not that it should parse the identifier. That's in keeping with only identifying how to get necessary information without dictating how to use it.

> I wonder if it would be more productive to have a general statement that reading systems may choose to expose or not expose metadata to users however they see fit

Don't we have something like this, or maybe I'm getting confused with the internal/linked metadata clarifications? At any rate, there are no high-level RS requirements on the use of bibliographic metadata, so it's certainly the right interpretation.

**Comment by dauwhe** [comment]
> To determine whether an identifier conforms to an established system or has been granted by an issuing authority, Reading Systems SHOULD attempt to parse the value of the element.

> For additional precision (e.g., if the scheme cannot be determined from the value or could lead to an ambiguous result), Authors MAY attach an identifier-type property to assist in Reading System identification.

Perhaps change to 

> Reading Systems MAY attempt to determine whether an identifier conforms to an established system or has been granted by an issuing authority by parsing the identifier. Authors MAY attach an identifier-type property to assist in Reading System identification.

**Comment by mattgarrish** [comment]
It gets kind of soft and squishy when all we have are MAYs. We really don't even need to say RSes can parse the value, do we? They can do whatever they want in the absence of something they should or must be doing; all we're really highlighting here is that the property exists for this purpose.

So perhaps it could just be:

> To determine whether an identifier conforms to an established system or has been granted by an issuing authority, Reading Systems SHOULD check for an `identifier-type` property.

That way we could also drop this sentence after the example:

> When included, the identifier-type value SHOULD take precedence over value parsing the identifier.

**Comment by dauwhe** [comment]
Closed via #1233
