### ISSUE TITLE
Reading System display of dc:creator

### ISSUE THREAD

**Issue by dauwhe** [w3c/epub-specs#1218]
Packages says,

> The creator element SHOULD contain the name of the creator as a Reading System will present it to a user. The file-as property MAY be attached to include a normalized form of the name, and the alternate-script property to represent a creator's name in another language or script.

My built-in (but buggy) English language parser throws a warning on the first sentence... it feels backwards. Is the intent that the reading system SHOULD display the contents of `dc:creator` to the user as-is?

At least one reading system I've used today displays the `file-as` value rather than `dc:creator`.

**Comment by mattgarrish** [comment]
> Is the intent that the reading system SHOULD display the contents of `dc:creator` to the user as-is?

It's a creative way to work around requiring the reading system to do anything...

It comes from 2.0.1, but I think the intention was just to be aware that the property is for display so format it as you want readers to read it.

I'd say it's pretty much an unnecessary statement now, since we already say elsewhere that the minimal metadata in the package document is for reading system rendering.

**Comment by dauwhe** [comment]
Any better?

> The creator element SHOULD contain the name of the creator as the Author intends it to be displayed to a user.

**Comment by dauwhe** [comment]
Closed via #1235
