### ISSUE TITLE
[editorial] better identify SSV terms that are deprecated in XHTML but allowed in MO

### ISSUE THREAD

**Issue by rdeltour** [w3c/epub-specs#1222]
The [SSV](https://idpf.github.io/epub-vocabs/structure/) "Status of this Document" section says:

> Deprecated term are identified by the label **[DEPRECATED]**.

However, some of these deprecated terms are only deprecated in the context of Content Documents, but otherwise allowed in Media Overlays. This is the case of terms for tables, lists, and figures.

The deprecation of these is indicated in the "HTML usage context":

> HTML usage context: Deprecated

Maybe this form should be added to the "Status of this document" section as well? Or somehow harmonized with the regular way of identifying deprecated terms?

**Comment by mattgarrish** [comment]
That label is broadly applied, which is why it's never been put on the Media Overlay-specific terms. There are no contexts in which it is recommended to use terms marked `[DEPRECATED]`.

That's not the same as allowing/forbidding semantics in specific contexts, which is what the HTML usage context is getting into. We had to restrict tables/lists/figures because we didn't want to introduce the idea that you could just slap these on `div` in place of using the proper elements. (See the About section for more detail on this.)

Or more to the point, I don't see how we could apply the general label without causing more confusion, or having to write more explanation to explain that the opposite is now true.

If it's not clear enough, though, maybe we could add a parenthetical like:

> Deprecated terms are identified by the label [DEPRECATED]. These terms are no longer recommended for use in any context (refer to individual terms for additional restrictions on their use in specific contexts, such as in Content Documents).

**Comment by mattgarrish** [comment]
We might also want to consider changing the designation in the _HTML usage context_ sections from "Deprecated" to "Not Allowed" to be even more forceful about their restricted use.

These semantics were never intended for use outside of Media Overlay documents.

**Comment by rdeltour** [comment]
> We might also want to consider changing the designation in the _HTML usage context_ sections from "Deprecated" to "Not Allowed" to be even more forceful about their restricted use.

Yes, I think this would be a reasonable clarification.
