### ISSUE TITLE
Referencing the SSV Document

### ISSUE THREAD

**Issue by dauwhe** [w3c/epub-specs#1224]
We reference https://idpf.github.io/epub-vocabs/structure/ in EPUB 3.2

But the IDPF GitHub repo also has https://idpf.github.io/epub-vocabs/structure/structure.html which is a draft EPUB 3 CG Report.

Given that we're looking at editing this document due to #1222, should we move the document to the publ-epub-revision repo and have EPUB 3.2 reference the CG version?

**Comment by mattgarrish** [comment]
All the vocabs have been reformatted to CG drafts so that they can be dropped in in place of the existing IDPF documents whenever we publish 3.2. The idea was that we'd switch them to the "index.html" pages, thereby making them live and not having to change any paths or move documents and lose revision histories.

**Comment by mattgarrish** [comment]
Or if an example helps:

1. https://idpf.github.io/epub-vocabs/structure/index.html - current live vocabulary
2. https://idpf.github.io/epub-vocabs/structure/structure.html - working draft

And 2 gets copied to 1 when we publish.

**Comment by mattgarrish** [comment]
The trouble with moving it is that we'd lose all history of its changes in that repo. We could always move it back to /vocab/structure which I believe would resurrect the history in this repository, so at least we'd minimize the number of years lost.

It should really be formally published in /epub/vocab/structure within the same w3c setup as the 3.2 documents so that we have a static record of it. Putting a respec-generated version out through github pages probably is acceptable for a cg report, but it would be better to have consistency in publishing.

**Comment by mattgarrish** [comment]
I believe we can close this off since what to do with the SSV and external registries is already identified in our charter.
