### ISSUE TITLE
Clarify script elements

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1234]
I'm wondering if #1225 is clear enough yet. :)

The statement we have is fine as it cover xhr and fetches, but it leaves a hole about `script` tags, unless you follow the leap that a script will use them. Maybe for absolute clarity, we should add another bullet that says:

> - The [HTML] and [SVG] `script` elements MAY reference Remote Resources (i.e., from their `src` or `href` attributes, respectively) provided the resources are not [classic or module scripts](https://www.w3.org/TR/html/semantics-scripting.html#element-attrdef-script-type) [HTML].

But a big part of me thinks the qualification about remote scripts is pointless in the end. There are easy ways to work around whatever we say. More realistic is the reading system will either allow or deny these requests, which they are allowed to do by the scripting section.

**Comment by rdeltour** [comment]
@mattgarrish we may be overthinking this.

A `script` element can represent either:
- a [classic script](https://html.spec.whatwg.org/#classic-script) when the `type` attribute is missing or is a Javascript MIME type.
- a [module script](https://html.spec.whatwg.org/#module-script) when the `type` attribute is "`module`".
- a [data block](https://html.spec.whatwg.org/#data-block) otherwise.

If I understand correctly you're suggesting to allow the `script` element `src` attribute to reference a remote resource when the script is a data block.

**However**, HTML also says:
> When used to include data blocks, the data must be embedded inline, the format of the data must be given using the type attribute, and the contents of the script element must conform to the requirements defined for the format used. The src, async, nomodule, defer, crossorigin, integrity, and referrerpolicy attributes must not be specified.

So, problem solved? `script` elements can't be used to represent remote data resources; they can only reference remote Javascript, which we intend to disallow (correct?).

**Comment by rdeltour** [comment]
Btw remote data blocks are not reported by the Nu HTML Checker,  I just filed validator/validator#772.

**Comment by mattgarrish** [comment]
Ah, that makes sense. I knew you couldn't access the contents of a script element with a src, but didn't do the full research.
