### ISSUE TITLE
Semantic inflection vs semantic enrichment, epub:type, and microdata

### ISSUE THREAD

**Issue by dauwhe** [w3c/epub-specs#1291]
I found this statement from contentdocs very interesting:

> Unlike semantic inflection, which is about refining the structures within the markup, semantic enrichment enables the layering of meaning into the content in order to facilitate machine processing.

Why is this distinction important? I'm thinking about the future of `epub:type`. Trying to port that vocabulary to `@role` has proven very problematic. Why can't we just use microdata? I just did a quick experiment with (of course) Moby-Dick:

```html
<section class="body-rw Chapter-rw" itemscope="itemscope" itemtype="http://schema.org/Chapter">
<header>
<h1 itemprop="name"><span class="audio" id="c001s0000">Chapter 1. Loomings.</span></h1></header>
```

This passes EPUBCheck, but would easily port to an HTML serialization. And Google recognizes the microdata:

<img width="1299" alt="Screen Shot 2019-08-14 at 3 46 53 PM" src="https://user-images.githubusercontent.com/5687700/63051978-4c950e00-beac-11e9-9303-c381a65e9dd3.png">

What am I missing?

**Comment by mattgarrish** [comment]
> What am I missing?

epub:type was designed to facilitate publisher workflows, as there was a need to be able to encode more information about the structures but with clean separation from `class`. It could be used by reading systems, too, but that's why there's never been any general requirement to do so in the core specs (outside of the navigation document, of course, which is a specialized case).

That original purpose then kind of went haywire in the various extension specs, as more and more wishes got layered onto it.

Given that, I don't know that microdata is the optimal tool to replace it. It depends on what publishers want to do with their data.

But that's also why I'm not sure it's our problem to solve `epub:type` going forward. Microdata might be a solution for some. Custom elements for others. data-* for whomever... We can't figure out everyone's workflows.

**Comment by iherman** [comment]
I am not familiar with all the usages of `epub:type`, so I am just raising a red flag.

Microdata is more than "just" adding some semantic information on a single element. The example actually shows it: the `itemscope` creates a new scope for the section, and the `itemprop=name` provides a property for that scope. Which is of course fine in this case, but one has to be very careful on whether using some `epub:type` equivalent on the _descendents_ of that section would still be meaningful, otherwise it is possible to create meaningless or, worse, misleading information. 

Again, this may not be a problem. But it has to be carefully analyzed.

(Using RDFa, which is another alternative, leads to exactly the same problem.)

**Comment by mattgarrish** [comment]
> Microdata is more than "just" adding some semantic information on a single element.
> ...
> Again, this may not be a problem. But it has to be carefully analyzed.

Right, and `epub:type` went from inflecting simple semantics on an element to building all kinds of quasi-relationships and connections between data.

What happens with `epub:type` indeed depends on what a replacement is expected to provide. I don't have the answer to that, but if it's a workflow issue I think we can have a useful vocabulary without having to define the implementation for it.

**Comment by mattgarrish** [comment]
Should we close this issue?

It's kind of a larger philosophical problem that needs resolving whenever we do a new major version and move beyond XHTML, but probably something we just have to live with for 3.0.
