### ISSUE TITLE
epub:type for hyperlinks

### ISSUE THREAD

**Issue by VeryGoodErotica** [w3c/epub-specs#1297]
Hello, I apologize if this is addressed another way and I did not find it.

When looking at the epub:type vocabulary the only page I could find that describes it is https://idpf.github.io/epub-vocabs/structure/ which might predate W3C taking over, again I apologize if there is an update that I just could not find.

When I make a hyperlink using an `a href=` tag, it generally falls into one of four categories that I think would be useful for a11y to be able to semantically identify.

1. Internet Resource. Currently I use `title="Internet hyperlink"` but the title attribute is not very useful on many platforms that read an ePub. So I also use `class="internet"` which then has CSS put a glyph for a globe with meridians before the link. The intent is to make sure the reader knows they need an Internet connection to follow the link. I would prefer to use something like `epub:type="webresource"` or whatever so that assistive technology can identify the link as one that requires a connection to the web (I'll still do the visual globe thing too) rather than relying upon interpretation of the title attribute.
2. Skip Past Content. If I have a code block or configuration file example, a user with good vision using can visually skip past it. I put in links that allow screen reader users to skip past it too. Something like `epub:type="skipblock"`
3. Link to Content within Same Chapter. For these links I currently use `title="[same chapter]"` but that then precludes the use of the title attribute for other uses. perhaps something like `epub:type="linksamechapter"` could exist to make it clear to readers that the link is part of the same chapter. That could be determined programatically if one page per chapter is used, which I do, but I do not believe chapters are required to have all content on the same spine page.
4. Link to Content in Separate Chapter. Something like `epub:type="linkseparatechapter"

The first two are the most important for me to see a markup solution for, I am guessing other users may have other needs, and an #a11y guru should probably also give input.

But I thought I'd let this perceived need of mine be known.

Thank you for your time.

**Comment by Doktorchen** [comment]
Just my ideas:

1. can be distinguished from others by the user agent looking at the content of the href attribute.
At least this works too to distinguish between links to fragment identifiers in the same document and relative links to other documents.

For 2 something like title="skip code block" might be informative for the audience already. Else it is almost the same as 3.

There are as well rel and rev attributes to indicate relations between the current document and the referenced resource. Did you take them into account as well.
At least some rel/rev values are predefined for example Next, Prev, Index, Glossary, Chapter, Subsection, Appendix, Help, Start in the old XHTML/HTML4 recommendations, maybe worth to look, what is available and accepted for (X)HTML5, a few values are in the recommendation, more are registered in a specific list outside.
Someone could register values specific for digital books as well.
From purpose and semantics rel/rev seem to be the right methods to indicate the purpose of a link ... and it would not be specific for EPUB only, therefore easier usage for content published in different formats/media.

**Comment by dauwhe** [comment]
None of them are EPUB-specific, but apply to, well, pretty much any web content. So any potential solution should also not be EPUB-specific. Second, I'm not aware of much user demand for such information. Are AT users requesting this? 

>   Internet Resource. Currently I use `title="Internet hyperlink"` but the title attribute is not very useful on many platforms that read an ePub. So I also use `class="internet"` which then has CSS put a glyph for a globe with meridians before the link. The intent is to make sure the reader knows they need an Internet connection to follow the link. I would prefer to use something like `epub:type="webresource"` or whatever so that assistive technology can identify the link as one that requires a connection to the web (I'll still do the visual globe thing too) rather than relying upon interpretation of the title attribute.

I agree with @Doktorchen that the `rel` attribute is the proper semantic for most of these. And of course we have `title` and `@role` and the link text itself to give the user information about the nature of the linked content.

 But I'm wondering about the utility as described. This doesn't tell me if the link works or not, it just tells me that the link requires an internet connection. I might not know if I'm online at the moment I read the link. So even having this information isn't enough for me to know if the link will work. 

Luckily I can just click the link, and the user agent will let me know if it worked :)

> Skip Past Content. If I have a code block or configuration file example, a user with good vision using can visually skip past it. I put in links that allow screen reader users to skip past it too. Something like `epub:type="skipblock"`

Perhaps such content could be semantically coded as `aside`.

>   Link to Content within Same Chapter. For these links I currently use `title="[same chapter]"` but that then precludes the use of the title attribute for other uses. perhaps something like `epub:type="linksamechapter"` could exist to make it clear to readers that the link is part of the same chapter. That could be determined programatically if one page per chapter is used, which I do, but I do not believe chapters are required to have all content on the same spine page.

> Link to Content in Separate Chapter. Something like `epub:type="linkseparatechapter"`

Could you explain in more detail why a user might behave differently if this information was made more explicit?

**Comment by mattgarrish** [comment]
(Sorry, somehow I missed this issue.)

> Second, I'm not aware of much user demand for such information. Are AT users requesting this?

There is a similar accessibility issue for the web -- links that cause new windows/tabs to open. It can confuse the user when nothing is announced and suddenly they can't go back to where they were (e.g., for users with cognitive disabilities). The more common solution I've heard of to this problem is to include an icon within the link to identify external links, with an alt text that indicates you're leaving the site. See: https://www.w3.org/TR/WCAG20-TECHS/G201.html

I'm not sure how critical this is for reading apps, though, since web links spawn a whole different app (a browser). If you're reading inside a browser, there's no specific problem with users leaving to another site so long as you don't try to spawn a new window/tab. I'm sure @GeorgeKerscher and @avneeshsingh will know more, though.

At any rate, epub:type isn't going to solve this problem, as it isn't used by reading systems or AT. It may not be a helpful ARIA addition, either, as the affected users groups extends beyond AT.

> Perhaps such content could be semantically coded as `aside`.

This gets to the general problem of skippability/escapability. I believe there are various elements that AT will allow users to bypass so long as the content is semantically tagged. I don't know that linking past such content will be as helpful, as it also potentially has the detrimental effect of loading a document up with unnecessary links (being able to cycle through the links on a page is a feature of most AT).

> Could you explain in more detail why a user might behave differently if this information was made more explicit?

The more common problem tends to be once you follow a link, anywhere, it may not always be easy to get back where you were. More semantics isn't going to solve that issue, though. If a reading system/AT can tell you what document you're in, there's no issue knowing where you've gone. If it doesn't provide that information, then the semantics probably aren't going to give you enough useful information, anyway.

**Comment by VeryGoodErotica** [comment]
This can be closed. I found something that works. AT can read the title, for those w/o AT I can use CSS selectors to place a glyph in front of the link that lets the user know about the link (I describe them at the beginning of my book) - so when a user not using AT reads the ePub, they know if the link is to an external resource or to the glossary or to skip past boring content (e.g. describing how to get a signed TLS certificate when they already know how) etc. The CSS selector works even on old ePub 2 readers so don't need anything new to achieve the purpose.
