### ISSUE TITLE
Remove CSS Speech support

### ISSUE THREAD

**Issue by dauwhe** [w3c/epub-specs#1298]
Spec [says](https://www.w3.org/publishing/epub32/epub-spec.html#confreq-rs-epub3-tts)

> If it supports Text-to-Speech (TTS) rendering, it SHOULD support Pronunciation Lexicons [ContentDocs32], [CSS3Speech] and SSML attributes [ContentDocs32] in XHTML Content Documents.

CSS 3 Speech is now obsolete, and has been published as a retired note, due to a lack of implementation. We should remove this dependency from EPUB.

**Comment by mattgarrish** [comment]
SSML and PLS are unlikely to go anywhere, too.

APA has a [pronunciation task force](https://www.w3.org/WAI/APA/task-forces/pronunciation/) looking into this problem.

**Comment by murata2makoto** [comment]
SSML is very heavily used by the biggest textbook publisher in Japan.

**Comment by mattgarrish** [comment]
> SSML is very heavily used by the biggest textbook publisher in Japan.

Do any reading systems or assistive technologies support it, or is it only in content?

I don't expect we'd remove them, but recommending they be implemented by reading systems when there's certainly been no widespread effort to implement them seems unrealistic.

**Comment by murata2makoto** [comment]
> Do any reading systems or assistive technologies support it, or is it only in content?

Lentrance Reader supports SSML.  It is a product of a company named Lentrance.  Tokyo Shoseki owns stocks of this company. 

I am not a big fan of SSML, since it requires a lot of authoring cost.  But we should not underestimate it, especially for education.

**Comment by VeryGoodErotica** [comment]
Hi, I am looking for ePub readers that support PLS and SSML. All I have found is people asking the same question - going all the way back to 2013 and being told they do not yet exist.

But unless there is a technology to replace them I do not want to see them leave the spec, I would rather see a campaign to try and get some readers to support them. I am using both in an ePub I am currently authoring even though I have no way to test - in hopes that if someone who needs TTS buys my book, they know about a ePub reader I can't find and will benefit.

With respect to CSS text to speech, quite frankly I think CSS is the wrong place for it.

I will look for Lentrance Reader and see if it at least lets me test my own.

As far as PLS/SSML being a big authoring cost, I do not know what WAI considers it to be, but I would consider TTS lexicons to be WCAG AAA lever of support - which the way I treat AAA is do it if I can afford to, and note that it hasn't been done if I can't so that users who need it know it isn't there (A and AA I treat as critical must fix bugs)

I guess what I'm saying is I would encourage proper lexical markup but do not consider a critical bug if not present. Kind of like ASL interpreter in a video - that's AAA while captions are AA - the former is good to have if you can afford to hire an interpreter, but the latter is a must.

I have a (now deceased) brother who was profoundly deaf, low vision, and autistic - so I am a bit biased towards a11y due to personal relations in my family, but I do not want to see PLS/SSML removed unless there is something better to replace them. I would much rather see a campaign to get them supported in readers.

Just my thoughts.

**Comment by mattgarrish** [comment]
> CSS 3 Speech is now obsolete, and has been published as a retired note, due to a lack of implementation.

It's back at CR as of last year, though: https://www.w3.org/TR/css-speech-1/

No one can quite put a stake in it... :smile:

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-05-13-epub#section2) on 2021-05-13

List of resolutions:

- ***[Resolution No. 1](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-05-13-epub#resolution1):  Close issue 1298***

<details><summary><i>View the transcript</i></summary>

### 2. Remove CSS Speech Support 

_See github issue [#1298](https://github.com/w3c/epub-specs/issues/1298)._




**Dave Cramer:** a while ago the CSS Speech module was unimplemented, but apparently it has come back, and is in CR now  
… though still not aware of too many implementations, at least in epub world  
… given CR status, not comfortable taking it out at this point  

**Brady Duga:** there hasn't been much harm to it being there yet, so it seems fine to leave it  

**Matt Garrish:** as its unimplemented, nobody has done anything with it  
… but if we're not touching PLS or SSML then we can probably leave it too  

**Wendy Reid:** do we know why CSS put this back on rec track?  
… wonder if it is reviving due to resurgence of voice tech  

**Dave Cramer:** did some quick searching this AM, and there seem to be a few voice over things that will read a few of these properties  

**Matt Garrish:** it's also been stripped down a little  

**Dave Cramer:** okay, so we close the issue  

> **Proposed resolution: Close issue 1298** *(Wendy Reid)*

> *Ben Schroeter:* +1

> *Shinya Takami (高見真也):* +1

> *Matthew Chan:* +1

> *Toshiaki Koike:* +1

> *Wendy Reid:* +1

> *Dave Cramer:* +1

> *Matt Garrish:* +1

> *Masakazu Kitahara:* +1

> *Brady Duga:* +1

> *Fred Chasen:* +1

> ***Resolution #1: Close issue 1298***

</details>

**Comment by danielweck** [comment]
> SSML is very heavily used by the biggest textbook publisher in Japan.

Heads-up - “spoken html” first working draft:

https://www.w3.org/TR/spoken-html/#multi-attribute-approach-for-including-ssml-in-html

> Publishers in Japan use a similar technique from EPUB 3 for the SSML phoneme element.

Related issue: https://github.com/w3c/pronunciation/issues/57
