### ISSUE TITLE
Request for more detailed definition of Content Display Area

### ISSUE THREAD

**Issue by dauwhe** [w3c/epub-specs#1306]
This is something of a follow-up to #898. 

The spec defines Content Display Area as:

> The area within the Viewport dedicated to the display of EPUB Content Documents. The Content Display Area excludes any borders, margins, headers, footers or other decoration a EPUB Reading System might inject into the Viewport.

>In the case of synthetic spreads, the Viewport contains two Content Display Areas.

I'm hearing from reading system developers that this isn't clear enough; for example content authors are complaining about reading system headers impinging their content. But is it possible to have a more detailed definition? Presumably a reading system gets to decide how much of the screen they reserve for UI etc. 

I'm hoping that this issue can allow people to comment on what problems they've faced when implementing this or authoring content.

**Comment by bduga** [comment]
Some fun questions: How does the Content Display Area differ from the viewport? Does any of this apply outside of fixed layout content? If so, how? And what the heck is up with our definition of viewport?

**Comment by mattgarrish** [comment]
> Does any of this apply outside of fixed layout content?

Don't believe so. As far as I remember, CDA was used in the original FXL note and then around 3.1 we realized we didn't have any sort of formal definition for it.

> How does the Content Display Area differ from the viewport?

CDA is just the part of the viewport where the content is rendered, as I understand it. Wasn't the reason for this because authors wanted full bleed images but the reading system interface was getting in the way? So we define the two separately so we can say that reading systems should give the full area to content for certain FXL displays.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-05-13-epub#section5) on 2021-05-13

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

### 5. Detailed definition of Content Display Area 

_See github issue [#1306](https://github.com/w3c/epub-specs/issues/1306)._




**Dave Cramer:** supposed to be the area in the display for epub content documents, excluding borders, margins, etc. injected by RS  
… touches upon what part of screen real-estate should be controlled by author vs RS  
… is just purely a FXL issue?  

**Fred Chasen:** one place where this comes up is the little page dog-ear icon that clashes with book  

**Matt Garrish:** we haven't spec'ed what a viewport is, then we tried to describe a part within the viewport where content is displayed  
… hard for us to be very specific about this  

**Dave Cramer:** then is it possible to be more specific? Esp. given that RS might mess with putting more margin on body so that content doesn't clash with bevel  
… is there anything to be gained by being more precise?  

> *Brady Duga:* +1

**Wendy Reid:** are we talking about reflow, or FXL? Because the problems around headers, footers, etc. are mainly a problem for reflow where authors might have their own ideas about these regions  
… for FXL the only question is whether it fits within the screen  

**Brady Duga:** Content Display Area is only used within FXL (except for definitions)  
… the idea was that RS should not mess with visuals in cases of FXL  
… but Content Display Area technically applies to everything, because its just in the definitions  

**Dave Cramer:** so is restricting the definition a solution?  

**Brady Duga:** we could  
… also, looking at the definitions, its not clear what the difference between viewport and Content Display Area is supposed to be  

**Ben Schroeter:** I think there should be general guidance that RS should not obscure publisher content  
… for the question at hand, I think the definition we have is suitable  
… not sure how much more precise we can be  

**Dave Cramer:** one more factor is that we've quite often had request for "full bleed" even in reflow  
… e.g. where authors want something like an image to take up the entire screen  
… e.g. in chapter opening photos in recipe books  

**Matt Garrish:** should we try to move it over to RS spec, and try to explain the concept of Content Display Area?  
… seems to apply only to RS rendering of FXL content  

> *Shinya Takami (高見真也):* +1 to mgarrish

**Dave Cramer:** this could really use a diagram to help explain  
… i'll look into that  

**Ben Schroeter:** maybe we just need to reframe the question to how should RS accommodate the desire for full bleed content?  

**Brady Duga:** there are plenty of FXL implementations that enable full bleed  

**Dave Cramer:** and some user gestures make an overlay appear over the content  

</details>
