### ISSUE TITLE
The default value of rendition:flow and testing

### ISSUE THREAD

**Issue by dauwhe** [w3c/epub-specs#1313]
[We say](https://www.w3.org/publishing/epub32/epub-packages.html#layout-property-flow-usage):

> The default value auto MUST be assumed by Reading Systems as the global value if no meta element carrying this property occurs in the metadata section. Reading Systems MAY support only this default value.

I'm trying to figure out if it's possible to violate this rule. The [definition of auto](https://www.w3.org/publishing/epub32/epub-packages.html#layout-property-flow-values) is:

> The Author does not have a preference for overflow handling. The Reading System MAY render overflow content using its default method or a user preference, whichever is applicable.

So... say a book has no `rendition: flow` element. The reading system is therefore obligated to... use the auto value, which means it can choose any of the possible values? It could choose to `paginate`. It could choose to do `scrolled-continuous`. It could choose to do `scrolled-doc`. 

Is the original MUST statement thus untestable?

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-01-07-epub#section3) on 2021-01-07

List of resolutions:

- ***[Resolution No. 2](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-01-07-epub#resolution2):  Change the language for `rendition:flow` to define the default is auto, but remove the MUST statement/ untestable assertion.***

<details><summary><i>View the transcript</i></summary>

### 3. The default value of `rendition:flow`.

_See github issue [#1313](https://github.com/w3c/epub-specs/issues/1313)._




**Wendy Reid:** this came up during testing.  
… `rendition:flow` is a property by which an author can determine if pagination style is scrolled, paginated, or auto.  
… if the RS supports it.  
… the issue is that the spec says that the default value is auto, and that the RS may choose to support only the default.  
… since auto means that its basically the RS's choice, does this make the assertion untestable?.  

**Brady Duga:** i think this is solved by saying that the default is auto, period..  
… with the understanding that if authors are not explicit, then they get default functionality.  

**Wendy Reid:** to clarify, W3C says any time we make a MUST statement, the assertion must be accompanied by a test.  
… or, the statement shouldn't be MUST.  
… if this results in something untestable, we're going to run into issues later.  

**Ben Schroeter:** or change MUST to SHOULD?.  

**Garth Conboy:** that would only mean that the RS SHOULD do whatever it wants. It works around the W3C's testability requirement, but doesn't make much of a functional difference.  

> **Proposed resolution: Change the language for `rendition:flow` to define the default is auto, but remove the MUST statement/ untestable assertion.** *(Wendy Reid)*

> *Garth Conboy:* +1.

> *Matthew Chan:* +1.

> *Ben Schroeter:* +1.

> *Toshiaki Koike:* +1.

> *Brady Duga:* +1.

> *Wendy Reid:* +1.

> *Shinya Takami (高見真也):* +1.

> *Masakazu Kitahara:* +1.

> ***Resolution #2: Change the language for `rendition:flow` to define the default is auto, but remove the MUST statement/ untestable assertion.***

</details>

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-04-15-epub#section2) on 2021-04-15

List of resolutions:

- ***[Resolution No. 1](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-04-15-epub#resolution1):  Merge PR 1616***

<details><summary><i>View the transcript</i></summary>

### 2. language around rendition:flow 

_See github issue [#1313](https://github.com/w3c/epub-specs/issues/1313)._




_See github pull request [#1616](https://github.com/w3c/epub-specs/pull/1616)._




> *Dave Cramer:* See [Relevant comment within the PR](https://github.com/w3c/epub-specs/pull/1616#pullrequestreview-629109802)

**Dave Cramer:** I was concerned that we say RS MUST use auto as a default value, but auto means "RS, do whatever you want"  
… not sure that it was testable  
… but Dan thinks it is testable  
… so maybe we should just undo that resolution  
… if it is testable i'm fine with restoring that requirement  

**Brady Duga:** agree. Not worth spending much time on.  
… and agree with dlazin's testing method for it  

**Dave Cramer:** yes, we just need to see that things are consistent between having explicit auto value and "implied" auto  

> **Proposed resolution: Merge PR 116** *(Wendy Reid)*

> *Brady Duga:* +1

> *Dave Cramer:* +1

> *Wendy Reid:* +1

> *Matthew Chan:* +1

> *Dan Lazin:* +1

> *Masakazu Kitahara:* +1

> *Toshiaki Koike:* +1

> *Marisa DeMeglio:* +1

> *Shinya Takami (高見真也):* +1

> ***Resolution #1: Merge PR 1616***

</details>
