### ISSUE TITLE
Practical application of using doc-endnote for endnote content

### ISSUE THREAD

**Issue by ghost** [w3c/epub-specs#1316]
We are currently in the process of researching/developing the inclusion of `doc-endnote` and `doc-endnotes` as roles for endnote content in the EPUBs we distribute.

For EPUB, we cannot consistently rely on reading systems to suppress HTML list numbers/bullets, so we have resorted to using divs as part of the structure. Thus, we would like to use the following structure (as specified in this example on the [DPUB-ARIA 1.0 page](https://www.w3.org/TR/dpub-aria-1.0/#desc-doc-endnote)):

```
<section role="doc-endnotes">
   <h2>Notes</h2>
   <section id="ch1-notes">
      <h3>Chapter 1</h3>
      <div role="list">
         <p id="6baa07af" role="doc-endnote">1. Additional results of this study can be found at … </p>
         <div id="7b2c0555" role="doc-endnote">
            <p>2. The primary source of infomation …</p>
            <p class="note-cont">In the case of secondary studies …</p>
         </div>
         …
      </div>
   </section>
</section>
```

However, we’ve run into a few issues that have made us rethink the above:
* While `doc-endnote` has the `listitem` superclass role, [`listitem` may be determined to be the only role allowed in `role="list"`](https://github.com/daisy/ace/issues/274#issuecomment-612891332)
* In the Ace checker command line (1.1.1), [`<div>` is not a proper fallback for `doc-endnote`](https://github.com/daisy/ace/issues/254)
* [`doc-endnote` may be deprecated in the future](https://github.com/daisy/ace/issues/274#issuecomment-612891332)

Our questions are as follows:
* What we should use in place of `doc-endnote` if its future is up in the air? We wouldn’t consider all endnote sections to be lists, but for practical applications, should we just use `role="listitem"` instead?
* Would there be an issue for linking to an element with `doc-noteref`?
* Is there any issue adding `epub:type="endnotes"` and `epub:type="endnote"` to their respective elements?

**Comment by mattgarrish** [comment]
Yes, the inheritance of listitem only arose after we published the DPUB-ARIA module, so it's really made a mess of doc-endnote and doc-biblioentry.

Given that the only viable solution to this problem is create a new list role every time we need a list item role, I suspect the next update to the module will make doc-endnote more like doc-footnote. That, or we may even just deprecate doc-endnote and use doc-footnote exclusively going forward.

My advice at this point would be to avoid doc-endnote. It somewhat stands to reason that the list entries in an endnotes section represent the endnotes, so it's not all that critical (when it's not imparting list semantics).

If you prefer, though, you could use doc-footnote on an element within the list item, so going by your example:

```
<section role="doc-endnotes">
   <h2>Notes</h2>
   <section id="ch1-notes">
      <h3>Chapter 1</h3>
      <div role="list">
         <div role="listitem">
            <p id="6baa07af" role="doc-footnote">1. Additional results of this study can be found at … </p>
         </div>
         ...
   </section>
</section>
```

With regards to `epub:type`, it doesn't matter for accessibility if or how you use them.

**Comment by GeorgeKerscher** [comment]
IMO you will need a link back to the spot you left off reading. This will allow readers to follow the link and then get back to the spot they left off reading after they read the end note.

**Comment by ghost** [comment]
Thanks all! Everyone's insight has been very helpful in getting us closer to a direction we can take.

**Comment by mattgarrish** [comment]
Closing this issue as the guidance already suggested about not using doc-endnote is correct. The forthcoming DPUB-ARIA 1.1 module will deprecate both doc-endnote and doc-biblioentry because of the list inheritance problems (we should have a first public working draft soon).
