### ISSUE TITLE
Clarify version number is for EPUB 3

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1349]
Although we've abandoned the idea of incrementing the package version number, the spec prose still makes it sound revision specific:

> The version attribute specifies the EPUB specification version to which the given EPUB Package conforms. The attribute MUST have the value "3.0" to indicate compliance with this version of the specification.

It might be helpful to change the last sentence more along the lines of:

>The attribute MUST have the value "3.0" to indicate conformance with EPUB 3.

**Comment by dauwhe** [comment]
Motivation: https://github.com/w3c/epubcheck/issues/1188

**Comment by Doktorchen** [comment]
Unfortunately different versions of HTML5 are not backwards compatible.
See for example the allowed content model for tables in HTML5.0 and later variants.
For EPUB 3.0 one can assume, that authors have to use (X)HTML5.0, for 3.2 it seems up to the author, what to use (including WHATWG dialect).
If checking of EPUBs has a meaning, one has to provide exactly, what to check.
If everything is 3.0, there is no way to check properly in a defined way, because HTML5 or the future SVG2 have no version indication on the document level.

Currently simply authors only can produce EPUB3.0, because EPUB3.2 has no version indication (EPUB3.0 contains no hint, that the version number is  not specific for this version). If a checking program assumes something different, it has a risk to fail and to provide wrong, useless information for authors.

If it is intended, that  books created with respect to a future EPUB version cannot be checked anymore, it is a good idea to remove the version attribute completely, as done for HTML5, resulting finally in a situation, that EPUB is a simple ZIP file with arbitrary content ;o)

**Comment by mattgarrish** [comment]
> it is a good idea to remove the version attribute completely

You can't remove the version attribute, or increment it, without consequences in existing EPUB 3 reading systems. While this may be an idea for an EPUB 4, it's [explicitly out of scope](https://www.w3.org/2020/08/epub-wg-charter.html#out-of-scope) in the working group's charter to make any changes to the attribute.
