### ISSUE TITLE
Where to put the conformance criteria?

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#1359]
At the moment the content document has inherited the various conformance criteria from packages, OCF, content documents, etc. I think the customary is to have the conformance criteria at the beginning of a W3C spec, so maybe we should regroup them in one place (although leaving them in subsections may make a lot of sense).

**Comment by mattgarrish** [comment]
There is a very [high-level conformance section](https://w3c.github.io/epub-specs/epub33/core/#sec-epub-conf), but many of the requirements you might expect to find there are defined at the [package level](https://w3c.github.io/epub-specs/epub33/core/#sec-package-conformance) because you can bundle more than one package in a container.

There's kind of a cascading effect, too, so merging is more complicated than just bundling everything together. What I think might happen is the package requirements will become more and more bloated with lower-level requirements until it's hard to read anything.

But I'll spend some time fiddling around with them. We have a lot of "content conformance" sections, for sure.

**Comment by mattgarrish** [comment]
Closed with #1382
