### ISSUE TITLE
Document type declarations for SMIL?

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#1371]
EPUB media overlay uses a subset of SMIL.  Although SMIL has DTDs, EPUB media overlay does not use them.  Instead, MO has relied on RELAX NG, Schematron, and NVDL for validation.  I thus propose not to allow SMIL DTDs in EPUB.  Do people agree?

This issue is to create § B. Allowed External Identifiers as proposed in #1368.

**Comment by mattgarrish** [comment]
We're using a modified version of the DAISY profile, I believe, so I don't think it's really an option to specify a doctype in media overlay files.

/cc @marisademeglio @danielweck

**Comment by marisademeglio** [comment]
Media Overlays doesn't reference the [DAISY profile](https://www.w3.org/TR/SMIL3/smil-daisy-profile.html#DaisyProfileNS-DocumentConformance), which, as far as I am aware, was never implemented in the real world. MO doesn't specify a `baseProfile` attribute and doesn't have a DTD. We don't explicitly prohibit a doctype declaration though.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2020-11-06-epub#section3).

- `RESOLVED:  Merge PR #1368 to address outstanding DTD issues, and close GH issues 1369-1373`
<details><summary><i class="differentiate">View the transcript</i></summary>
Wendy Reid: we had resolutions at the F2F, and further discussions on github<br/>
… and came to a happy place<br/>
Matt Garrish: <a href="https://github.com/w3c/epub-specs/pull/1368">https://github.com/w3c/epub-specs/pull/1368</a><br/>
Matt Garrish: where we ended up was…<br/>
… we put in an allowance for a specific set of external identifiers that we have put in an appendix<br/>
… we have SVG and MathML that are allowed to be used in content docs or in separate files<br/>
… and we made a restriction against external entities in the internal DTD subset<br/>
… so it prevents some security issues but eases authoring<br/>
… so we’ll no longer force people to remove SVG DTDs from tool-generated files<br/>
… I’m hoping this is it :)<br/>
Ivan Herman: tech comment<br/>
… in fact, the changes are such that<br/>
… makes possible something that I’m not sure we really use<br/>
… I can define as part of an internal entity something that won’t go out to the network<br/>
… I’m not sure if this feature is in use<br/>
… formal comment<br/>
… there was a formal resolution on the previous version; this PR slightly changes that<br/>
… can we get a formal resolution to merge, and also close a bunch of issues which were examples of the problem?<br/>
Proposed resolution: Merge PR #1368 to address outstanding DTD issues, and close GH issues 1369-1373 (Wendy Reid)<br/>
Garth Conboy: +1<br/>
Matt Garrish: +1<br/>
Ivan Herman: +1<br/>
Charles LaPierre: +1<br/>
Matthew Chan: +1<br/>
Wendy Reid: +1<br/>
Brady Duga: +1<br/>
George Kerscher: +1<br/>
Laura Brady: +1<br/>
Bill Kasdorf: +1<br/>
Ben Schroeter: +1<br/>
Resolution #1: Merge PR #1368 to address outstanding DTD issues, and close GH issues 1369-1373<br/>
</details>
