### ISSUE TITLE
(Editorial) legacy?

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#1376]
[§4.2.3.7](https://w3c.github.io/epub-specs/epub33/core/#sec-pkg-legacy) is the section listing legacy features like NCX, guide and meta elements. I believe the W3C terminology (e.g., in the HTML spec, in relation to `<applet>` or `<marquee>`) is 'obsolete'. Should we adopt this terminology?

**Comment by mattgarrish** [comment]
Obsolete as defined in the current HTML spec doesn't match the legacy features. They don't generate warnings, for one, and they're not technically part of the current standard. They aren't supported in EPUB 3 reading systems, and aren't supposed to be, but are allowed in the container so that if an EPUB 2 reading system is used to open the file it will be able to provide some level of rendering. Kind of a different beast.

The deprecated features more closely resemble HTML's obsolete, as they're features that have slowly been dropped due to poor design, support or both. But I don't know if we want to get into changing labels now.

**Comment by iherman** [comment]
deprecated?

**Comment by mattgarrish** [comment]
https://w3c.github.io/epub-specs/epub33/core/#sec-overview-unsupported

**Comment by iherman** [comment]
:-( You can't win...

O.k., let us leave this one alone, not worth getting there. Closing...

**Comment by mattgarrish** [comment]
It was painful even getting agreement on legacy and deprecated. Picking at old wounds just leads to more bloodshed. :)
