### ISSUE TITLE
Error in Example 36

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#1381]
In [Example 36](https://w3c.github.io/epub-specs/epub33/core/#fxl-ex4) it says:

```xml
properties="page-spread-right rendition:layout-pre-paginated"
```

and it should say (I guess)

```xml
properties="rendition:page-spread-right rendition:layout-pre-paginated"
```

**Comment by mattgarrish** [comment]
There's nothing wrong with the example; your alternate is exactly the same as the original.

`page-spread-right` and `page-spread-left` existed before the full fixed layout metadata came along. The `rendition:page-spread-right` and `rendition:page-spread-left` properties are just aliases so that people don't get confused by the lack of prefixes for the two older properties.

**Comment by iherman** [comment]
Ah. I found the reference to the alias. Maybe it is worth emphasizing this in the caption of the example...

**Comment by mattgarrish** [comment]
Works for me.
