### ISSUE TITLE
Vocabulary association regrouping?

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#1386]
This is just (editorial) musing...

At the moment, we have a vocabulary association section as [§4.3.2](https://w3c.github.io/epub-specs/epub33/core/#sec-metadata-assoc), as part of the section on publishing metadata and then we have a somewhat similar section [§5.1.3.1.3](https://w3c.github.io/epub-specs/epub33/core/#sec-contentdocs-vocab-association) as part of the content document spec. The latter refers back to the former, in fact but with different defaults and namespaces.

This is of course the result of the original structure. I wonder whether it is not possible/better to factor this out in one place, that is in its own section. It may make the overall structure cleaner.

(I am not sure this is necessary, but just raising the question...)

**Comment by iherman** [comment]
I also realized that there is no _one_ place listing all the namespaces that are used in this document, whether they are predefined prefixes or not. Predefined prefixes are listed at those two places above, and the two namespaces that are used elsewhere (`epub:` and `ssml:`) are defined in [§1.6.1](https://w3c.github.io/epub-specs/epub33/core/#sec-shorthands-ns). 

I think that, as part of the reorganization above, we could regroup all the various namespaces in one place, just as, for example, in the [JSON-LD 1.1](https://www.w3.org/TR/json-ld11/#conformance). It would help the reader, imho.

**Comment by mattgarrish** [comment]
> I also realized that there is no _one_ place listing all the namespaces that are used in this document, whether they are predefined prefixes or not.

That's because they aren't universally applicable. The predefined prefixes for the package document are not usable in content documents (and vice versa) as they serve different purposes.

That's why there are separate sections, as the package the mechanism is more like traditional RDFa and in Content Documents and Media Overlays it's kind of a adaptation to enable semantic inflection. There's a stronger relation between how CD and MO work, but I'm not sure if we could tie all three together beyond just the syntax of the prefix attribute.

**Comment by iherman** [comment]
Well, the prefix attribute, the syntax, the concept of CURIE-s as used here, etc, are all used across all sections. The fact that the namespaces themselves are used differently across the various parts of the standard is fine, the table can be annotated accordingly...

Anyway. This is not an important thing, so I yield to what you prefer.
