### ISSUE TITLE
Disallowed namespaces for custom attributes (§5.1.3.6)

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#1388]
The text disallows adding custom attributes to the xhtml and epub namespaces. Shouldn't at least ssml be disallowed, too?

**Comment by murata2makoto** [comment]
SSML is *heavily* used by some publishers in Japan.  Dropping them from EPUB 3 is unacceptable.

**Comment by iherman** [comment]
> SSML is _heavily_ used by some publishers in Japan. Dropping them from EPUB 3 is unacceptable.

@murata2makoto, you completely misunderstood what I said, probably I was not clear enough. It is _**by no means**_ proposing to drop SSML from EPUB3.

[§5.1.3.6](https://w3c.github.io/epub-specs/epub33/core/#sec-xhtml-custom-attributes) talks about custom attributes in XHTML content. The relevant text is:

> Custom attributes MAY be included on any element in an XHTML Content Document provided such attributes are from a foreign namespace, which is defined as a namespace [XML-NAMES] that does not map to either of the following URIs:
>
> * http://www.w3.org/1999/xhtml
> * http://www.idpf.org/2007/ops

My reading is that the aim is to _protect_ some privileged namespaces. As SSML can be spread over all over the content document, my proposal is to _protect_ the SSML namespace, i.e., adding `https://www.w3.org/2001/10/synthesis
` to that list.

**Comment by murata2makoto** [comment]
@iherman 

Sorry for my confusion.  I agree to list the SSML namespace in this list.

**Comment by mattgarrish** [comment]
The ops namespace is there because we wanted to ensure control over anything "epub" (i.e., avoid a reading system adding an attribute that looks like it comes from a spec). The xhtml namespace purpose kind of eludes me, as HTML attributes aren't in any namespace.

We kind of violated the rules of good behaviour by minting SSML attributes in the first place (I don't know that that was coordinated in any way). And given that the world is moving on from this idea, I don't know how important it is to worry about.

We could always throw a blanket restriction over "http(s)://www.w3.org/" and call it a day?

**Comment by iherman** [comment]
> We could always throw a blanket restriction over "http(s)://www.w3.org/" and call it a day?

and the idpf.org namespaces? Maybe a blanket over w3.org _and_ idpf.org is fine. Essentially, external bodies should not mess with these namespaces...

**Comment by mattgarrish** [comment]
Works for me!
