### ISSUE TITLE
link element in the container file...

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#1393]
My reading of the text that the usage of a `<link>` in the container file (in [§5.1.5.2.1](https://w3c.github.io/epub-specs/epub33/core/#sec-container-metainf-container.xml)) is a legacy feature. Shouldn't we mark it as such explicitly?

**Comment by mattgarrish** [comment]
Not legacy, no. It was added in 3.0.1 to handle rendition mapping documents.

But given the state of support for multiple renditions...

**Comment by iherman** [comment]
Hm. I do not know what "rendition mapping" is, it is not defined in the current spec. It refers back to a document in the IDPF namespace (has it been transferred to W3C in the first place, ie, is it to be maintained?). This document does define multiple rendition, but not this mapping. What do I miss?

**Comment by mattgarrish** [comment]
> This document does define multiple rendition

Not fully, no. The multiple renditions specification was created to address the problem of determining why there are multiple renditions within the container. You can't use the media type, so the specification defined a number of properties you can use to express various characteristics of each rendition. Those attributes are allowed on the `rootfile` elements.

Another "feature" of multiple renditions was a mapping document syntax so that you wouldn't lose your place if you switched from one rendition to another (intentionally or, for example, due to a change in device orientation). To make these valid, the `link` elements had to be added to OCF. We did that part, but to date have not incorporated the rest of the multiple renditions spec due to a lack of implementation. That's why the spec is only mentioned in non-normative prose.

> has it been transferred to W3C in the first place, ie, is it to be maintained?

I guess in the same sense as indexes, dictionaries, distributable objects and all the other peripheral specs have been transferred to W3C. Maintained... well, I guess that depends on whether some uptake materializes.

**Comment by mattgarrish** [comment]
Since we're publishing multiple renditions as a note, can we close this?

**Comment by dauwhe** [comment]
I'm ok with this section as-is, and am fine with closing the issue.

**Comment by iherman** [comment]
Hm. Personally, I would have liked to see at least a (non-normative) link to the rendition note (to [§5.4.4](https://w3c.github.io/epub-specs/epub33/multi-rend/#rendition-mapping-container-id)). But it is certainly no big deal.

**Comment by mattgarrish** [comment]
> I would have liked to see at least a (non-normative) link to the rendition note

Now you're just changing the issue. ;)

Rewriting the current note that says the specification doesn't define any uses for the element is fine with me (something like "see MR for a possible use").

**Comment by iherman** [comment]
> Rewriting the current note that says the specification doesn't define any uses for the element is fine with me (something like "see MR for a possible use").

Yep, that is all I had in mind.
