### ISSUE TITLE
Reference to idpf accessibility forum

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1417]
The techniques document includes this sentence in the about section:

> The IDPF similarly has an [accessibility forum](http://idpf.org/forums/epub-accessibility) where EPUB-related issues can be raised.

Not sure what we replace this with.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2020-12-10-epub-a11y#section6) on 2020-12-10)

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

### 6. Reference to idpf accessibility forum 

_See github issue [#1417.](https://github.com/w3c/epub-specs/issues/1417.)._




**Avneesh Singh:** in the IDPF version of a11y technique, there is a reference to a forum that no longer exists.  
… for people who have to discuss techniques, where do they post?.  
… idea is for people to post directly to the issue tracker.  
… there are other options, but github is easy for anyone to find and post on.  

> **Proposed resolution: Refer to epub-specs GitHub issue tracker..** *(Avneesh Singh)*

> *Charles LaPierre:* +1.

> *Matthew Chan:* +1.

> *Bill Kasdorf:* +1.

> *Ben Schroeter:* +1.

> *Jun’Ichi Yoshii:* / +1.

> *Laura Brady:* +1.

> *Juliette McShane:* +1.

</details>

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2020-12-10-epub-a11y#section6) on 2020-12-10)

List of resolutions:

- ***[Resolution No. 4](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2020-12-10-epub-a11y#resolution4):  Refer to epub-specs GitHub issue tracker..***

<details><summary><i>View the transcript</i></summary>

### 6. Reference to idpf accessibility forum 

_See github issue [#1417](https://github.com/w3c/epub-specs/issues/1417)._




**Avneesh Singh:** in the IDPF version of a11y technique, there is a reference to a forum that no longer exists.  
… for people who have to discuss techniques, where do they post?.  
… idea is for people to post directly to the issue tracker.  
… there are other options, but github is easy for anyone to find and post on.  

> **Proposed resolution: Refer to epub-specs GitHub issue tracker..** *(Avneesh Singh)*

> *Charles LaPierre:* +1.

> *Matthew Chan:* +1.

> *Bill Kasdorf:* +1.

> *Ben Schroeter:* +1.

> *Jun’Ichi Yoshii:* / +1.

> *Laura Brady:* +1.

> *Juliette McShane:* +1.

> ***Resolution #4: Refer to epub-specs GitHub issue tracker..***

</details>

**Comment by mattgarrish** [comment]
Should we point people to the publ-a11y repository for general questions? This repository isn't really geared to being a general help forum.

We can always migrate issues that require fixing in the specifications to this repository.

**Comment by iherman** [comment]
Ping @avneeshsingh

**Comment by avneeshsingh** [comment]
In publishing at W3C we do not have one place for all accessibility related discussions due to distribution of work in different groups. I see two kind of feedback.
- One is specific to clarifications and bug fixes in techniques document. We should add a line about it in the techniques document and point to epub-specs issue tracker, so that we have seamless connection to pull requests etc.
- Other is discussion for general accessibility, the dedicated accessibility issue tracker in publishing repo is a good place for it.

**Comment by mattgarrish** [comment]
In this case, the IDPF reference is given beside the WAI Interest Group as places to ask for general help. Those sorts of questions are better supported in the dedicated repository, but we can always mention both repositories and explain where to ask what.
