### ISSUE TITLE
Release identifier construction informative?

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1440]
I noticed that the paragraphs about constructing the release identifier are still in the core spec, but concatenating the two values is not an authoring concern.

These paras need to migrate to the reading system specification, but should we make an (informative) appendix out of them? Even if a reading system creates and uses release identifiers (and I'm not sure they do), there's no requirement to. It's sort of a helpful idea on how to distinguish publications more than an actual requirement of the specification.

**Comment by dauwhe** [comment]
Agreed. See also #593 and #1310. 

Testing this stuff is gonna be fun :)

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2020-12-18-epub#section2) on 2020-12-18

List of resolutions:

- ***[Resolution No. 1](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2020-12-18-epub#resolution1):  remove language around the concept of a release identifier, while retaining the mandatory unique ID and dcterms:modified metadata.***

<details><summary><i>View the transcript</i></summary>

### 2. release identifier construction 

_See github issue [#1440](https://github.com/w3c/epub-specs/issues/1440)._




**Dave Cramer:** Need to do some boring stuff called work.  
… The release identifier comes up from time to time (id + release time).  
… So you can figure out new vs update.  
… This is really just advice to RSes on how to distinguish books.  
… So really hard to test. How do you determine if there was an error?.  
… Should this be in the appendix non-normatively?.  

**Ivan Herman:** Is it used ever by anyone?.  

**Dave Cramer:** That is my favorite question.  

**Hadrien Gardeur:** Partial reply: There are roughly 2 groups of RSes.  
… one where content always comes from a controlled warehouse (eg big retailers).  
… second is more generic that can support any type of epub.  

_See github issue [#1310](https://github.com/w3c/epub-specs/issues/1310)._




**Hadrien Gardeur:** this id makes more sense for the second group.  
… We are talking about unique id, but also saying maybe it isn't unique, so maybe don't rely on it. Very confusing for RS.  
… we are building a spec that should work for all types of RSes.  
… Personally know that some RSes in the second group do use that id.  
… Recs about looking at title is often wrong (eg if the change was to fix the title).  

**Garth Conboy:** We are mostly a retailer, but also allow side loading. We ignore both the UID and the mod date-time..  

**Ivan Herman:** Need to be careful, there are two notions the UID and the release ID.  
… This creates an identifier based on some info in the epub.  
… this issue is whether that algo makes sense.  

**Hadrien Gardeur:** If this is specifically about release id, then I don't know who is using it.  
… UID is different answer.  

**Dave Cramer:** Not discussing removal of id or release date.  
… This is about uniqueness of UID, what happens when two books have the same UID, etc.  
… We probably don't want to start dictating how RSes present their libraries.  
… I would say we remove this concept since it can't really be tested.  

> *Garth Conboy:* +1.

> *Tzviya Siegman:* +1 to dauwhe.

**Ken Jones:** Maybe have a revision number?.  
… to make it clear there is id and version explicitly.  

**Hadrien Gardeur:** But that is the issue at stake.  
… epub 2 only had uid.  
… this was added in epub 3, but isn't really used.  
… first group doesn't really care, and second group doesn't handle versioning at all.  
… don't think we should be in the business of specifying how these are used.  
… Would like to not say anything about UID, just say what it is and leave it to the RS implementors to figure it out.  

**Zheng Xu (徐征):** Will be very difficult to test something that is undefined.  

**Tzviya Siegman:** Want to caution about versions and revisions.  
… Not changing too much in the spec is good guidance.  
… There has been a lot of discussion about rev vs version, don't want to take it up here.  

**Gregorio Pellegrino:** Publishers don't seem to use this, we use ISBN and file hashes.  

**Garth Conboy:** We seem to agree that release ID is not really used, and even if it is doesn't need to be in the spec.  
… So we seem to agree on this issue.  

**Dave Cramer:** Makes sense. We won't comment on metadata construction in the specs.  
… proposal would be to remove that language without touching required metadata.  

**Ivan Herman:** Need to be careful about how this is phrased.  
… are we proposing removal or moving to non-normative section/document.  
… Also DC terms has a `hasVersion` term, so we have that too.  
… May want to mention it, but no reason why it couldn't just be used.  
… But I propose that dauwhe propose something.  

**Dave Cramer:** [typing noises].  

> **Proposed resolution: remove language around the concept of a release identifier, while retaining the mandatory unique ID and dcterms:modified metadata.** *(Dave Cramer)*

**Dave Cramer:** I don't there is a compat issue here.  
… don't think there is any testable change here.  
… This is basically editorial.  

**Ivan Herman:** We can say any valid 3.2 will be valid with 3.3, this change does not alter that.  
… Doesn't change behavior or authoring.  

> *Wendy Reid:* +1.

> *Ivan Herman:* +1.

> *Bill Kasdorf:* +1.

> *George Kerscher:* +1.

> *Brady Duga:* +1.

> *Charles LaPierre:* +1.

> *Hadrien Gardeur:* +1.

> *Garth Conboy:* +π.

> *Laura Brady:* +1.

> *Ken Jones:* +1.

> *Tzviya Siegman:* +1.

> *Gregorio Pellegrino:* +1.

> *Zheng Xu (徐征):* +1.

**Dave Cramer:** Resolved!.  

> ***Resolution #1: remove language around the concept of a release identifier, while retaining the mandatory unique ID and dcterms:modified metadata.***

</details>
