### ISSUE TITLE
Rechecking accessibility

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1470]
The accessibility specification is currently silent about when publications need to be retested.

Although each release of a publication is typically a point-in-time event, we should consider some level of recommendation for re-releasing content (whether it has previously been checked and not).

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-03-25-epub-a11y#section2) on 2021-03-25

List of resolutions:

- ***[Resolution No. 2](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-03-25-epub-a11y#resolution2):  add non-normative text in ePUB Accessibility suggesting rechecking the publications for major changes that could effect***

<details><summary><i>View the transcript</i></summary>

### 2. Rechecking accessibility 

_See github issue [#1470](https://github.com/w3c/epub-specs/issues/1470)._




**Matt Garrish:** this came up in ISO. How long does the certification of content being accessible last for? e.g. For website the certification might degrade over 5 years, after which the accessibility certification might not be trustworthy anymore  
… less of a concern for packaged up epubs that shouldn't change  
… but what about reissues of epubs?  
… should we have guidance for that? A specific recommendation? Leave it to authors?  

**Avneesh Singh:** it will depend on publisher processes  

**Gregorio Pellegrino:** we check all the books published by our members  
… we hash each epub  
… so when we get a new file that matches an existing isbn, we match the hashes  
… if hash mismatch, we recheck a11y  

**Charles LaPierre:** for GCA, once we certify a publisher, they can stamp all books coming off that workflow as certified  
… but the publisher must get recertified each year  
… and that recertification process will bring them up to the state of the art  
… if they then reissue epub after that point, then they can update the certification as well  
… i.e. our solution is to keep the publisher up to date  

**Avneesh Singh:** if the user gets an old ebook, say 3 years old, how can the user ensure that the latest revision is accessible?  

**Charles LaPierre:** the user would just refer to the a11y metadata in the reprint. And it would be up to the publisher to use the latest standards in the publishing pipeline  
… between recertifications, we leave this up to the publisher  

**Ben Schroeter:** if its a new edition, i would consider that a new publication  
… that would go through whatever processes the publisher uses for normal a11y check  
… in terms of GCA certified publishers  
… i can see a case where a title goes through the certified workflow, but on republication changes are made (e.g. inserted image) that doesn't conform with a11y standards  
… this is a potential gap  
… and also, we may be moving towards a world in which there are more and more frequent updates to epubs  

**Wendy Reid:** any guidelines we put in place will have to apply across the board - from GCA certified to micro indie publisher  
… for a lot of repubs, the content of the book is not really changing (maybe just update to copyright page or something)  
… so we have to be careful of mandating recheck on "new hash" or every new revision  
… maybe qualify by saying "if adding new content" or "if substantially changing content"  

> *Charles LaPierre:* +1 Wendy

**Wendy Reid:** but have exclusion for if you are just fixing typos or updating marketing material  
… also, re. comparison between epub and website, epubs don't replicate at the same rate  

**Matt Garrish:** i think it has to be an informative section  
… what wendyreid has described is similar to the qualifications that we once had on release identifier  
… this is probably as far as we can go  
… don't want to get mired in questions of what it means to recheck  
… maybe just say that standards change, and that when you do something to your epub you should just make sure that you are on top of the latest standards  

**Gregorio Pellegrino:** one of our ideas was to add date of certification  
… e.g. in accessibility summary  

**Charles LaPierre:** the idea of a certification date is something we could definitely add  
… that way publishers could change the certification date, or not, when they make other changes to the epub  
… i'm wondering about if the publisher modifies something 3 years from now, and URLs for conformsTo have changed  
… do they change the URLs to new URLs, or leave them as what they were at the point of initial certification?  

**Matt Garrish:** hard question to answer, because we're not negating the old standards  
… maybe the date based system is a good way to go  
… hard to make normative statements because of all the possibilities  
… maybe we could rely on legislation to set the rules, and just offer some guidance  

**Avneesh Singh:** we can start by providing non-normative text like mgarrish suggested  
… let this mature for some number of years, and then revisit it  

**George Kerscher:** when a publisher is doing update or new edition, if they have switched to a11y 1.1, wouldn't they just start using the correct metadata URLs at that point?  
… publishers are not all going to go from a11y 1.0 to 1.1 all at once  

> **Proposed resolution: add non-normative text in ePUB Accessibility suggesting rechecking the publications for major changes that could effect accessibility** *(Avneesh Singh)*

> *Wendy Reid:* +1

> *Charles LaPierre:* +1

> *Gregorio Pellegrino:* +1

> *Matthew Chan:* +1

> *Bill Kasdorf:* +1

> *Will:* +

> *Matt Garrish:* +1

> *Ben Schroeter:* +1

> *Will:* +1

> ***Resolution #2: add non-normative text in ePUB Accessibility suggesting rechecking the publications for major changes that could effect***

**Avneesh Singh:** we'll work on the specific guidance language over on the issue tracker  

> *George Kerscher:* +1

</details>
