### ISSUE TITLE
Must reading systems support manifest fallbacks? 

### ISSUE THREAD

**Issue by dauwhe** [w3c/epub-specs#1474]
Do these two statements conflict? 

[A] https://w3c.github.io/epub-specs/epub33/rs/#confreq-rs-foreign

>  It MAY support an arbitrary set of Foreign Resource types, and MUST process fallbacks for unsupported Foreign Resources as defined in Foreign Resources [EPUB-33] if not.

[B] https://w3c.github.io/epub-specs/epub33/rs/#manifest

> Reading System MAY choose to utilize fallbacks to find the optimal version of a Content Document to render in a given context.

**Comment by dauwhe** [comment]
Ah, a bit clearer because of the paragraph immediately before [B]: 

[C] https://w3c.github.io/epub-specs/epub33/rs/#manifest

> A Reading System that does not support the Media Type of a given Publication Resource MUST traverse the fallback chain until it has identified at least one supported Publication Resource to use in place of the unsupported resource. If the Reading System supports multiple Publication Resources in the fallback chain, it MAY select the resource to use based on specific properties [EPUB-33] of that resource, otherwise it SHOULD honor the Author's preferred fallback order. If a Reading System does not support any resource in the fallback chain, it MUST alert the reader that content could not be displayed.

So what is [B] for? Is this just restating that, for example, if the RS supports every media type in the fallback chain it doesn't have to choose the original?

**Comment by mattgarrish** [comment]
D'oh, that looks like a bad splitting of a sentence on my part. Looks like I forgot to come back and fix it after pulling it out. The original sentence read:

> Fallbacks MAY also be provided for Top-Level Content Documents that are EPUB Content Documents; a Reading System MAY choose to utilize such fallbacks in order to find the optimal version of a Content Document to render in a given context.

The RS can decide which of the possible xhtml/svg options provided to use; it doesn't have to use the first. This is also where the manifest item properties come in, as it could determine which is optimal based on the properties (e.g., if one has mathml specified, it might choose that one if it supports mathml, or avoid it if not).

It should be more like: "When manifest fallbacks are provided for Top-level Content Documents, Reading Systems MAY choose from the available options in order to find the optimal version to render in a given context (e.g., by inspecting the `properties` attribute for each)."

I don't know that we really need to say that this is possible, but I guess there's no harm in it, either.

**Comment by mattgarrish** [comment]
This should have been closed with #1477.
