### ISSUE TITLE
Untestable assertion for default value of page-progression-direction

### ISSUE THREAD

**Issue by dauwhe** [w3c/epub-specs#1482]
https://w3c.github.io/epub-specs/epub33/rs/#spine

> When the default value of the page-progression-direction attribute is specified, the Reading System can choose the rendering direction. **The default value MUST be assumed when the attribute is not specified.** In this case, the reading system SHOULD choose a default page-progression-direction value based on the first language element.

"The default value MUST be assumed when the attribute is not specified" is a normative statement that is impossible to test, and I believe it provides no guidance to reading systems. How about:

> When the default value of the page-progression-direction attribute is specified, or the attribute is absent, the Reading System can choose the rendering direction. In these cases, the reading system SHOULD choose a default page-progression-direction value based on the first language element.

Is SHOULD strong enough here? I have a test with no PPD attribute and `dc:language="ar"`. Are we saying that both LTR and RTL are acceptable choices for the reading system in this situation?

**Comment by iherman** [comment]
+1 to use the SHOULD rather than MUST for the reason you stated.

> Is SHOULD strong enough here? I have a test with no PPD attribute and dc:language="ar". Are we saying that both LTR and RTL are acceptable choices for the reading system in this situation?

Actually, probably yes. I am not saying it is good, but a simple reading system may decide to operate on a very specialized market (say, Chinese) and not being prepared to do radically different things, like putting up the table of content on the opposite side of the device. This may be a rational decision.

Note that I expect the whole text directionality problem coming back to bite us as part of the i18n review discussion. We may want to delay any conclusion on this issue until we look at the larger picture.

**Comment by dauwhe** [comment]
> Actually, probably yes. I am not saying it is good, but a simple reading system may decide to operate on a very specialized market (say, Chinese) and not being prepared to do radically different things, like putting up the table of content on the opposite side of the device. This may be a rational decision.

Do we need to use SHOULD to give specialized reading systems permission to create suboptimal reading experiences? There is literally no consequences for a reading system failing a particular test. But are we saying it's OK for a reading system to present Arabic LTR, just because the document author forgot to use the page-progression-direction attribute?

**Comment by mattgarrish** [comment]
> Is SHOULD strong enough here?

But what if the language of the first element is invalid, or the reading system doesn't know it, or a direction can't always be inferred from the language alone?

> There is literally no consequences for a reading system failing a particular test.

When the default value is set, that's what the author is saying. Do whatever you want.

I don't believe there's a good answer to what to do when an explicit PPD isn't set. All you can do is let the reading system decide. Maybe the author forgot, or maybe they just don't care.

Ivan's case doesn't sound valid to me, as you can't ignore an explicitly-set PPD. That's required further up in this blanket requirement for package document:

> It MUST honor all presentation logic expressed through the Package Document [EPUB-33] (e.g., the reading order, fallback chains, page progression direction and fixed layouts).

This is only about when the author doesn't care or has omitted the attribute.

**Comment by mattgarrish** [comment]
> It MUST honor all presentation logic expressed through the Package Document [EPUB-33] (e.g., the reading order, fallback chains, page progression direction and fixed layouts).

This statement needs work, though. Presentation logic, I believe, is only supposed to encompass elements/attributes of the package document, not any metadata that can be expressed via `meta` tags. Fixed layouts doesn't belong in the examples, in other words, as it's not directly part of the logic of the package document. It's also why we have separate bullets for supporting fixed layouts.

**Comment by OriKuttner** [comment]
In the case of EPUB3 table of contents, it has a dir=rtl in case of right
to left language so a RS can understand from this file alone that it is
right to left, it does not need the language.

-- 
Ori Idan CEO Helicon Books
http://www.heliconbooks.com

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-07-08-epub#section5) on 2021-07-08

List of resolutions:

- ***[Resolution No. 4](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-07-08-epub#resolution4):  Change text for page-progression-direction to "When the default value of the page-progression-direction attribute is specified, or the attribute is absent, the Reading System can choose the rendering direction.", drop assertion, close issue 1482***

<details><summary><i>View the transcript</i></summary>

### 5. Page progression direction 

_See github issue [#1482](https://github.com/w3c/epub-specs/issues/1482)._




**Dave Cramer:** spec requires that when page progression direction (PPD) is not explicit, RS MUST assume value of "default"  
… not sure how to test this requirement  
… also, what happens when having just the language element is not enough for RS to set the PPD?  
… I proposed some alternate language in the issue, but there didn't seem to be consensus  

**Murata Makoto:** are you trying to relax requirements? Saying that MUST is too strong?  

**Dave Cramer:** it's more that requiring the RS to assume "default" is essentially saying that RS can do whatever it wants  

**Murata Makoto:** ah, so if we are going to impose normative restriction, then it should result in something observable  

**Dave Cramer:** e.g. what should happen if PPD is unstated, but language is Arabic? What are we requiring RS do in that case?  
… not always possible to determine what "correct" PPD is based solely on language  

**Murata Makoto:** so can we drop the entire second sentence in the proposed language?  Not specifying the ppd is already inviting a trouble.

**Dave Cramer:** right, in case the RS has some better way of choosing PPD (other than looking at the first language element)  

**Shinya Takami (高見真也):** SHOULD is a little strong because JP content uses both RtL and LtR PPD  

**Dave Cramer:** so we're thinking of deleting that sentence entirely, so that there is no longer a should at all  

> **Proposed resolution: Change text for page-progression-direction to "When the default value of the page-progression-direction attribute is specified, or the attribute is absent, the Reading System can choose the rendering direction.", drop assertion, close issue 1482** *(Wendy Reid)*

> *Dave Cramer:* +1

> *Murata Makoto:* +1

> *Shinya Takami (高見真也):* +1

> *Ben Schroeter:* +1

> *Matthew Chan:* +1

> *Toshiaki Koike:* +1

> *Matt Garrish:* +1

> *Brady Duga:* +1

> *Masakazu Kitahara:* +1

> *Wendy Reid:* +1

> ***Resolution #4: Change text for page-progression-direction to "When the default value of the page-progression-direction attribute is specified, or the attribute is absent, the Reading System can choose the rendering direction.", drop assertion, close issue 1482***

</details>

**Comment by llemeurfr** [comment]
Seems to me that this decision ends up lowering the interoperability of reading systems. The lack of PPD is a common issue in EPUBs. 

Readium-based systems rely on a [behaviour fully documented here](https://readium.org/readium-css/docs/CSS16-internationalization.html) (wouldn't it be great if all reading systems were documenting there behaviour?). The heuristic is using the first language element as an important clue. But there is a flaw there, as most authoring tools don't care about ordering languages ([ref](https://indesign.uservoice.com/forums/601021-adobe-indesign-feature-requests/suggestions/32796718-epub-css-output-could-be-improved-quite-a-lot)). 

If interoperability is taken seriously, the spec must become stricter in this field. But I agree that this `default` PPD value makes tests difficult and that relying on the first language property is a hack (metadata should not be ordered). There would be no more issue if PPD had no default value and every XHTML document had `lang` and `dir` properly set, but ...  

Being stricter in the EPUB authoring spec is not easy if we want to keep backward compatibility. The best solution is therefore to become clearer on authoring guidelines and reading system processing rules.

**Comment by murata2makoto** [comment]
> Seems to me that this decision ends up lowering the interoperability of reading systems. 

I don't think so.  It is always a good idea to specify the PPD.   By providing detailed descriptions of behaviors for its omission, you are implicitly encouraging the omission.

> Readium-based systems rely on a behaviour fully documented here (wouldn't it be great if all reading systems were documenting there behaviour?). 

This is implementation-dependent.  Different RSes for different languages and scripts may well adopt different behaviors .

**Comment by llemeurfr** [comment]
> Different RSes for different languages and scripts may well adopt different behaviors.

Which means that RS interoperability is not good enough.

**Comment by iherman** [comment]
@llemeurfr the problem I see is that I am not sure what would we put into the spec. As you yourself say, even such a detailed behavioural description as Readium's (bravo to have that published, b.t.w.) is not without problems, ie, it would probably be inappropriate to put it into the spec. And I do not think it is realistic to expect other RS-s to publish their own heuristics within a foreseeable amount of time.

Ideally, the EPUB spec should say that authors _SHOULD_ (maybe even _MUST_) put the PPD value into the package document. But that would mean that epubcheck would probably flag a huge number of existing and deployed EPUB content, and that is a big no-no per our charter.

At this point, pragmatically (and I'm holding my nose) I do not see any other feasible approach than what was accepted on the call... 

(We may, or rather the CG may, set up a place where such documents as yours could be collected. If there are such documents around it may be possible, in the future, to distill some common behaviour that could be documented later.)

**Comment by OriKuttner** [comment]
I don't really see the problem.
If PPD is defined RS will use it. If it is not RS should use the main
language, most languages are LTR.
I think the default for EPUB2 was LTR, only in 3.0 we added the
page-progression-direction property.
