### ISSUE TITLE
Re-add normative distribution requirements

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1487]
As discussed on the [2021-01-28 telecon](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-01-28-epub-a11y), the EU directives have similar requirements to the 1.0 specification's distribution section -- for metadata and that rights restrictions must not restrict access. We'll need to restore these requirements to better match the legislation.

**Comment by murata2makoto** [comment]
I oppose this change.  The abstract of A11Y clearly shows that its scope is contents and accessibility metadata.

I understand your desire.  But just like world peace is not in the scope of technical specifications, distribution is outside the scope.

If normative descriptions about distribution are indeed needed, we should create another specification for distribution.  We might want to use the white paper from LIA as a basis.

**Comment by avneeshsingh** [comment]
The objective of this section is not to specify distribution requirements, but to highlight that distribution mechanisms should not block accessibility.
It is a requirement in European Accessibility directive. ANNEX I, Section IV Ebooks:
https://eur-lex.europa.eu/eli/dir/2019/882/oj?eliuri=eli:dir:2019:882:oj

LIA has a good white paper, and this change was done in sync with LIA, and based on analysis of EU accessibility act and EPUB accessibility done by Luc, Gregorio and Cristina.

**Comment by murata2makoto** [comment]
@avneeshsingh Then, why "Make distribution section normative"?  This section surely specifies distribution requirements.  "highlight that distribution mechanisms should not block accessibility" is a normative requirement.

**Comment by avneeshsingh** [comment]
@murata2makoto Are you concerned about normative section? Is it ok if this section is non-normative?
@gregoriopellegrino what are your thoughts?

**Comment by mattgarrish** [comment]
What if we move this section to an appendix and clarify that conforming to the requirements is not strictly part of the specification but may be required by relevant legislation, highlighting the EU directive in particular?

Watering the language down to informative suggestions doesn't seem helpful given the reality of the EU directive.

**Comment by gregoriopellegrino** [comment]
I talked about this with Cristina, our proposal could be to make the section non-mandatory and adding a note similar to https://w3c.github.io/epub-specs/epub33/a11y/index.html#issue-container-generatedID-2

In the note we can write that for some legislations, like the EAA, DRM systems used for EPUB distribution must not block accessibility features.

**Comment by avneeshsingh** [comment]
We also plan to get feedback for the public working draft from EU perspective. So, I think that we should keep this issue open for some time for further discussions, and make a well informed decision after going through different aspects.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-03-11-epub-a11y#section1) on 2021-03-11

List of resolutions:

- ***[Resolution No. 1](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-03-11-epub-a11y#resolution1):  make distribution section non-normative and place a note that it is required by EU accessibility act***

<details><summary><i>View the transcript</i></summary>

### 1. distribution 

_See github issue [#1487](https://github.com/w3c/epub-specs/issues/1487)._




> *Avneesh Singh:* [https://w3c.github.io/epub-specs/epub33/a11y/index.html#sec-distribution](https://w3c.github.io/epub-specs/epub33/a11y/index.html#sec-distribution)

**Avneesh Singh:** there are some questions on the distribution section  
… this section was added to be in line with the European Accessibility Act highlighting that it is not a normative section  

**Gregorio Pellegrino:** we can do as in WCAG as a note where is highlighted that is not normative and it may be only for some legislation in some countries  

**Matt Garrish:** worry as DRM is always an problematic issue in specs  
… this is one reason to avoid including it  

**Bill Kasdorf:** the ways it actually stated that authors must not impose restrictions while restrictions are implemented by distributors  

**Matt Garrish:** there are features of DRM that authors or publishers can add and it is important do highlight this issue  

**Tzviya Siegman:** as it it a requirement of EEA Gregorio may you clarify what is required by the EEA  

> **Proposed resolution: make distribution section non-normative and place a note that it is required by EU accessibility act** *(Avneesh Singh)*

> *Charles LaPierre:* +1

> *Gregorio Pellegrino:* +1

> *Tzviya Siegman:* +1

> *Laurent Le Meur:* +1

> *Ben Schroeter:* 0

> *Matt Garrish:* +1

> *Bill Kasdorf:* 0

> ***Resolution #1: make distribution section non-normative and place a note that it is required by EU accessibility act***

</details>
