### ISSUE TITLE
Page list ordering

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1500]
The page list definition currently includes the old requirements of the table of contents -- that the list has to be ordered to reflect the occurrence of page breaks by spine entry and within each content document.

Is this actually what we want, or should the page list be allowed to (recommended to) reflect the original numbering of the source document?

**Comment by gregoriopellegrino** [comment]
I think it should stay, otherwise it becomes very difficult for RS to put the pages in the correct order in the UI, as discussed in #1471

**Comment by mattgarrish** [comment]
> it becomes very difficult for RS to put the pages in the correct order in the UI

But this is essentially the question. Does the user want to access the page numbers all out of sequence because that's the way the digital content is ordered, or do they want to access a sequential list that matches the print?

If they're trying to follow the print edition, in other words, wouldn't they want to follow the print sequence and not the digital?

My understanding from @danielweck's response is that thorium at least doesn't re-order the list; it just uses whatever is provided for manual access. In the case of going to a specific page, it doesn't sound like it matters.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-03-11-epub-a11y#section4) on 2021-03-11

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

### 4. pages related issues 

_See github issue [#1503](https://github.com/w3c/epub-specs/issues/1503), [#1502](https://github.com/w3c/epub-specs/issues/1502), [#1501](https://github.com/w3c/epub-specs/issues/1501), [#1500](https://github.com/w3c/epub-specs/issues/1500), [#1542](https://github.com/w3c/epub-specs/issues/1542)._



**Matt Garrish:**: Updated EPUB accessibility for addressing a part of the following static pages issues. Some requirements can be addressed by EPUB Accessibility while others should go to best practices.

> *Avneesh Singh:* [https://w3c.github.io/epub-specs/epub33/a11y/index.html#sec-page-nav](https://w3c.github.io/epub-specs/epub33/a11y/index.html#sec-page-nav)

**Matt Garrish:** we had different questions about pagelists  
… one propose is to structure the requirements for pagelists  
… e.g. level A: some pages in the pagelist  
… level AA: all content pages linked in pagelist  
… level AAA: all pages (no exclusion, even blank pages)  
… I didn't move over with my requirements  

**Avneesh Singh:** I don't think these issues can be added in the guidelines, maybe the best place is best practices  

**Tzviya Siegman:** we had similar in PDFs with "this page intentionally left blank", where we left blank pages for starting the chapters on page right  
… I think that marking blank pages can be really confusing  
… maybe we can use ARIA  

**Avneesh Singh:** yes, but then someone will say that ARIA is not only for AT  

**Charles LaPierre:** I'm not sure if Read Aloud by the Reading system can get that information  

**Matt Garrish:** for sure we can investigate the use of ARIA label or something similar  

**Avneesh Singh:** I think this task force should focus on the requirements Matt put in the issues  
… we can go through the issue tracker  
… and discuss there  

**Matt Garrish:** we have a issue about the ordering of the pagelist  
… if I have the pages moved in the digital version, what happen to the pagelist?  

**Tzviya Siegman:** I have several examples of this  

**Avneesh Singh:** I think for AT users it would be useful to have an alert  

**Charles LaPierre:** maybe we can put in in the accessibility summary (metadata), but do we need to have some requirements for reading systems?  

**Gregorio Pellegrino:** maybe something like play order attribute in NCX tocs  

---


</details>

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-03-25-epub-a11y#section1) on 2021-03-25

List of resolutions:

- ***[Resolution No. 1](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-03-25-epub-a11y#resolution1):  relax strict requirement of sequential page numbers in EPUB 3 specification***

<details><summary><i>View the transcript</i></summary>

### 1. Page list ordering 

_See github issue [#1500](https://github.com/w3c/epub-specs/issues/1500)._




**Matt Garrish:** right now the pagelist is required to follow spine+content order  
… pagelist will therefore match digital sequencing  
… but should we lift the requirement, therefore allowing the pagelist to follow print sequencing  
… right now there is no choice in it  
… we did require this for toc, and we reduced that requirement  
… i don't have a strong position on this  
… it really comes down to which one users expect, and what makes sense  

**Avneesh Singh:** thoughts?  

**Wendy Reid:** i have no seen RS that uses pagelist to dictate page number order in epub  
… kobo doesn't do it  
… pagelist is more likely treated as just an additional nav aid, like toc  

**Gregorio Pellegrino:** as far as i've tested i think that apple books uses it for UI toc, where they put "real" page numbers for different toc entries  
… from my point of view, which are the use cases for end users for the pagelist?  
… what are the requirements for RS?  
… what are the requirements for content producers?  

**Avneesh Singh:** one use case i would like to mention is if there is a classroom, and there are students using print, and a blind student using ebook  
… if teacher says "move to page X", then it make sense for pagelist to match print  

**Bill Kasdorf:** what is the relationship of the pagebreak markers to the pagelist?  
… i thought they always had to correspond?  

**Matt Garrish:** They have to correspond. So, they need to be included in the pagelist, but why should they match the order of the epub content?  

> *Bill Kasdorf:* +1 to Matt

**Matt Garrish:** e.g. if an epub has reordered pages, and you're looking for a particular print correspondence page, then how do you find it (without using a UI where you can type in a page number)  

**Gregorio Pellegrino:** another use case could be for quotations, and for finding quotations in books  
… usually quotations are based on print page numbers  
… also, from UI point of view, few RS are using something like an input tool to navigate to page  
… because there can be a mix of page number styles (e.g. a, i, I, arabic numbers)  
… hard for a single tool to find any given page  

**Wendy Reid:** any time i've seen implementation of pagelist it has been in toc style (e.g. a list of links)  
… in this case it makes more sense to follow the correspondence order (e.g. print)  
… and always be in linear sequence, of course  

**Avneesh Singh:** so it seems like we are all in favour of relaxing the requirement of pagelist following content order  

**Matt Garrish:** i think we can have some sort of a recommendation, at least, that pagelist follow the print  

**Bill Kasdorf:** i've always thought of pagelist as a correspondence tool to an authoritative print equivalent  
… but for publications without print equivalent, what is the purpose of pagelist?  

> *Gregorio Pellegrino:* CFI?

**Wendy Reid:** this is virtual page numbers. We're exploring this topic. The need for these has become more prevalent recently  

**Bill Kasdorf:** this is a key distinction. We should be careful with the distinction  
… only use page number for print equivalent. The other one should be called "locators"  

**Avneesh Singh:** we are using the same terms in wcag 2.2  

> **Proposed resolution: relax strict requirement of sequential page numbers in EPUB 3 specification** *(Avneesh Singh)*

> *Matthew Chan:* +1

> *Matt Garrish:* +1

> *Wendy Reid:* +1

> *Bill Kasdorf:* +1

> *Charles LaPierre:* 0

> *Will:* +1

> *Gregorio Pellegrino:* +1

> *Ben Schroeter:* +1

> ***Resolution #1: relax strict requirement of sequential page numbers in EPUB 3 specification***

**Avneesh Singh:** this may require main group approval later  

**Wendy Reid:** we're going to have to discuss this in the main group call, maybe on the agenda next week  

**Avneesh Singh:** mgarrish will make changes and do PR  

</details>

**Comment by mattgarrish** [comment]
Per the discussion yesterday, the accessibility task force is recommending the WG remove the requirement for the page list to match the ordering of page break elements in the content.

This requirement puts the list out of sequential order relative to the print making it potentially more difficult to locate pages when content is shuffled around for the digital edition.

It also doesn't account for page lists for which no page break markers are present.

**Comment by mattgarrish** [comment]
Closing as we relaxed these rules in #1588.
