### ISSUE TITLE
Reading system handling of gaps in page list

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1504]
As originally asked in #1471:

> what should RSs do if the page-list has jumps in numbering? Interpolate?

**Comment by mattgarrish** [comment]
I don't think we should try and have reading systems fill in gaps. I'm not even sure they can, as how, for example, would a reading system know if there are roman numeral pages missing if they're the last pages before arabic numbers start? I've seen some weirdly named backmatter pages in my time, too, so we can't expect the RS to make sense of these.

We might want to provide some guidance about alerting a user when pages do not exist, but this kind of depends on the interface. If the user has a list to select from instead of a place to plug in a number, the user will have to figure out that the pages aren't there.

(Again, removing the accessibility label as this is a core consideration.)

/cc @gregoriopellegrino

**Comment by wareid** [comment]
@gregoriopellegrino Can you provide some background on this for us? Not sure what the intended action is.

**Comment by gregoriopellegrino** [comment]
In many remediation cases (e.g. accessibility remediation or converting EPUB 2 to EPUB 3), you can't enter all the page numbers of each page, so one technique is to list the page numbers at the beginning of each chapter (very easy to get from a TOC of the printed book). This technique is valid because there are no requirements that the page list must contain all the pages of the book.

A page list could therefore be:
```
<nav epub:type="page-list" id="page-list" role="doc-pagelist">
	<ol>
		<li><a href="test-2.xhtml">3</a></li>
		<li><a href="test-4.xhtml">7</a></li>
		<li><a href="test-5.xhtml">11</a></li>
		<li><a href="test-6.xhtml">22</a></li>
		<li><a href="test-7.xhtml">28</a></li>
		<li><a href="test-8.xhtml">31</a></li>
		<li><a href="test-9.xhtml">39</a></li>
	</ol>
</nav>
```

My question is, what if a user wanted to go to page 15?
Can we give suggestions to reading apps on what to do?
Should we put restrictions on content producers (list all pages or none)?

**Comment by dauwhe** [comment]
> My question is, what if a user wanted to go to page 15?
> Can we give suggestions to reading apps on what to do?

If the Reading System provided an interface that allowed a user to enter a string, and that string was not found in the page list, reading systems would typically not navigate, and altert the user that the page number doesn't exist. That seems to be the most common behavior. This also matches what a program like Adobe Acrobat would do when a user asked for a page number that was not in the document. 

> Should we put restrictions on content producers (list all pages or none)

I don't think there's any way of knowing that a page list is complete. Aside from blank pages, an ebook may not include some sections that were in the print book. Content may be reordered. The content author is going to have a much better understanding of the idiosyncrasies of any particular book. 

I think this falls into the case of best practices--yes, if there is a print edition, it is a best practice to include every print page number in the pagelist.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-04-29-epub#section5) on 2021-04-29

List of resolutions:

- ***[Resolution No. 3](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-04-29-epub#resolution3):  Close issue 1504***

<details><summary><i>View the transcript</i></summary>

### 5. Handling gaps in pagelist 

_See github issue [#1504](https://github.com/w3c/epub-specs/issues/1504)._




**Dave Cramer:** question of whether RS should interpolate between explicit page numbers if it encountered gaps  
… e.g. where an epub without page numbers was remediated by adding page references to only the first page of each chapter  
… if the RS even allowed a user to "go to" page and user entered in a number in one of the gaps  
… i would expect RS to say "page does not exist"  
… interpolation does not seem a workable solution  

**Brady Duga:** yes, that's what Google does  
… if you enter something that doesn't match a pagelist value, we don't go anywhere  
… if you enter a match, then we take you to the destination of the pagelist  

**Ben Schroeter:** what about gregorio's question about guidance to authors to include pagelist link to all pages  

**Brady Duga:** there might be pages in the print that are not in epub, blank pages, out of order pages (i.e. frontmatter moved to back)  
… numerous reasons for lack of 1-to-1 correspondence  

> **Proposed resolution: Close issue 1504** *(Wendy Reid)*

> *Ben Schroeter:* +1

> *Shinya Takami (高見真也):* +1

> *Brady Duga:* +1

> *Dave Cramer:* +1

> *Wendy Reid:* +1

> *Matthew Chan:* +1

> *Toshiaki Koike:* +1

> ***Resolution #3: Close issue 1504***

**Dave Cramer:** some of this may be best practice for how to create pagelist, but that's outside scope of core spec  

> *Matthew Chan:* shiestyle addresses JP members in Japanese

**Shinya Takami (高見真也):** I just confirmed whether Voyager is using pagelist  
… i don't think many JP RS do  

</details>
