### ISSUE TITLE
Clarify what support for "presentation logic" means

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1516]
The reading system spec has this high-level requirement for the package document:

> [A Reading System] MUST honor all presentation logic expressed through the Package Document [EPUB-33] (e.g., the reading order, fallback chains, page progression direction and fixed layouts).

https://w3c.github.io/epub-specs/epub33/rs/#sec-package-rs-conformance

The inclusion of fixed layouts in the examples is confusing, though, as it there is a separate bullet for fixed layout handling in the same list.

I believe the intention of this bullet was only to require support for the "presentation logic" expressed directly through the elements and attributes of the package document, not indirectly through metadata expressed in meta tags.

On top of the general ambiguity about what "presentation logic" refers to, "honor" isn't exactly a technical term. The bullet seems more like an indirection to actual requirements/recommendations than something that can be tested.

In any case, it needs work.

**Comment by mattgarrish** [comment]
I think this "requirement" is just a regular old pointer wrapped up in some serious-sounding handwaving.

If there is "logic" that reading systems have to "honor", then it should be written as normative requirements not left for developers to vaguely give deference to.

Looking at the examples cited:

- the reading order - we already define requirements for processing in the [spine section](https://w3c.github.io/epub-specs/epub33/rs/#sec-pkg-doc-spine)
- fallback chains - we define fallback processing in the [foreign resources](https://w3c.github.io/epub-specs/epub33/rs/#sec-epub-rs-conf-foreign-res) and [manifest](https://w3c.github.io/epub-specs/epub33/rs/#sec-pkg-doc-manifest) sections
- page progression direction - also defined in the spine section
- fixed layouts - aren't inherent logic of the package markup but at any rate have a [dedicated section](https://w3c.github.io/epub-specs/epub33/rs/#sec-fixed-layouts) of requirements

So what else is there? General rendering metadata is like fixed layouts - not really applicable but already covered.

If we're missing requirements for any of the above, or there's something I didn't spot, we should be adding those in not hoping they'll be "honored".

**Comment by mattgarrish** [comment]
So, in case it needs saying, my proposal is to drop this statement/section.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-04-15-epub#section6) on 2021-04-15

List of resolutions:

- ***[Resolution No. 3](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-04-15-epub#resolution3):  Drop the statement in issue 1516***

<details><summary><i>View the transcript</i></summary>

### 6. What do we mean by support for "presentation logic"? 

_See github issue [#1516](https://github.com/w3c/epub-specs/issues/1516)._




**Dave Cramer:** we say RS must "honor presentation logic expressed through package document"  
… mgarrish thinks we should just delete it since we already require all the pieces of that in other places in the RS spec  
… making this statement redundant  

**Brady Duga:** agree  

**Marisa DeMeglio:** yes, agree  

> **Proposed resolution: Drop the statement in issue 1516** *(Wendy Reid)*

> *Dave Cramer:* +1

> *Wendy Reid:* +1

> *Matthew Chan:* +1

> *Marisa DeMeglio:* +1

> *Brady Duga:* +1

> *Toshiaki Koike:* +1

> *Masakazu Kitahara:* +1

> *Dan Lazin:* +1

> ***Resolution #3: Drop the statement in issue 1516***

</details>
