### ISSUE TITLE
Add a "translation" value to the `refines` mechanism

### ISSUE THREAD

**Issue by wareid** [w3c/epub-specs#1553]
See Ivan's comments in #1527: https://github.com/w3c/epub-specs/issues/1527#issuecomment-787858199

Should we add a refines="translation" value to the metadata in order to provide a clear mechanism for content authors to provide translations?

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-03-04-epub#section5) on 2021-03-04

List of resolutions:

- ***[Resolution No. 5](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-03-04-epub#resolution5):  Close issues 1527 and 1553, add editorial note regarding the current use of `dc:title` on the market and edit the example***

<details><summary><i>View the transcript</i></summary>

### 5. Handling of `dc:title` 

_See github issue [#1527](https://github.com/w3c/epub-specs/issues/1527), [#1553](https://github.com/w3c/epub-specs/issues/1553)._




**Wendy Reid:** these next two are related  
… there was some confusion about the example provided for `<dc:title>`  
… specifically when there are multiple, but they have different `xml:lang`-s  
… the discussion raised the question of whether refines needs a translation value  
… because the different titles might not be translations of one another  

**Dave Cramer:** is there any RS that does anything with the title beyond the bare minimum?  

**Wendy Reid:** probably no  

**Dave Cramer:** i've been writing tests and most RS seem to just display the first of each when there are fields that can occur multiple times  
… authors are asking for more expressive power, but no RS seems to be presenting this additional data to the user  

**Matt Garrish:** we tried what Laurent brought up in the issue  
… up to epub 3.1 you had to define your title type  
… and nobody used it, so we took it out  
… we'd be going back in circles. I think maybe we should just move on.  
… about the refines translation, we haven't found a case for it  
… people aren't making one epub with metadata in all these different various languages  

**Brady Duga:** agreed to all of that  
… unclear what an RS should even do when presented with the title in multiple different languages  

**Wendy Reid:** especially if the book itself is only in one language  
… one of the concerns we had was about JP, because Japanese has 3 different script sets, for lack of a better way of explaining it  
… so could an RS potentially implement a feature where the user could swap between script sets?  

**Dave Cramer:** ultimately the purpose of title is so you can distinguish books within your own collection  
… not meant to be as rigorous as a metadata record at some high level aggregator level (e.g. library of congress)  
… maybe change not needed  

**Brady Duga:** should we clarify the example then?  

**Matt Garrish:** we can't get rid of multipart `dc:titles` at this point  
… so do we guide people towards putting everything in a single title?  

**Dave Cramer:** I think our examples should reflect what will work for most people  
… so maybe we need to dial back the example  

**Matt Garrish:** or say that you can do multipart titles, but that there is no guarantee that RS can use them, or guarantee as to consistency  

**Brady Duga:** say "you can put multipart titles, but nobody knows what will happen, so you should probably only put one"  

> **Proposed resolution: Close issues 1527 and 1553, add editorial note regarding the current use of `dc:title` in the market** *(Wendy Reid)*

**Wendy Reid:** this should probably be an editorial note  

> **Proposed resolution: Close issues 1527 and 1553, add editorial note regarding the current use of `dc:title` on the market and edit the example** *(Wendy Reid)*

> *Brady Duga:* +1

> *Matthew Chan:* +1

> *Matt Garrish:* +!

> *Wendy Reid:* +1

> *Toshiaki Koike:* +1

> *Matt Garrish:* +1

> *Masakazu Kitahara:* +1

> ***Resolution #5: Close issues 1527 and 1553, add editorial note regarding the current use of `dc:title` on the market and edit the example***

</details>
