### ISSUE TITLE
[EPUB Accessibility Guidelines] Distribution section – second paragraph unclear to me

### ISSUE THREAD

**Issue by gregoriopellegrino** [w3c/epub-specs#1569]
I do not fully understand the meaning of the following sentence:

> Even when an Author controls their own distribution, the accessibility of their bookstore, library and/or Reading System can be outside their control.

**Comment by mattgarrish** [comment]
Ya, this is a case where the ISO rewrites didn't improve on the text. I think we ended up with this wording in order to do away with "Distribution Channel" as a term.

The whole paragraph is a bit confusing, though, and redundant in places (e.g., twice we say factors are outside the control of authors without really explaining what this means). The "factors" we were talking about are also gone. It made a lot more sense in 1.0.

Thanks for pointing this out as I'll try and give the whole para a better rewrite.
