### ISSUE TITLE
Allowing role on dc:publisher

### ISSUE THREAD

**Issue by acabal** [w3c/epub-specs#1583]
Tangentially related to #1129. With the release of epubcheck 4.2.5 the Standard Ebooks corpus is now throwing errors because we attach a `role` to `<dc:publisher>`, and that appears to be no longer allowed.

I would suggest including `<dc:publisher>` in the list of allowed elements that may have a `role` attached. Many MARC roles apply to *organizations*, not just individuals, and it is often useful to include such metadata: for example, which organization is the Metadata Contact (mdc)? That might often be the publisher!

For example, this is the standard boilerplate that has been included in all Standard Ebooks for years, which all of a sudden fails epubcheck:

```xml
<dc:publisher id="publisher">Standard Ebooks</dc:publisher>
<meta property="role" refines="#publisher" scheme="marc:relators">bkd</meta>
<meta property="role" refines="#publisher" scheme="marc:relators">mdc</meta>
<meta property="role" refines="#publisher" scheme="marc:relators">pbl</meta>
```

This indicates that Standard Ebooks is the Book Designer (bkd), Markup Contact (mdc), and Publisher (pbl). One could argue that pbl is redundant but I think the rest are valid roles to attach to an organization.

**Comment by rdeltour** [comment]
For reference, this spec requirement was added in EPUBCheck after it was reported in w3c/epubcheck#1121

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-03-26-epub#section3) on 2021-03-26

List of resolutions:

- ***[Resolution No. 3](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-03-26-epub#resolution3):  Relax the restriction on cardinality for OPF metadata***

<details><summary><i>View the transcript</i></summary>

### 3. Extending "role" cardinality in contributor metadata 

_See github issue [#1129](https://github.com/w3c/epub-specs/issues/1129), [#1583](https://github.com/w3c/epub-specs/issues/1583)._




**Dave Cramer:** this came up early in epub 3.2 in CG  
… can you have more than one metaproperty role pointing to meta element  
… schema said 0 or 1  
… CG felt it would be tricky for RS to do anything else, and there wasn't a lot of demand for change at the time  
… but recently people have been using role property to reflect fact that each contributor can do multiple things for publication  

**Matt Garrish:** part of the restriction is because we had the OPF role attribute role in epub  
… and we were trying to match things up  
… i'm not sure its critical anyway  
… not harmful to have multiple roles  
… happy to let people do what they want with metadata  
… for epub2 compat, maybe an informative note that you may want to limit yourself to 1 role  

**Dave Cramer:** more RS i'm aware of won't display this to end user at all  

**Bill Kasdorf:** allowing this might be good just for removing friction for publishers  
… really common  
… so maybe let's allow it if it does no harm  

**Hadrien Gardeur:** from Readium perspective, we could support it  
… we could parse it, make it easy to work with, and then its up to the RS to do with that what they want  
… and then about OPF, for some RSes its the only metadata they have  

**Dan Fauxsmith:** given that we are currently saying 0 to 1, but publishers are saying they have lots of ebooks where this is already >1, should we recommend that if there is more than 1 then it should be in priority order?  
… as an author, you don't know about RS behaviour. You just want to know what is the best value to populate  

> *Ivan Herman:* +1 to dlazin

**Gregorio Pellegrino:** my Q is about ONIX  
… in ONIX do you have to duplicate the contributor, or can the contributor have multiple roles?  

**Bill Kasdorf:** this is really common in higher ed publishing  
… highly likely that they'd need to be able to do this  

**Hadrien Gardeur:** disagree that we should try to align with ONIX  
… its not produced by the same people  
… one person does OPF, and often someone else does ONIX  
… repeating roles rather than repeating author is more elegant  

**Dave Cramer:** ONIX cardinality for contributor is that each can have multiple roles  
… i'm seeing strong support to relax this restriction, to allow cardinality of multiple  

**Ivan Herman:** agree, but i think we should also make it clear that they should be in priority order  

**Charles LaPierre:** i just created book for diagram center that had multiple contributors, and there i had to add in all these roles for each contributor. Would have loved to have been able to do this in the epub as well.  

**Brady Duga:** for priority, i could seen some RS taking the first one, and some taking the last one  

**Matt Garrish:** can we also agree to 1583?  

> **Proposed resolution: Relax the restriction on cardinality for OPF metadata** *(Wendy Reid)*

> *Ivan Herman:* +1

> *Charles LaPierre:* +1

> *Matthew Chan:* +1

> *Brady Duga:* +1

> *Bill Kasdorf:* +1

> *Gregorio Pellegrino:* +1

> *Ken Jones:* +1

> *Wendy Reid:* +1

> *Juliette McShane:* +1

> *Toshiaki Koike:* +1

> *Masakazu Kitahara:* +1

> ***Resolution #3: Relax the restriction on cardinality for OPF metadata***

**Wendy Reid:** so we'll leave to mgarrish to draft amending language  

</details>

**Comment by acabal** [comment]
Thanks @iherman, good to know it's being considered. Looking at the transcript it's not clear to me if this would also allow roles on `<dc:publisher>`, was that also under consideration?

**Comment by mattgarrish** [comment]
> it's not clear to me if this would also allow roles on `<dc:publisher>`, was that also under consideration

Yes, I asked that we resolve both right before we voted so they're both relaxed in https://github.com/w3c/epub-specs/pull/1591

I've also opened this in https://github.com/w3c/epubcheck/issues/1230 to get epubcheck updated.

**Comment by acabal** [comment]
Awesome, thanks!
