### ISSUE TITLE
[Question] Z39.98 relevance for EPUB

### ISSUE THREAD

**Issue by ThomasR128** [w3c/epub-specs#1589]
Since it was mentioned loooong ago in @mattgarrish’s _EPUB3 Best Practice_ book, I wonder if the Z39.98-2012 Structural Semantics Vocabulary (still) has / ever had any relevance for EPUB, be it in the US or elsewhere. Epubcheck certainly doesn’t complain. A quick Google search comes up with very few results, mostly a11y-related:

- [the Nordic EPUB3/DTBook Migrator](http://nlbdev.github.io/nordic-epub3-dtbook-migrator/)
- an old manual by the Swedish Agency for Accessible Media
- [a Springer book from 2012 on Braille document creation](https://link.springer.com/chapter/10.1007/978-3-642-31522-0_75)
- [a recent French book on EPUB3.2 creation](https://books.google.es/books?id=bl3yDwAAQBAJ&pg=PA279#v=onepage&q&f=false)
- the Standard Ebooks style guide

I’m mainly referring to AT since it is much more detailed than the EPUB SSV.

–Thanks

**Comment by mattgarrish** [comment]
Well, I guess if you're going to call me out for mentioning it... :smile:

No, `epub:type` in general never panned out as a means of AT understanding documents. That's why we worked on the DPUB-ARIA module for the `role` attribute. There are some reading system affordances that `epub:type` values make available (pop-up footnotes and finding the table of contents, for example) but those are a fraction even of the EPUB vocabulary.

The Z39.98 vocabulary predates EPUB's -- we basically whittled it down a bit to get the most useful terms for mainstream publishing in making the EPUB version. The vocabulary was designed to add additional context to the Z39.98 authoring and interchange format, which itself was designed as a kind of "master" format from which to produce various accessible formats (braille, dtbs, epubs, etc.).

If you want even more semantics for an internal workflow using epub, the vocabulary can also be helpful, too.

But while it might still have some value in those contexts, there's no specific benefit to the terms in an output epub.

Hope that helps.

**Comment by ThomasR128** [comment]
> Well, I guess if you're going to call me out for mentioning it... 😄

Only in the best way imaginable. That book has been a most helpful resource and certainly deserves an update for EPUB3.3.

Your answer confirms what I imagined since daisy.org has it under "Daisy Format" and not under "EPUB". 

Thanks again, Matt.
