### ISSUE TITLE
Page source when no source

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1599]
When we created the requirement to identify the source of page break markers for the accessibility spec, we weren't really considering virtual page numbers.

To workaround the problem of requiring a source, I know we've told people to use an identifier for the current publication, but this doesn't make sense from a metadata perspective. It's an abuse of the `dc:source` element. I'm not sure it makes any sense to users, either.

The solution to this seems fairly simple: `dc:source` is only required if the pages are from a static source.

Any reasons not to make this change?

**Comment by clapierre** [comment]
We still need some solution if there are page numbers added by the publisher for a digital only solution where there is no print version.  Having these page numbers embedded in the publication means that no matter the reading system used or the size of one's screen that when a teacher says go to page 23 everyone gets to the same page.  We need a way to identify there are embedded page breaks for discovery.

Previously we identified this by having accessibilityFeature="printPageNumbers" and then role=doc-pagebreaks along with the requirement of dc:source and we did discuss for EPUB only (ie no print version) this would self reference the EPUB and then additionally the the metadata of `<meta refines="#src-id" property="source-of">pagination</meta>`.

Do we now need to add a new accessibilityFeature value of "digitalPageNumbers" or "virtualPageNumbers" and then perhaps keep dc:source as self referencing the EPUB's ISBN, and then make it clearer with the refines property="source-of" being a new "virtualPagination" or "digitalPagination"

**Comment by mattgarrish** [comment]
> We still need some solution if there are page numbers added by the publisher for a digital only solution where there is no print version.

Why is this an accessibility issue, though? If the only version is digital, then nobody is disadvantaged by having to use the digital version.

The reason for identifying that there are print page numbers and giving the source is so you can determine if the ebook matches the specific print edition used in mixed environments.

With purely digital works, all you have to do is check its ISBN or other identifier to see that it's the same edition. Either everyone can coordinate if there are page numbers or no one can, but it doesn't raise a specific accessibility issue.

**Comment by clapierre** [comment]
> Why is this an accessibility issue, though? If the only version is digital, then nobody is disadvantaged by having to use the digital version.

If there are no embedded page breaks then you won't have the same experience when the same EPUB is opened on two different Reading systems when you try to turn to the same page.

Reading system X may do page #'s ever 1000 characters, reading system Y may break pages at 1000 words, or 1500 words or X number of paragraphs.  There won't be any consistency so you are forcing ALL students to use the same reader in order to all get to the same page #.

Having embedded page breaks in the EPUB is critical for accessibility no matter the reading system, screen size, etc.

**Comment by mattgarrish** [comment]
> There won't be any consistency so you are forcing ALL students to use the same reader in order to all get to the same page #.

This is a general usability issue. If no one can coordinate pages, then how is any group disadvantaged?

But my point above is that if the publisher only distributes a digital version with page breaks, then everyone gets a version with page breaks. There is no confusion about whose page breaks match what so putting in a self-referential source achieves nothing.

**Comment by clapierre** [comment]
Correct but if there are 2 books one with virtual page breaks embedded and one without and I as a school district to buy a book I would like to know which book to buy that has this issue addressed and doesn't leave it up to the reading system the students & teachers use.

**Comment by mattgarrish** [comment]
> Correct but if there are 2 books one with virtual page breaks embedded and one without

But is this a reality with digital-only books? Why would a single publisher produce two versions of the edition only varying by the inclusion of page breaks?

I think you're arguing something different than what is the source of the pagination, though, which is what I'm trying to get clarified in this issue.

A digital-only publication has no source for its page breaks. It's a misnomer to say that it is its own source, since that's self-referential. A book can't be the source of itself.

Your other questions I would categorize as:

- should we require page breaks no matter if there is a static source so everyone can access the same page. This is the ideal, for sure, but I don't think it falls within the scope of an accessibility spec to mandate this. That's why I'm saying this is a usability, or best practice, issue.
- should we indicate that a publication has page breaks even if there isn't a source for them. I understand your desire to put this in, but I also think this gets misleading as an accessibility feature. Experience suggests that when we move into these kinds of nuances it leads to confusion and misapplication of terms. All the page breaks are virtual, for example, whether they come from a print source or not.

**Comment by clapierre** [comment]
> But is this a reality with digital-only books? Why would a single publisher produce two versions of the edition only varying by the inclusion of page breaks?

I doubt a single publisher would do that, my thought was two competing publishers producing the same style of book with all else being equal I would want to purchase the one that had the embedded page breaks for consistent page navigation across all readers my students have.

My only issue is that right now we don't have a way to state that in the accessibility metadata if accessibilityFeature = "printPageNumbers" is only for print book page synchronization we don't have the equivalent for digital only.

I am less concerned maybe with the initial issue of self referencing for the source-of pagination although it is related.

If we need a separate issue for an accessibilityFeature of digitalPageNumbers I am fine with that but then we would also need to revise the statement

EPUB Creators MUST identify the source of the pagination in the Package Document metadata.

So how do they do that if the source of the pagination is itself?

**Comment by GeorgeKerscher** [comment]
Interesting thread! IMO this is not an accessibility issue and is better positioned as a usability issue. All kinds of good reasons for having virtual page numbers. We know xyz is looking to put them in, when a title does not come from the publisher with them, and here is where we need the standardization. If two people are using the same book, one from xyz and the other from abc and they are not identical, there will be no coordination. Citations are more difficult, book clubs  make it hard to talk about specific passages, and on-and-on.

 

In our discussion about indexes today, I see no conflict with virtual page numbers and direct locators to a paragraph. On virtual page 10, you may have the word dog half way down the page. The index that has dog could go directly to that paragraph on page 10. This is better than print indexes.

 

Just had to throw in my $.02

Best

George

**Comment by avneeshsingh** [comment]
I would suggest to allow this issue to focus on the source metadata for referring to print source.

It is important to have a metadata for identifying that the born digital publication has page locaters. Lets open a new issue for it. An option can be to have a new value in schema.org AccessibilityFeatures, something like virtual pages. Lets discuss more ideas  on a separate issue.

**Comment by clapierre** [comment]
The only issue is if we put in an exception that if there are embedded page breaks in the EPUB that the publisher put in, but there is no print equivalent source that we wouldn't require a dc:source metadata to be added then how can this be tested if its a normative statement?  How would EPUBCheck work?  I believe there is a check now that if there are page breaks and no dc:source it flags this as an error.

During our call @TzviyaSiegman  thought why couldn't we self-reference the ISBN of the EPUB, which I believe @mattgarrish thought this was really considered a hack.  If we spell this out in the specification would it really be then considered a hack?

This is what we suggest our GCA publishers do when they have page breaks for a digital Only EPUB.

**Comment by mattgarrish** [comment]
> which I believe @mattgarrish thought this was really considered a hack

It absolutely is a hack. How exactly can the book you have be the source of itself? It's a metaphysical impossibility. :)

But step back for a moment and consider what sense this makes outside of this group of insiders. If you'd never been involved in our discussions, how would you interpret a book that claims to be the source of itself? Wouldn't you consider this is a bizarre error in the metadata?

As to the question of enforcement, if everything has to be checkable by epubcheck we're in a lot of trouble.

But more to the point, could someone please explain what problem putting in a source when there isn't one solves? Why does there need to be a source in all cases?

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-04-08-epub-a11y#section3) on 2021-04-08

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

### 3. `dc:source` where there is no page source 

_See github issue [#1599](https://github.com/w3c/epub-specs/issues/1599)._




**Matt Garrish:** the reason i opened this issue is to deal with `dc:source` for epub with no print equivalent  
… we have a requirement where if you have pagelist then you have to identify source, but when there is no print equivalent there is no source  
… so the epub became its own source  
… doesn't really make sense  
… so suggest that where there is no print equivalent that we relax this requirement  

**Ben Schroeter:** tie to virtual page numbers, which are often determined by RS, and therefore could not be included in epub metadata when created  

**Charles LaPierre:** that would be if there are no pagebreaks in the epub itself  
… if there were already pagebreaks in the digital only epub, then the RS would just use those  

**Ben Schroeter:** but if they're included in the epub, then they aren't virtual anymore, right?  

**Matt Garrish:** yeah, this is a source of confusion. What it means for a pagebreak to be "virtual"  

**Avneesh Singh:** CharlesL can you open a new issue to discuss these sorts of use-case issues?  

**Charles LaPierre:** yeah  
… so if we're not going to have `dc:source` for digital only documents, how are RS to know that pagebreaks exist in the document?  
… this is not necessarily an a11y thing  
… but the distinction between embedded pagebreaks and pagebreaks created dynamically by RS is still important  

**George Kerscher:** i think RS putting in its own pagebreaks is a really bad idea due to lack of consistency  
… having pagebreaks come from publisher is ideal  
… but we know that some distributors are planning to put in their own pagebreaks where they don't already exist because they see the value of it  

**Ben Schroeter:** i don't think we can make it a requirement, but we can make it a strongly worded best practice  

**Avneesh Singh:** `dc:source` is not only for print equivalent, it could also be for FXL version, PDF, etc.  

**Tzviya Siegman:** we have digital only pubs, and we included page numbers  
… i think we made the `dc:source` the same as the ISBN of the epub  

**Avneesh Singh:** yes, this was the state of things in a11y 1.0  

**Tzviya Siegman:** and then publishers would decide where to put those digital only pagebreaks in  
… and maybe we can just write some best practice about how to do that  

**George Kerscher:** that algorithm is sometimes determined by the authoring tool used by the publisher  

**Charles LaPierre:** to tzviya's point, I think the whole self-referencing thing was what mgarrish was trying to get away from  
… though I liked it  

**Avneesh Singh:** this issue will surface again the virtual locators group  

> *Wendy Reid:* [https://github.com/w3c/epub-specs/wiki/Use-Cases-for-Virtual-Locators](https://github.com/w3c/epub-specs/wiki/Use-Cases-for-Virtual-Locators)

**Wendy Reid:** we have a wiki right now where we're gathering use-cases  
… these questions are worth including  

**George Kerscher:** why is self-referential source bad? Maybe we can just clarify in the spec that where there is no print equivalent then the source should just be the epub itself  

**Avneesh Singh:** CharlesL you can open a new issue about these various use-cases  

</details>

**Comment by avneeshsingh** [comment]
Summing up the discussions up to now:
1. dc:source should refer to print or digital equivalent if the static pages map to it.
2. We omit dc:source if the static pages do not map to any other edition. But if in such a case the publication has virtual pages then we can indicate it with schema.org accessibilityFeature (we can add a new value for it).

**Comment by mattgarrish** [comment]
We actually advise people in the 1.0 techniques document not to include a source if there isn't a print equivalent:

> If the page break markers are unique to the EPUB Publication, do not identify a print source.

The problem is that our normative requirement didn't match this, so it makes sense to me to add the proper condition that there be some other document the pagination is equivalent to when a source is required.

**Comment by GeorgeKerscher** [comment]
As I see it, the publisher may want to insert these page brakes and page navigation when there is no print source. We need a way to indicate that the publisher made this  enhancement. We also know that some distributors want to insert these virtual page breaks if the publisher has not done so. Here, we need a way to indicate that the distributor did this. When the distributor does this, it introduces problems, because from one distributor to another there is the potential that it will be inserted differently. For this reason, we should strongly encourage that the publisher insert these. We still have the issue of what is the source of these page numbers.

**Comment by avneeshsingh** [comment]
@GeorgeKerscher it looks that we are stepping beyond the scope of this specific issue. 
It would be better to open a new issue for discussing how to indicate that page numbers were generated without a print source.
In fact this issue is more related to updating or creating a metadata value in schema.org and ONIX. So, there is a option to delegate it to Publishing CG where metadata work is already going on.

**Comment by mattgarrish** [comment]
To replicate some of the comment I made in the pull request so it's not lost, and expand on it, I don't think the print page number accessibility feature is terribly helpful. It was developed in a bit of a vacuum as far as actual use would go, and what is it telling you? It doesn't tell you if there is a page list or page break markers or both, only that if these exists they are tied to some print source that can't be specified through schema.org metadata.

If we stick with only identifying a source of pagination when there is an actual statically-paginated equivalent somewhere that the page break markers and/or page list match up to, then the need for marking this as a distinct accessibility feature disappears. All we need is a generic way of saying that there are physical markers in the markup (and a page list).

But for the sake of not talking abstractly (and not to suggest these are the final values), say we added pageList and staticLocators to accessibilityFeature.

From that, we know:

- accessibilityFeature=staticLocators plus dc:source means there are page breaks in the markup from a paginated source
- accessibilityFeature=pageList plus dc:source means there is a page list to access the page break locations of the paginated source
- accessibilityFeature=staticLocators plus accessibilityFeature=pageList plus dc:source means all pagination is from a paginated source

Obviously, if you omit dc:source you know that the page list and locators were created just for the current publication.

This should also give some flexibility for whether digital edition-only locators in the future exist as markup in the document or are solely defined by a page list.

But as @avneeshsingh has already mentioned, where we should try to solve these metadata issues is a good question. Neither the specification nor the techniques currently delve into how to apply accessibility feature metadata to pagination, so it's not like we have bad advice we need to fix. The CG may also be the more appropriate place for schema.org metadata as we don't want to be tied to revisions to be able to take up these kinds of issues.

**Comment by avneeshsingh** [comment]
The issue was discussed in [June 24, 2021 a11y task force meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-06-24-epub-a11y).
 Resolution #1: Identify the source in the metadata only if the static pages correspond to another version of the publication, and not when the publication is source of its own pagination.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-06-24-epub-a11y#section1) on 2021-06-24

List of resolutions:

- ***[Resolution No. 1](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-06-24-epub-a11y#resolution1):  Identify the source in the metadata only if the static pages correspond to another version of the publication, and not when the publication is source of its own pagination.***

<details><summary><i>View the transcript</i></summary>

### 1. Page source when no source 

_See github issue [#1599](https://github.com/w3c/epub-specs/issues/1599)._


> *Avneesh Singh:* PR: [https://github.com/w3c/epub-specs/pull/1697/files/839fbaf8c98e7423a0bc6becfa3750472c17d868](https://github.com/w3c/epub-specs/pull/1697/files/839fbaf8c98e7423a0bc6becfa3750472c17d868)


**Matt Garrish:** should not provide source if there is no paper source for the pagination.  
… should provide if there is an actual source. even if the page #'s are virtual  

> **Proposed resolution: Identify the source in the metadata only if the static pages correspond to another version of the publication, and not when the publication is source of its own pagination.** *(Avneesh Singh)*

> *Charles LaPierre:* 0

> *Matt Garrish:* +1

> *Ben Schroeter:* +1

> *Tzviya Siegman:* +1

> *Bill Kasdorf:* +1

> *Laura Brady:* +1

> *Will Awad:* +1

> ***Resolution #1: Identify the source in the metadata only if the static pages correspond to another version of the publication, and not when the publication is source of its own pagination.***

</details>
