### ISSUE TITLE
CSS required for all Reading Systems, or only those with a viewport?

### ISSUE THREAD

**Issue by dlazin** [w3c/epub-specs#1604]
https://w3c.github.io/epub-specs/epub33/rs/#sec-css says `A conformant EPUB Reading System ... MUST support the official definition of CSS as described in the [CSSSnapshot].` That appears to apply to *all* RSes.

But https://w3c.github.io/epub-specs/epub33/rs/#confreq-rs-epub3-css (scroll up one line) makes this conditional on a viewport: `In addition, if a Reading System has a Viewport: It MUST support visual rendering of XHTML Content Documents as defined in § 4.3 CSS Style Sheets.`

Which is correct? Presumably the latter (which occurs first in the spec).

**Comment by mattgarrish** [comment]
> Which is correct? Presumably the latter (which occurs first in the spec).

Yes, the high-level section 2 still defines the overarching requirements for feature support. If you're required to support a feature (because there's a viewport or audio capability), then the specific support requirements in the referenced section kick in.

A lot of this indirection again had to do with authoring and reading system requirements being merged together in the past. A lot of "requirements" were simply pointers to help devs find where there were actual requirements they needed to pay attention to.

I just did another pass to try and get rid of the more pointless of these requirements, but it was only at the feature level (i.e., all the sections after section 2).

I was a little hesitant to break up section 2 as it is kind of a convenient overview of everything a reading system has to be able to handle, but there's an argument that separating overall support from the respective subsections just adds confusion. I'm open to further flattening out the specification so that each section encapsulates everything you need to know about it.

**Comment by dlazin** [comment]
Ah, that makes sense. I had a similar thought that I didn't file: section 2 says `Support for the following features is OPTIONAL: Fixed-Layout Documents, Media Overlays`, but then the dedicated sections for those features don't mention that they're optional.

IMO, we should repeat the optionalness in the subsections. It's common, especially in technical documentation, for readers to skim and jump around; when possible, we should give them all the info in one place, rather than requiring that they read both sections and mentally correlate. In these cases, we're just talking about a few words per section, so I would encourage repeating ourselves to avoid confusion.

**Comment by iherman** [comment]
I believe that is now covered in the [latest version of the RS spec](https://w3c.github.io/epub-specs/epub33/rs/#sec-css). It says:

> If a Reading System has a Viewport, it MUST support the visual rendering of XHTML Content Documents via CSS [EPUB-33].

@dlazin, is it o.k. to close this?

**Comment by dlazin** [comment]
Yep, looks great! Thanks.
