### ISSUE TITLE
epubReadingSytem methods should be marked as required

### ISSUE THREAD

**Issue by dlazin** [w3c/epub-specs#1610]
https://w3c.github.io/epub-specs/epub33/rs/#app-ers-properties (`epubReadingSystem` properties) says `The following properties MUST be made available for retrieving information about the Reading System.`

However, the equivalent section for `epubReadingSystem` methods, https://w3c.github.io/epub-specs/epub33/rs/#app-ers-methods, does not explicitly say that the methods must be implemented. Can we copy the same sentence, swapping "properties" for "methods"?

**Comment by iherman** [comment]
There is a more general issue about the role and fate of Appendix A in general: #1420. I would propose to postpone this issue until #1420 is resolved.

**Comment by dlazin** [comment]
Fine by me if that's what you want, but we *could* just add the one sentence (mirroring the Properties section) and then close this issue, just so we have fewer option issues. #1420 could still track the bigger question. To me, adding this one sentence now seems uncontroversial by itself because Properties already has it.

**Comment by iherman** [comment]
You are probably right. But we should sync with what we decide related to #1615

**Comment by dlazin** [comment]
That's merged now — want to get this one out of the way?

**Comment by iherman** [comment]
Well... looking at it again, I am not sure that there is anything to change. The real meat is in [§A.4.1.2](https://w3c.github.io/epub-specs/epub33/rs/#app-ers-hasFeature-features) and that says essentially the same thing already.

**Comment by dlazin** [comment]
Yes, you're right. Closing!

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-04-08-epub#section3) on 2021-04-08

List of resolutions:

- ***[Resolution No. 1](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-04-08-epub#resolution1):  Flag appendix A as at-risk, keep as a normative requirement and test implementation, remove the WebIDL***

<details><summary><i>View the transcript</i></summary>

### 3. WebIDL/epubReading System 

_See github issue [#1610](https://github.com/w3c/epub-specs/issues/1610), [#1420](https://github.com/w3c/epub-specs/issues/1420), [#716](https://github.com/w3c/epub-specs/issues/716)._




> *Wendy Reid:* See [relevant section in the core spec](https://www.w3.org/TR/epub-rs-33/#app-epubReadingSystem)

**Ivan Herman:** we have a separate section with a small webIDL describing the RSO  
… i have two questions  
… first, should it be normative? (it currently is)  
… second, if normative, we may run into the problem that webIDL is considered by browser implementors as something they have to implement  
… other specs I've worked on have used webIDL, and it has gotten us into trouble  
… I'd prefer to avoid this if possible  
… the spec also calls it a JS epubReadingSystem object, but webIDL is supposed to be language independent  

**Dave Cramer:** is there something in W3C policy that says if you use webIDL then all browsers must implement it?  

**Ivan Herman:** no, BUT i'd rather not get into this type of discussion about down the line  
… some other people might disagree with me and say that implementation is required. We do not want this discussions with the AC at voting time.  

**Brady Duga:** i think webIDL is for things intended to be implemented by browsers  
… but it does seem to be a normative requirement because of statements that we make later on in the appendix  

**Wendy Reid:** can someone please explain the importance of webIDL?  

**Brady Duga:** we were just trying to describe the RSO stuff using webIDL  

**Tzviya Siegman:** one of our goals is the define the role of the RS more clearly, and I'm not sure that this section does that?  

**Dave Cramer:** I think it does, webIDL is the industry standard for describing APIs  

**Garth Conboy:** maybe we can just describe it in JS?  

**Ivan Herman:** I think yes  

**Garth Conboy:** so webIDL might be fine to use, but if JS is also fine to use, then maybe we can resolve this small thing by just using JS  

**Matt Garrish:** some time back there was also discussion about maybe dropping RSO entirely...  

**Ivan Herman:** if we turn that section into informative only, then that allows us to bypass formal objections down the line?  

**Dan Lazin:** are we currently just discussing the question of how to DOCUMENT RSO? And how widely implemented is it?  

**Dave Cramer:** some do, some don't  

**Garth Conboy:** do we care about the requireness of this given that support isn't unanimous  

**Brady Duga:** not sure how common this is. We should write a test and try it in some RSes  
… has anyone in this call implemented it?  
… yes it is normative now, and there are MUST statements that point to this, but on the other hand we might spend a lot of time on this only to find out that no one really uses it  
… if no one implements this, then we can decide whether to drop it or make it non-normative etc.  
… and publishers should tell us if they use JS in their epubs, and if yes, then have they relied on this being available  

**Dave Cramer:** we've used this because of the state of epub interoperability  
… we use this to figure out which RS our epub is in  
… e.g. UA sniffing  

**Dan Lazin:** speaking of interop, one of the testing questions is: When we identify that not RS currently supports, e.g. Opus, does that mean that it ought not to be a core media type?  
… my feeling is that giving guidance on where we want to go is a pathway towards future interop  
… but when we mandate things that are not widely used, that leads RS implementors to not know what to trust  
… and I'm happy to write a test about this  

**Ken Jones:** a lot of FXLs with interactive content rely on scripting, so this is important  

**Dave Cramer:** it is possible to support scripting without relying on epubReadingSystem Object  

**Ivan Herman:** for now, do we say that this thing should be implemented by RS?  
… the other possibility is that we keep as normative requirement, but flag as at risk  

**Avneesh Singh:** +1 to ivan, flag at risk and keep as normative requirement for now

**Ivan Herman:** I'm leaning towards the second option, plus, rewording the section using JS  

> **Proposed resolution: Flag appendix A as at-risk, keep as a normative requirement and test implementation, remove the WebIDL** *(Wendy Reid)*

> *Garth Conboy:* +1

> *Gregorio Pellegrino:* +1

> *Brady Duga:* +1

> *Matt Garrish:* +1

> *Deborah Kaplan:* +1

> *Masakazu Kitahara:* +1

> *Avneesh Singh:* +1

> *Dan Lazin:* +1

> *Ben Schroeter:* +1

> *Matthew Chan:* +1

> *Ivan Herman:* +1

> *Tzviya Siegman:* +1

> *George Kerscher:* +1

> *Charles LaPierre:* +1

> ***Resolution #1: Flag appendix A as at-risk, keep as a normative requirement and test implementation, remove the WebIDL***

</details>
