### ISSUE TITLE
Length of file and path names

### ISSUE THREAD

**Issue by xfq** [w3c/epub-specs#1629]
https://w3c.github.io/epub-specs/epub33/core/#sec-container-filenames

>   File Names MUST NOT exceed 255 bytes.

>   The Path Name for any directory or file within the OCF Abstract Container MUST NOT exceed 65535 bytes.

What if the File Name is more than 255 bytes or the Path Name is more than 65535 bytes? Will they be truncated?

The i18n WG has related guidelines here: https://w3c.github.io/bp-i18n-specdev/#char_truncation

**Comment by mattgarrish** [comment]
> What if the File Name is more than 255 bytes or the Path Name is more than 65535 bytes? Will they be truncated?

We don't currently define what a reading system should do [if it can't unzip a file](https://w3c.github.io/epub-specs/epub33/rs/#sec-container-filenames), as if you truncate the path or file name you also have to check and modify the content for any references to the path and name that would also have to be repaired.

But, similar to the [note about authoring tools that can't handle unicode](https://w3c.github.io/epub-specs/epub33/core/#h-note-48), we could perhaps add a note to the reading system section noting that content would need repairing and cite these guidelines for approaches to truncating (or make the section informative and write it directly in, since the section doesn't say anything normative right now anyway).

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-04-23-epub#section1-2) on 2021-04-23

List of resolutions:

- ***[Resolution No. 2](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-04-23-epub#resolution2):  Add a note to clarify that a RS should do what it can with filenames that exceed the limit***

<details><summary><i>View the transcript</i></summary>

#### 1.2. Length of file and path names 

_See github issue [#1629](https://github.com/w3c/epub-specs/issues/1629)._




**Dave Cramer:** file names must not exceed 255B, path name not more than 65535B  
… so what happens if these limits are exceeded?  
… my initial reaction is to say if you have some massively long file name and the RS knows what to do, then I don't think we should ask RS to fail artificially  

**Dan Lazin:** so maybe, "file names must abide, if not RS must truncate"?  

**Matt Garrish:** we've talked about this in the past  
… truncation leads to having to modify all the content  
… but then how we enforce?  
… maybe we could point to a method of truncation that RS can use  
… but at best this is note territory  
… we shouldn't specify normative stuff to address this  

**Dave Cramer:** basically if you go outside of what the rules are, things may break  
… if the file names are truncated, the RS may not know what to do, may not be able to identify the file  

**Charles LaPierre:** as long as epubcheck throws an error for long file names, most distributors won't accept those epubs  
… most people won't see those books  

**Ivan Herman:** a few weeks ago we had a discussion like this about content document processing (see [spec intro for content docs](https://w3c.github.io/epub-specs/epub33/rs/#sec-contentdocs))  
… i think we should use the same text for the package document processing  
… this is all the same sort of thing, where spec says what you should do, and we're concerned with what RS should do if content does not conform  
… if we change our mind here, then we should go back and change what we did for content document processing too  

**Dave Cramer:** can we just say that if RS encounters file name or path exceeding limit that it should try to process it?  
… and if it fails then it doesn't have to do anything else?  
… i.e. no obligation to truncate, but continue to process if it can  

**Brady Duga:** we don't say what RS should do, so whether I try to continue to process or not, I'd be in spec  
… let's just explicitly say that RS should try  

**Matt Garrish:** should there be a note as well that if you try truncation, then you may have to go into the content as well?  
… should we note the problems with truncation?  

**Dave Cramer:** i think we're kind of dealing with that by advising people not to use long file names in the first place  
… but no strong feelings, either way  

**Wendy Reid:** okay, so we're leaving in the requirement about file name size  

**Ivan Herman:** in the issue, Fuxiao gave i18n link that says spec should not try to limit length of names  

**Brady Duga:** good point  
… if you are JP using UTF8, that's really not a lot of characters  
… maybe we should just follow whatever the zip specification says and not add extra requirements  

**Matt Garrish:** these requirements exist to try to maintain cross-compat  
… we don't want to be creating OS-based compatibility issues  
… i'm concerned about dropping these requirements  

**Brady Duga:** i think the 255B number is based on some legacy system (e.g. Pascal)  
… somewhat arbitrary to enforce this today  

**Dave Cramer:** isn't this a limit of Windows? Not a limit of winzip or the zip spec?  

**Brady Duga:** Mac paths apparently have a limit of 260 char, not byte  

**Dave Cramer:** i am fine with keeping the limit in order to make epubs more universal  
… maybe just add something that says RS should still try to process document if it encounters file name or path exceeding limits  

> **Proposed resolution: Add a note to clarify that a RS should do what it can with filenames that exceed the limit** *(Wendy Reid)*

> *Ivan Herman:* +1

> *Dave Cramer:* +255

> *Deborah Kaplan:* +1

> *Matthew Chan:* +1

> *Toshiaki Koike:* +1

> *Masakazu Kitahara:* +1

> *Ben Schroeter:* +1

> *Brady Duga:* +1

> *Matt Garrish:* +1

> *Wendy Reid:* +1

> *Gregorio Pellegrino:* +1

> *Charles LaPierre:* +1

**Matt Garrish:** it will be a SHOULD, not a note. It will be normative.  

> ***Resolution #2: Add a note to clarify that a RS should do what it can with filenames that exceed the limit***

</details>

**Comment by xfq** [comment]
Sorry for the late response. I understand that the restrictions may be from legacy system's constraints, but it would be useful if the text in https://w3c.github.io/epub-specs/epub33/core/#sec-container-filenames states that if file and path names are truncated the truncation should not occur in mid-of-character.

**Comment by mattgarrish** [comment]
I don't disagree that this is an important consideration for truncating, but the issue with adding specific prose like this is that it assumes a reading system is going to truncate the file name as given, and that's not a requirement in the reading system specification. All we say for processing is:

> This specification does not specify how a Reading System that is unable to represent OCF File and Path Names would compensate for this incompatibility.

Which is intentionally vague, as a reading system might simply rename the resource to a completely new and valid path/name rather than deal with the invalid path/name provided by the author.

**Comment by aphillips** [comment]
I18N discussed this in teleconference today (2021-05-27) and I drew the action to respond here. Our concern is not to add additional normative requirements here. However, given that there is normative text about the file name and path length and this is expressed in bytes (over a multibyte encoding, i.e. UTF-8), we think it would be useful to include a health warning. We are less concerned with reading systems receiving the epub document than with reminding implementers on best practices when imposing the limit (when authoring the content). This might be included in the existing note at the end of this section or as a new note. I'd suggest wording similar to:

> If an EPUB Creator imposes length limits on path and file names, it is important to avoid mid-character truncation due to the difference between bytes and characters in multibyte encodings such as UTF-8. See https://w3c.github.io/bp-i18n-specdev/#char_truncation for more information.

**Comment by r12a** [comment]
The link should point to the /TR version, ie. https://w3c.github.io/bp-i18n-specdev/#char_truncation

**Comment by iherman** [comment]
You mean https://www.w3.org/TR/international-specs/#char_truncation, right?

**Comment by r12a** [comment]
Oops, yes. Sorry.  Bad paste, unnoticed.

**Comment by iherman** [comment]
@r12a @aphillips I have created a PR (#1702) which adds a note to the section imposing shorter file names for EPUB Creators, see https://pr-preview.s3.amazonaws.com/w3c/epub-specs/pull/1702.html#sec-container-filenames. 

As @mattgarrish said in https://github.com/w3c/epub-specs/issues/1629#issuecomment-846603508 the Reading System document is now intentionally vague on this problem and, actually, it is not the Reading System but the EPUB Creator that does the truncation (if needed) so I do not think adding anything to the Reading System document is necessary.
