### ISSUE TITLE
Character restrictions on the file names

### ISSUE THREAD

**Issue by xfq** [w3c/epub-specs#1632]
https://w3c.github.io/epub-specs/epub33/core/#sec-container-filenames

There are a few restrictions on the characters in file names, and the i18n WG has comments on the following two restrictions:

> Non characters in Arabic Presentation Forms-A (U+FDDO … U+FDEF)

First, `U+FDDO` should be `U+FDD0` (zero instead of oh) here.

The U+FDD0 … U+FDEF range is indeed unassigned, but why not other unassigned characters in other blocks? Moreover, unassigned code points may become assigned later.

> Non characters at the end of the Supplementary Planes (U+1FFFE, U+1FFFFF … U+EFFFE, U+EFFFF)

`U+1FFFFF` is out of the Unicode codespace. Perhaps it means `U+1FFFF`?

**Comment by mattgarrish** [comment]
I'll get the typos part of this issue fixed shortly.

> First, `U+FDDO` should be `U+FDD0` (zero instead of oh) here.
> `U+1FFFFF` is out of the Unicode codespace. Perhaps it means `U+1FFFF`?

**Comment by mattgarrish** [comment]
For context, here's some of the discussion that led to the expanded character restrictions: https://github.com/w3c/epub-specs/issues/125

**Comment by dauwhe** [comment]
> The U+FDD0 … U+FDEF range is indeed unassigned, but why not other unassigned characters in other blocks? Moreover, unassigned code points may become assigned later.

We put in this restriction because Unicode describes these as noncharacters (and they are immutable). I don't believe we have ever said anything about unassigned characters.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-04-23-epub#section1-4) on 2021-04-23

List of resolutions:

- ***[Resolution No. 4](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-04-23-epub#resolution4):  Close issue 1632***

<details><summary><i>View the transcript</i></summary>

#### 1.4. Character restrictions on the file names 

_See github issue [#1632](https://github.com/w3c/epub-specs/issues/1632)._




**Dave Cramer:** character restrictions on file names  
… there were typos  
… already a PR in to fix those  
… i think all we have to do is resolve to accept the PR here  

**Matt Garrish:** the typo PR was already merged, actually  

**Dave Cramer:** as far as i know, we now ban all non-characters  

**Matt Garrish:** yes  
… Fuxiao is asking why we banned certain parts of the Arabic Presentation Forms, but not other unassigned chars in other blocks  

**Dave Cramer:** and I answered that the Arabic Presentation Forms thing was because those were non-characters  
… we haven't said anything about unassigned character blocks  

**Ivan Herman:** we should ping Fuxiao to ask if it is okay to close the issue now  

**Dave Cramer:** do we need to resolve to close issue?  

**Ivan Herman:** I think we should, because we asked i18n WG  

> **Proposed resolution: Close issue 1632** *(Wendy Reid)*

> *Deborah Kaplan:* +1

> *Ivan Herman:* +1

> *Garth Conboy:* +1

> *Wendy Reid:* +1

> *Matt Garrish:* +1

> *Brady Duga:* +1

> *Matthew Chan:* +1

> *Toshiaki Koike:* +1

> *Masakazu Kitahara:* +1

> ***Resolution #4: Close issue 1632***

> *Dave Cramer:* +1FFFF

</details>

**Comment by iherman** [comment]
There was enough lead time for reactions; closing

**Comment by r12a** [comment]
> We put in this restriction because Unicode describes these as noncharacters (and they are immutable). I don't believe we have ever said anything about unassigned characters.

@dauwhe I'm curious about the source for this distinction between 'noncharacters' and 'unassigned characters'.  As far as i'm aware, U+FDD0..U+FDEF characters are just ordinary unassigned, as are the unassigned codepoints elsewhere, including U+FBC3..U+FBD2 in the same block.

**Comment by mattgarrish** [comment]
According to the FAQ on the unicode site:

> Q: What are noncharacters?
> A: A "noncharacter" is a code point that is permanently reserved in the Unicode Standard for internal use.
> ...
> Q: Which code points are noncharacters?
> A: The 66 noncharacters are allocated as follows:
> 
> - a contiguous range of 32 noncharacters: U+FDD0..U+FDEF in the BMP
> ...
>
> Q: Why are 32 of the noncharacters located in a block of Arabic characters?
> A. The allocation of the range of noncharacters U+FDD0..U+FDEF in the middle of the Arabic Presentation Forms-A block was mostly a matter of efficiency in the use of reserved code points in the rather fully-allocated BMP. The Arabic Presentation Forms-A block had a contiguous range of 32 unassigned code points, but as of 2001, when the need for more BMP noncharacters became apparent, it was already clear to the UTC that the encoding of many more Arabic presentation forms similar to those already in the Arabic Presentation Forms-A block would not be useful to anyone. Rather than designate an entirely new block for noncharacters, the unassigned range U+FDD0..U+FDEF was designated for them, instead.

http://www.unicode.org/faq/private_use.html#noncharacters

**Comment by r12a** [comment]
Interesting. Thanks @mattgarrish.  I was unaware of that FAQ page.
