### ISSUE TITLE
Language and direction metadata missing

### ISSUE THREAD

**Issue by xfq** [w3c/epub-specs#1633]
Will the `name` attribute in the [EpubReadingSystem](https://w3c.github.io/epub-specs/epub33/rs/#app-epubReadingSystem) be rendered and read by a user (not just an internal identifier)? If so, it should have language and direction metadata.

See [string-meta](https://w3c.github.io/string-meta/) for more information.

**Comment by iherman** [comment]
> Will the `name` attribute in the [EpubReadingSystem](https://w3c.github.io/epub-specs/epub33/rs/#app-epubReadingSystem) be rendered and read by a user (not just an internal identifier)? If so, it should have language and direction metadata.
> 

I believe, the attribute is "assigned" by the particular Reading System and is meant to be used by scripts to adapt their behaviour. (It is a bit like the user agent string that HTTP may return.) Ie, I do not think that the language and direction metadata is relevant for this case.

**Comment by mattgarrish** [comment]
> It is a bit like the user agent string that HTTP may return

Right, it's effectively like navigator.userAgent but avoids collision with it.

Because epub has a lot of flexibility, and because there isn't consistency in what reading systems support, the object was added to allow authors to try and adapt their content to the capabilities of the device.

Presenting the name to users probably doesn't make a lot of sense, as the user already knows what device they're using. But if the author did want to do this they'd have to write it into the dom, so language and direction would be available using the features of html/svg.

**Comment by iherman** [comment]
@xfq are these answers satisfying? Ie, can we close this issue?

**Comment by xfq** [comment]
Yes. Thanks for the explanation.
