### ISSUE TITLE
Handling of invalid properties

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1673]
For the property data type, we say Reading System concatenation of the base URL and value must result in a valid url string.

So what happens if it doesn't? Must Reading Systems ignore the value? Should they ignore it? Or do we not care?

**Comment by iherman** [comment]
My vote would be to ignore the value (and, possibly, issue a warning)

**Comment by bduga** [comment]
Where is the current conformance language? I am somehow not seeing it.

**Comment by mattgarrish** [comment]
Current language is here: https://w3c.github.io/epub-specs/epub33/rs/#sec-property-datatype

Updated language in the open PR is here: https://cdn.statically.io/gh/w3c/epub-specs/fix/issue-808/epub33/rs/index.html#sec-property-datatype

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-05-13-epub#section7) on 2021-05-13

List of resolutions:

- ***[Resolution No. 3](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-05-13-epub#resolution3):  If a property is invalid, ignore it, close issue 1673***

<details><summary><i>View the transcript</i></summary>

### 7. Handling of invalid properties 

_See github issue [#1673](https://github.com/w3c/epub-specs/issues/1673)._




**Matt Garrish:** when I was making the URL spec change this came up  
… when property values expand, they are supposed to expand into valid URL string  
… assuming that if it is invalid, then RS should ignore property  

**Brady Duga:** there are also situations where RS is suppose to ignore in failure case  

**Dave Cramer:** right, this causes as little disruption to reading experience as possible  
… e.g. not doing something to alert the reader  

> **Proposed resolution: If a property is invalid, ignore it, close issue 1673** *(Wendy Reid)*

> *Ben Schroeter:* +1

> *Shinya Takami (高見真也):* +1

> *Brady Duga:* +1

> *Matt Garrish:* +1

> *Dave Cramer:* +1

> *Matthew Chan:* +1

> *Fred Chasen:* +1

> *Toshiaki Koike:* +1

> *Wendy Reid:* +1

> ***Resolution #3: If a property is invalid, ignore it, close issue 1673***

</details>

**Comment by iherman** [comment]
@mattgarrish I did not know whether you want to change something on the spec related to this, so I did not close this issue yet.

**Comment by mattgarrish** [comment]
Also will close automatically with #1650. I've added the statement to the updated section on expanding property data types (as linked in the above comment).
