### ISSUE TITLE
Support for mixed fixed layout and flowing

### ISSUE THREAD

**Issue by bduga** [w3c/epub-specs#1708]
In issue #1606 we decided to require support for fixed layout content based on the fact that many reading systems already support it, and it is useful for authors to be able to rely on it. However, that means that mixed flowing and fixed layout content is also now required, since we didn't explicitly say otherwise. However, it is my belief that such mixed content is not well supported by reading systems. If that is the case, should we consider marking such mixed content as at risk? Or am I wrong and there are already multiple reading systems that support such content?

**Comment by OriKuttner** [comment]
I am not aware of any reading system that supports mixed layouts.

-- 
Ori Idan CEO Helicon Books
http://www.heliconbooks.com

**Comment by iherman** [comment]
> ... should we consider marking such mixed content as at risk? 

I have no problem making this explicit in the document and let CR decide whether there are at least two RS implementing this.

**Comment by wareid** [comment]
Closing this issue as a test has been written, and we'll see how testing plays out.

**Comment by joseph** [comment]
FYI, OverDrive Read (used by Libby) has had a full implementation of EPUB3 mixed layout (MXL) since about 2014. 

Libby is the #1-ranked EPUB reading system in both the App Store and the Play Store, and has many millions of daily active users. There's no lack of implementation, there's only a lack of publisher adoption. From personal experience designing a few test books, MXL titles always feel remarkably polished. It would be a shame to drop it from your spec due to under-implementation by other reading systems.
