### ISSUE TITLE
obsolete spec link?

### ISSUE THREAD

**Issue by danielweck** [w3c/epub-specs#1711]
Hello, I noticed that when I search for "epub w3c specification" in my web browser (Google Search), the top search results is https://www.w3.org/publishing/epub3/epub-spec.html which is "Final Community Group Specification 08 May 2019" and which contains a dead link "Latest editor's draft:" https://w3c.github.io/publ-epub-revision/epub32/spec/epub-spec.html

**Comment by iherman** [comment]
Is https://github.com/w3c/epub-specs/tree/main/archive/epub32/spec the right URL now? @mattgarrish @dauwhe ?

If so, I will have to change this in the document (I guess in all of them, not only this one) by hand. But I need a nod from you guys...

**Comment by iherman** [comment]
Sorry, I meant the github.io equivalent: https://w3c.github.io/epub-specs/archive/epub32/spec/epub-spec.html & Co.

**Comment by mattgarrish** [comment]
Ya, I guess so.

Why does W3C link to a latest editor's draft from final documents, though? Seems kind of weird. I'd have expected that link to disappear.

**Comment by mattgarrish** [comment]
Should those links go to the "latest editor drafts" of 3.3? That would at least make a bit more sense, but seems like a pain to maintain.

Something amiss about a link to an editor's draft that precedes the final version but is dated today... but maybe this is what our new publishing process to TR will get rid of?

**Comment by iherman** [comment]
> Ya, I guess so.
> 
> Why does W3C link to a latest editor's draft from final documents, though? Seems kind of weird. I'd have expected that link to disappear.

Remember that this is not a formal TR document so the TR publication rules do not apply. The publication format is a bit ad-hoc: we wanted something more formal then a CG "draft", but we could not publish a /TR.

**Comment by iherman** [comment]
I see several possibilities:

1. We use https://w3c.github.io/epub-specs/archive/epub32/spec/epub-spec.html (and equivalent). Which would refer to the "editors' drafts" of 3.2. However, that document is bound to be frozen, I do not believe it would change at any time.
2. We could refer to the 3.3 /TR documents (using undated URL), but that may be premature as it would suggest that 3.2 is obsolete
3. We could remove that link altogether because it would not provide any new, meaningful information

I am tempted to go for (3) but we should wait for @dauwhe to come back from vacations...

**Comment by mattgarrish** [comment]
> this is not a formal TR document so the TR publication rules do not apply

TR REC documents also have "latest editor's draft" links. What they go to all seems to depend on how the underlying repository is used. If the group keeps working on the same file for the next revision, you see the draft for the latest work (see the ARIA spec, for example). Otherwise you get a stale document with a date that may look recent.

But hopefully the new process does away with these.

**Comment by iherman** [comment]
I do not know whether the process will make that change. At the moment, if the group uses automatic publishing of each editor's draft as a TR document (something that we will also go for) then having the editor's draft does not make too much sense indeed. But remember that this changes once you get to CR/PR/Rec, when ECHIDNA is not necessarily used anymore. Ie, once we get to that stage, having a separate editors' draft reference makes sense again.

Anyway, this is not really relevant for the issue at hand, because we are not bound to pubrules. Let us see what @dauwhe thinks about the possible choices...

**Comment by iherman** [comment]
@dauwhe, as former chair of the CG that produced 3.2, which options of https://github.com/w3c/epub-specs/issues/1711#issuecomment-864350987 should we choose?

(We should get this done and remove this issue from the list of open issues...)

**Comment by dauwhe** [comment]
My instinct from my CSS days is to have the latest editor's draft link on 3.2 point to the editor's drafts of 3.3. That is indeed the most recent work. 

I would also be fine with just removing any such link (option 3). I don't think we should point to a GitHub.io version of EPUB 3.2--there's really no reason for that.

**Comment by iherman** [comment]
I personally would prefer to remove all links. I am a bit worried that this would suggest 3.2 is outdated; this community seems to be very sensitive to these things...

Will take care of these tomorrow

**Comment by iherman** [comment]
I have commented out all the 'latest version' links after having updated the links to the right github.io addresses. This means that, currently, that header is not present but, if for whatever reasons we want to reinstate them, they can be uncommented, and they would then point to the right addresses.

A note to ourselves: when 3.3 is close to the final version (ie, in CR or PR) then we will have to give some thoughts on how to handle the transition. Ie, should we

1. change the series of redirections of `https://www.w3.org/publishing/epub3/` and `https://www.w3.org/publishing/epub/` towards the /TR versions? (They currently go to epub32)
2. define a series of redirections of `https://www.w3.org/publishing/epub33/` towards the /TR versions?
3.  re-instate these headers in the 3.2 documents towards the 3.3 equivalents?

These will have to be discussed later. 

(I close this issue by also labeling it as 'deferred' so that it would not bother us as an open issue, but we can find it easily later for this discussion.)

cc @TzviyaSiegman @swickr @mattgarrish @dauwhe
