### ISSUE TITLE
TTS note title

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1715]
One issue I forgot to raise for the initial extraction is what do we name this thing. For now, I've named it "EPUB 3 Text-to-Speech Enhancements".

The oddity here is that this is neither new (it succeeds from 3.2) nor a rec-track 3.3 specification, so it's just as odd to number it "EPUB Text-to-Speech Enhancements 1.0" as it is to number it "EPUB Text-to-Speech Enhancements 3.3".

I don't think the name I have right now works, though, since it doesn't have a incrementable number, so open to other ideas on what to call or number it.

**Comment by iherman** [comment]
We have named multiple renditions as "EPUB Multiple-Rendition Publications 1.1", although, I believe, the same arguments apply. Maybe, to be consistent, we could call it "EPUB Text-to-Speech 1.1".

**Comment by mattgarrish** [comment]
> although, I believe, the same arguments apply.

Not really. What is defined in the multiple renditions spec is all brand new stuff - rendition selection attributes, mapping documents, grammar for the metadata.xml file and whatever else. There's no legacy of any of that stuff existing in the 3.0+ that you would ever refer to.

It'd be odd to number it to match multiple renditions and not have a "1.0" anywhere, though.

Maybe we can mash everything together and get "EPUB 3 Text-to-Speech Enhancement 1.0".

Even "EPUB 3 Multiple Rendition Publications 1.1" sounds better than what we have, since the specification is not applicable to EPUB 2 or a future 4+. (Suggesting we rename that one, not a typo!)

**Comment by iherman** [comment]
> > although, I believe, the same arguments apply.
> 
> Not really. What is defined in the multiple renditions spec is all brand new stuff - rendition selection attributes, mapping documents, grammar for the metadata.xml file and whatever else. There's no legacy of any of that stuff existing in the 3.0+ that you would ever refer to.

What I meant was: multiple rendition was part of EPUB 3.2, and we took it aside due to poor implementation. There are similarities in this respect... (O.k., I know, there was a separate IDPF 1.0 version, so that is different.)  

> 
> It'd be odd to number it to match multiple renditions and not have a "1.0" anywhere, though.

That is true
> 
> Maybe we can mash everything together and get "EPUB 3 Text-to-Speech Enhancement 1.0".

Works for me

**Comment by mattgarrish** [comment]
Closing this issue as I've update the title in https://github.com/w3c/epub-specs/commit/4f667e26e011c56d204a92820a469291761714ad and the short name in https://github.com/w3c/epub-specs/commit/633ad4b1bec718dc1a0b7ba2b054f408652c6c72

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-06-24-epub#section2) on 2021-06-24

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

### 2. Text-To-Speech 

_See github issue [#1715](https://github.com/w3c/epub-specs/issues/1715), [#1717](https://github.com/w3c/epub-specs/issues/1717)._




**Wendy Reid:** last week we discussed what to do with PLS and SSML in the spec. We aren't getting rid of them, but are separating them into their own separate document.  
… the issues were just doing this  

**Matt Garrish:** yes, we pulled them out, and added a little intro type prose  
… we talked about what to name these documents in one of the issues  
… but like we said last time, these parts just felt a little underspecified (and still do)  

**Wendy Reid:** I started doing a little bit of research into what RS might have implemented TTS, this is ongoing  

**Matt Garrish:** DAISY has some readers that can do TTS, but even when it comes to PLS they don't implement it exactly as per spec  
… about naming, we were going for something that tied it to our spec, but also gave it a 1.0 version number  

**Ben Schroeter:** VitalSource has TTS, but not sure if they use SSML and PLS  

**Brady Duga:** same with us, but we just use OS level TTS functionality  

</details>
