### ISSUE TITLE
TTS example and chinese

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#1716]
[Example 4](https://w3c.github.io/epub-specs/epub33/tts/#example-4) includes the following reference to a pronunciation lexicon:

```
<link rel="pronunciation" type="application/pls+xml" hreflang="zh" href="../speech/zh.pls"/>
```

I wonder whether that is correct, or at least a judicious example. “zh” stands for “Chinese”, but are we sure that this really refers to one specific Chinese language, i.e., mandarin? After all, _we are talking about a pronunciation lexicon_, so we should be really careful to be crystal clear about this. The alternative may be to use ”zh-cmn” for Mandarin, or “zh-yue” for Cantonese...

@xfq or @r12a could tell me if I am overly cautious...

**Comment by r12a** [comment]
Since this is language, rather than writing, i'd agree you'd want to be fairly specific here.  A Mandarin and a Cantonese lexicon are not the same thing, so you'd want to refer to them appropriately.

Rather than 'zh-cmn', though, you should use just 'cmn'.  See the notes at https://r12a.github.io/app-subtags/?lookup=cmn and https://r12a.github.io/app-subtags/?lookup=yue.

**Comment by iherman** [comment]
Thanks @r12a. I have created a PR (#1719) using 'cmn'
