### ISSUE TITLE
[EPUB 3.3] [suggestion] Repetition in the explanation of Media Overlay?

### ISSUE THREAD

**Issue by gregoriopellegrino** [w3c/epub-specs#1737]
It seems to me that similar concepts are repeated in these three sections, perhaps it may make sense to revise them to avoid repetition? Or are they functionals to different types of users who will need to read the specifications? 

- https://www.w3.org/TR/epub-33/#sec-overlay-doc-create
- https://www.w3.org/TR/epub-33/#sec-media-overlays
- https://www.w3.org/TR/epub-33/#sec-media-overlays-structure

**Comment by iherman** [comment]
I am not sure. §7 then §7.3 and then §7.3.2.1 go into increasing details of the terms, with §7 being very general (and non-normative) to §7.3.2.1 as fully normative. There are overlaps but I think it makes it easier for the reader to comprehend what is happening. Unless there are contradictory statements (which I have not seen so far) I would prefer, for the sake of the first-time reader, to leave it as is (though being a bit verbose).

**Comment by mattgarrish** [comment]
Ya, media overlays takes a different approach than the package document, but I don't think it's a bad thing. There's arguably some redundancy between having element definitions and a structure section, but it's easier to understand the structure when it's written about in a single section than to try and read the element definitions to grasp how the elements fit together (especially since the element definitions can't be easily organized to make a hierarchy).

**Comment by iherman** [comment]
I guess this could be closed now...

**Comment by gregoriopellegrino** [comment]
Fine for me, thanks
