### ISSUE TITLE
[EPUB 3.3] [suggestion] List epub:type values in tables?

### ISSUE THREAD

**Issue by gregoriopellegrino** [w3c/epub-specs#1741]
Maybe the section [D.8 Structural Semantics Vocabulary](https://www.w3.org/TR/epub-33/#structure-vocab) could be rendered as a table so it's more compact?

**Comment by mattgarrish** [comment]
I agree from a consistency standpoint, as the other property definitions all use tables. The problem is there are something like 80+ terms in the structure vocabulary.

If we convert to tables and add sections around each term, our table of contents is going to get massively bloated. If we convert to tables and don't add a section for each, it'll be a lot more difficult to find the definition you're after using an AT (you'd have to move table to table and read into each).

That's why I left them in their original definition list.

**Comment by iherman** [comment]
@gregoriopellegrino would you close this if you are satisfied with the answer?

**Comment by gregoriopellegrino** [comment]
Sure, thanks
