### ISSUE TITLE
Explain the purpose of the landmarks nav

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#1761]
As raised on the mailing list by @johnfoliot, the purpose of the landmarks nav and what links authors are supposed to add to it is not very clear in the specification. There is also little and inconsistent use of landmarks in reading systems.

To try and remediate some of the confusion problems for authors, we may want to look at:

- clarifying that the landmarks must be a flat list of entries (no nested lists)
- providing some guidance about limiting the number of entries for ease of access when presented to users (it's not supposed to be a reproduction of the table of contents)
- providing guidance about the preferred type of entries (e.g., select reference links and front/body/back matter)
- informatively noting that the links may be exposed directly to users, so should have readable labels

Other suggestions welcome.

**Comment by GeorgeKerscher** [comment]
I have heard from college students who said they would love a consistent landmark in a text book  in each chapter that identified what you must learn in this chapter. I have seen this in several textbooks I have reviewed.

**Comment by mattgarrish** [comment]
@GeorgeKerscher A landmark within each chapter might be better expressed using ARIA roles. I'm not sure it would be a good fit for the landmarks nav, as you could have dozens of learning objectives to list depending on how many chapters there are in a textbook.

Another thought might be to add a separate nav element that lists all the learning object sections, sort of like a list of tables or illustrations, since ARIA landmarks don't often get exposed in reading apps.

We'd probably need some input from educational publishers on what is more realistic for them to produce before trying to select a specific option, though.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-08-19-epub#section2) on 2021-08-19

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

### 2. Explain the purpose of the landmarks nav (issue epub-specs#1761)

_See github issue [#1761](https://github.com/w3c/epub-specs/issues/1761)._



**Dave Cramer:** explain the purpose of the landmarks nav  
… I don't think I want to have this discussion without Matt and Brady  
… and with no representatives of the a11y activity  
… I would propose we postpone this discussion  
… We don't have the right people in the virtual room for this one  

**Shinya Takami (高見真也):** Kadokawa uses landmarks for our EPUB files  

**Dave Cramer:** We use it minimally  
… mainly to provide a link for the TOC  

**Dan Lazin:** A learning opportunity  
… why were landmarks added? What were they meant to do?  
… seems like they conflict  

**Dave Cramer:** My understanding is that they came from the OEB/EPUB2 feature called "guide"  
… there was an original element in the OPF called a guide where you could provide a tour of the highlights of the book  
… signposts  
… pointers into the content that was different from the TOC  
… providing quick references to glossaries or indexes, special features, etc  
… when UI conventions in EPUB hadn't been solidified  
… some RSs have exposed these before in their UI  
… but is happening less and less  
… as EPUB has stabilized and matured  

**Dan Lazin:** This sounds like a widget that has been deprecated  

**Dave Cramer:** I wouldn't argue with that  

**Shinya Takami (高見真也):** In the past, Kindle wasn't able to use the navigation element, so it used this  
… so we used landmarks in place of that  

**Dave Cramer:** We have some homework  
… thanks everyone!  

---


</details>

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-08-27-epub#section1) on 2021-08-27

List of resolutions:

- ***[Resolution No. 1](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-08-27-epub#resolution1):  Clarify the language for landmarks, close issue 1761***

<details><summary><i>View the transcript</i></summary>

### 1. Landmarks Nav 

_See github issue [#1761](https://github.com/w3c/epub-specs/issues/1761)._




**Dave Cramer:** what is the purpose of landmark nav?  

**Matt Garrish:** this is a continuing question. We created it originally to aid RS with hotkeys that go to specific parts of epub, stuff like that.  
… but do RS even use these? And what are authors supposed to put in here?  
… RS couldn't rely on there being specific content in here  
… closest thing to standard is link to start of bodymatter  
… we should provide some guidance, but if this isn't being used, then should we acknowledge that it isn't being used? Probably can't deprecate because some epubs already use it?  

**Dan Lazin:** does that disagree with the explanation at the last meeting, which said that we've had landmark since epub2?  

**Matt Garrish:** i think dauwhe was getting at guides, which were kind of like a tour of the content. A little different.  

**Dan Lazin:** if this feature hasn't been adopted widely by this point, it sounds like the sort of thing that ought to be deprecated  

**Brady Duga:** i think tours and guides were two different things, but I hesitate to say that its not being used. It's just being used for a specific thing: Finding the start of bodymatter.  
… and its used for that purpose widely  
… would be odd to deprecate it in that case  

**George Kerscher:** screenreaders have had keys that go to landmarks, which has been useful  
… i've heard from students when there are landmarks in each chapter that provide an overview of said chapter  
… so i don't think depreciation is appropriate, but i don't think we need to mandate that RS have specific navigation feature for them  

**Dave Cramer:** are these things implemented in RS based on landmark?  

**George Kerscher:** as long as there's a landmark in the DOM than the screenreader can go to it  

**Dave Cramer:** we might be using "landmark" to refer to two different things?  

**George Kerscher:** Referring to ARIA landmark here  

**Tzviya Siegman:** right, ARIA landmarks are a different thing. And this has lead to confusion over the years  
… re. difference between guide and landmark. In epub2 guide was introduced. Guide is still widely used, and relatively short: toc, begin of content, index. Something like that.  
… but some books are starting to use it to duplicate toc, which makes it less useful  
… i would hesitate to deprecate entirely, but maybe offer guidance to make landmark more useful  

> *Avneesh Singh:* +1 for not deprecating landmark. we should provide some guidance.

**Matt Garrish:** in my issue i was trying to get at this, i.e. clarifying some things about landmark. And in addition maybe say that people are mainly using it to identify start of content  
… this could head people off before they get confused  

**Hadrien Gardeur:** i think historically we have bad tendency to add more and more lists. For future versions of epub, we probably need less of these. Put some of this information in reading order, e.g. spine.  

**Dave Cramer:** Identifying the point where people would start reading is valuable for the reader, but what is the best way to accomplish that?  

**Dan Lazin:** my interpretation is that deprecating something already used doesn't mean that the thing is going away immediately  
… it means we're leaving this, and there is spotty implementation  

> *Dave Cramer:* [https://w3c.github.io/epub-specs/epub33/core/#deprecated](https://w3c.github.io/epub-specs/epub33/core/#deprecated)

**Dan Lazin:** if you are new RS or author, it tells you this is not high on your list of features  

**Gregorio Pellegrino:** another use case that I know of is being able to jump to the in-book toc  
… i.e. not the nav toc  

**Matt Garrish:** if we give some guidance on what works, we have at least a basis for starting over. Maybe say at least put toc and start of content.  
… and dlazin is correct about definition of deprecation from spec perspective, but we're also concerned about the practical implications of maybe causing books to get flagged in validation, etc.  

**Avneesh Singh:** coming back to main principles in charter, we have backwards compat clause  

> *Murata Makoto:* +1

**Avneesh Singh:** i would say there is some worry about deciding to deprecate today. Safer to make more of these types of potentially breaking changes in future version of spec  

**Brady Duga:** deprecation says this is not the recommended way of doing the thing you want to do. But this IS the way of pointing to the start of content etc.  
… and it is the recommended way, in fact.  
… and maybe we can return to this and set out a different way to do it in the future.  
… but for now, I'm very much against deprecation  

**Dave Cramer:** i'm with duga and avneeshsingh. I think we should follow original suggestion and clarify what this is for and what it does work for.  
… not a new toc, or a completely different way of traversing the content  
… maybe all that is needed for now is some editorial work  
… does that seem reasonable?  

**Brady Duga:** yes  

> *Murata Makoto:* Good to me.

> **Proposed resolution: Clarify the language for landmarks, close issue 1761** *(Wendy Reid)*

> *Deborah Kaplan:* +1

> *Tzviya Siegman:* +1

> *Dave Cramer:* +1

> *Toshiaki Koike:* +1

> *Brady Duga:* +1

> *Matt Garrish:* +1

> *Dan Lazin:* +1

> *Avneesh Singh:* +1

> *Gregorio Pellegrino:* +1

> *Masakazu Kitahara:* +1

> *Matthew Chan:* +1

> *Murata Makoto:* +1

> *Wendy Reid:* +1

> *Bill Kasdorf:* +1

> *Ben Schroeter:* +1

> ***Resolution #1: Clarify the language for landmarks, close issue 1761***

</details>
