### ISSUE TITLE
[EPUB 3.3 RS] [suggestion] Metadata lang

### ISSUE THREAD

**Issue by gregoriopellegrino** [w3c/epub-specs#1773]
I think the [metadata section](https://www.w3.org/TR/epub-rs-33/#sec-pkg-doc-metadata) should say that each metadata element can have an `xml:lang` attribute and that this information should be honored when the metadata is shown to the user (e.g. in the bookshelf view of the application).

**Comment by mattgarrish** [comment]
How would a reading system honour the metadata for display?

Even how to use it for TTS would be complicated to enforce, as then you get into whether the reading system supports TTS or the specified language.

**Comment by gregoriopellegrino** [comment]
> How would a reading system honour the metadata for display?

For example, when Reading Systems extract the book title to display it in the UI (in the bookshelf), they should set the label language in the User Interface to match that of the metadata (where possible). I have the impression that most Reading Systems show the metadata content, regardless of the language.

For example in iOS: https://developer.apple.com/documentation/objectivec/nsobject/1615192-accessibilitylanguage

**Comment by mattgarrish** [comment]
> I have the impression that most Reading Systems show the metadata content, regardless of the language.

Right, this is what I'm not sure I understand. Visually it doesn't matter what language you specify, so I was reacting to how it would effect what is shown.

The reference you cite is for ultimately voicing the text, which is getting us deeper into how bookshelves are constructed and interacted with. The reading system could expose the language, for example, but the AT may not do anything with the information.

I'm not arguing that it doesn't make sense, but I'm not sure what testable requirement we could list. I also wonder if maybe this belongs in the TTS note rather than the RS specification.

**Comment by gregoriopellegrino** [comment]
> The reference you cite is for ultimately voicing the text, which is getting us deeper into how bookshelves are constructed and interacted with. The reading system could expose the language, for example, but the AT may not do anything with the information.

Right, but if the reading system doesn't expose the language, the AT can never get the information.

> I'm not arguing that it doesn't make sense, but I'm not sure what testable requirement we could list. I also wonder if maybe this belongs in the TTS note rather than the RS specification.

On that I don't know, the TTS note seems to me to relate to the content of the publication (targeting content producers), rather than the metadata.

**Comment by iherman** [comment]
> Right, this is what I'm not sure I understand. Visually it doesn't matter what language you specify, so I was reacting to how it would effect what is shown.

In an ideal world, it _should_ matter. There may be typesetting/formatting choices that are language specific, even in cases the same fonts are used. Of course, we are not living in an ideal world, meaning that most Reading Systems indeed ignore those differences (I presume).

---

An example from the top of my head. In French, it is acceptable to drop an accent from a character when capitalized. I.e., the form "Elément" instead of "Élément" is perfectly fine in practice, although the correct spelling, if not capitalized, "élément". On the other hand, accents _must_ always be kept in Hungarian, even if capitalized (otherwise the word may be misunderstood).

**Comment by mattgarrish** [comment]
> There may be typesetting/formatting choices that are language specific, even in cases the same fonts are used.

It sounds like we're straying into problems that don't have real-world precedent, though. We're moving beyond simply displaying what has been authored into rewriting it, and whether the rewritten form is still meaningful at a per-language level.

**Comment by iherman** [comment]
> > There may be typesetting/formatting choices that are language specific, even in cases the same fonts are used.
> 
> It sounds like we're straying into problems that don't have real-world precedent, though. We're moving beyond simply displaying what has been authored into rewriting it, and whether the rewritten form is still meaningful at a per-language level.

I see your point...

**Comment by gregoriopellegrino** [comment]
Maybe I didn't understand: in my case (associating the language to the title label shown in the UI) it seems to me that there is no rewriting or reworking of the metadata by the Reading System. The `xml:lang` attribute can be present (if inserted by the EPUB creator) and we suggest the reading solutions to honor it.

**Comment by dauwhe** [comment]
We do [already say](https://www.w3.org/TR/epub-rs-33/#sec-epub-rs-i18n):

> A Reading System MUST process, for all Publication Resources, the attributes that set the primary language for the documents' contents, when applicable. This includes:
> * the xml:lang attribute for all XML documents like the Package Document or the Media Overlay Document [EPUB-33].
> * the xml:lang and lang attributes for XHTML [HTML] or SVG [SVG].

**Comment by mattgarrish** [comment]
> The `xml:lang` attribute can be present (if inserted by the EPUB creator) and we suggest the reading solutions to honor it.

But what has to be honored? There isn't a specific requirement yet on what to do with the language even assuming it can be retained in the bookshelf interface.

That's why I was asking if perhaps you intended this for voicing rather than visual rendering. In that case, we might be able to say that the language of the metadata should be used when rendering the text in a TTS engine or exposed to the platform accessibility APIs.

In that case, we might also consider expanding this bullet in the accessibility section:

> Bookshelf — Ensure that the process for accessing and opening the user's content is accessible (e.g., not relying on visual-only display like cover images).

to give some more detail, since fully describing reading system accessibility is probably not feasible in this revision.

**Comment by iherman** [comment]
> We do [already say](https://www.w3.org/TR/epub-rs-33/#sec-epub-rs-i18n):
> 
> > A Reading System MUST process, for all Publication Resources, the attributes that set the primary language for the documents' contents, when applicable. This includes:
> > 
> > * the xml:lang attribute for all XML documents like the Package Document or the Media Overlay Document [EPUB-33].
> > * the xml:lang and lang attributes for XHTML [HTML] or SVG [SVG].

Good point, @dauwhe. I am not sure that it is worth repeating essentially the same things somewhere else. (In some sense it is harmful in a spec, it is good, if possible, to keep to one reference for a given feature.)

**Comment by gregoriopellegrino** [comment]
To my reading (I'm not native-English) when I read "documents' contents" I don't think of metadata in OPF, but the actual content of the book shown to the user (HTML, SVG) :)

I understand now, thank you.

> > Bookshelf — Ensure that the process for accessing and opening the user's content is accessible (e.g., not relying on visual-only display like cover images).
> 
> to give some more detail, since fully describing reading system accessibility is probably not feasible in this revision.

+1 - If we can add a sentence at this point I think it would help.
