### ISSUE TITLE
[EPUB 3.3 RS] [question] Small difference between the XHTML Content Documents section and the SVG Content Documents section

### ISSUE THREAD

**Issue by gregoriopellegrino** [w3c/epub-specs#1774]
The [SVG Content Documents section](https://www.w3.org/TR/epub-rs-33/#sec-svg) explicitly says:

> SHOULD support user selection and searching of text within SVG elements

While the[ XHTML Content Documents](https://www.w3.org/TR/epub-rs-33/#sec-xhtml) section makes no mention of searching for content.

Maybe it makes sense to align them?

**Comment by OriKuttner** [comment]
I agree, we should align them.
It is more important to search XHTML document than SVG document.

-- 
Ori Idan CEO Helicon Books
http://www.heliconbooks.com

**Comment by dauwhe** [comment]
Are there reading systems that don't offer search because it's. not mentioned in the EPUB spec?

**Comment by OriKuttner** [comment]
I don't know if there are RS's that don't offer it because it is not
mentioned but that does not mean we should not mention it.

**Comment by mattgarrish** [comment]
I wonder whether we shouldn't have the SVG bullet at all. We've gone beyond supporting SVG into requirements on the UI, which we typically don't do.

If it's just to remind devs that SVGs aren't always pure images, maybe it could be a note rather than a recommendation?

**Comment by iherman** [comment]
> I wonder whether we shouldn't have the SVG bullet at all. We've gone beyond supporting SVG into requirements on the UI, which we typically don't do.
> 
> If it's just to remind devs that SVGs aren't always pure images, maybe it could be a note rather than a recommendation?

+1 to that. I was not sure why this statement was in the spec in the first place, and you have just given the answer... But that is the type of statement that should be in a note rather than the specification text.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-08-27-epub#section2) on 2021-08-27

List of resolutions:

- ***[Resolution No. 2](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-08-27-epub#resolution2):  Remove the search point from the SVG section, close issue 1774***

<details><summary><i>View the transcript</i></summary>

### 2. XHTML and SVG 

_See github issue [#1774](https://github.com/w3c/epub-specs/issues/1774)._




**Dave Cramer:** apparently the SVG content doc section says RS should support searching of text, but the XHTML content doc section doesn't mention searching  
… i see the point, but I'm also concerned that in general we try to avoid describing how RS should present epub to users  
… my preference is to take out the line about SVG  

**Matt Garrish:** I don't think we mandate certain UI features in any other point of spec. I agree on removing this. We leave this to the developers to figure out.  

> *Tzviya Siegman:* +1 to mgarrish

**Matt Garrish:** maybe just a note reminding RS people that SVGs can contain text  

**Brady Duga:** fine with removing. Alternative would be to say that any text interactions that RS supports with XHTML should also be supported for SVG text. A more vague way of doing what we want.  

**Wendy Reid:** gpellegrino which would you prefer, since it is your issue?  

**Gregorio Pellegrino:** no position as it doesn't strongly impact a11y. I just wanted to point out this discrepancy.  

**Dave Cramer:** I have no objection to duga language. But probably more simple to just remove SVG bullet. Hoping that developers already know that SVG can contain text. Not sure that our reminder will change their minds about what UI feature to put in their RS.  

> **Proposed resolution: Remove the search point from the SVG section, close issue 1774** *(Wendy Reid)*

> *Ben Schroeter:* +1

> *Brady Duga:* +1

> *Tzviya Siegman:* +1

> *Deborah Kaplan:* +0

> *Gregorio Pellegrino:* +1

> *Toshiaki Koike:* +1

> *Matthew Chan:* +1

> *Wendy Reid:* +1

> *Dan Lazin:* +1

> *Matt Garrish:* +!

> *Dave Cramer:* +1

> *Masakazu Kitahara:* +1

> *Murata Makoto:* +1

> *Bill Kasdorf:* +1

> ***Resolution #2: Remove the search point from the SVG section, close issue 1774***

</details>
