### ISSUE TITLE
[EPUB 3.3 RS] [suggestion] Enabling zooming FXL EPUBs

### ISSUE THREAD

**Issue by gregoriopellegrino** [w3c/epub-specs#1776]
As discussed in the EPUB FXL accessibility task force perhaps it may make sense to point out to implementers that for accessibility it is useful to allow zooming of content in EPUB FXL. Normally this functionality is available on mobile reading solutions, but not on desktop ones.

https://www.w3.org/TR/epub-rs-33/#sec-fixed-layouts

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-08-27-epub#section4) on 2021-08-27

List of resolutions:

- ***[Resolution No. 4](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-08-27-epub#resolution4):  Add a note to the accessibility section of the reading systems document, add mention in FXL accessibility note, close issue 1776***

<details><summary><i>View the transcript</i></summary>

### 4. Enabling zoom in FXL EPUBs 

_See github issue [#1776](https://github.com/w3c/epub-specs/issues/1776)._




**Dave Cramer:** should we point out that zooming is important for a11y, even in the context of FXL epub?  

**Gregorio Pellegrino:** my idea is to add SHOULD statement. "FXL SHOULD enable zooming"  

**Hadrien Gardeur:** what makes it difficult is the fact that you can have spreads in FXL  
… could be two iframes or two webviews. This makes it difficult to zoom in a good way because you have those two things side by side  
… but not saying that we shouldn't do it  

**Dave Cramer:** right, so what would happen if you try to zoom in on the boundary between two documents?  

**Matt Garrish:** aren't we getting into UI requirements again? Not sure if this is always feasible.  
… maybe this is something we could just point out. Or move this over to the FXL a11y doc rather that in the core spec.  

**Dave Cramer:** do we know of existing RS that allow for zoom in FXL  

**Gregorio Pellegrino:** yes, all the mobile RS  

**Matt Garrish:** but that's a feature of the mobile RS  

**Brady Duga:** that's quite a bit of implementation on the mobile side, its not free  
… but on the desktop side its a bit easier  
… and yes, spreads add complication  

**Wendy Reid:** almost the same comment as duga. Sometimes you see it implemented as a slider rather than pinch to zoom  
… uncomfortable with adding this to spec because we don't talk about UI or UX affordances  
… not sure we want to get into that territory  
… but we can add this as a recommendation in the FXL a11y doc  

**Avneesh Singh:** i think this isn't something for the FXL content side of things. Maybe we can add statement on RS side encouraging the provision of zoom for FXL content. But not make this a normative statement.  

**Dave Cramer:** getting the sense that a lot of RS already allow this. And historically we don't describe UX features in spec. I would note this in FXL a11y document rather than epub spec itself.  

**Gregorio Pellegrino:** my small concern is that the FXL note is more for authors than RS, so the suggestion may get ignored  

**Dave Cramer:** are there implementations of FXL epub that don't allow zooming?  

**Gregorio Pellegrino:** yes, on desktop some don't allow this  

**Dave Cramer:** are we okay with adding something non-normative to RS spec?  

> *Deborah Kaplan:* mgarrish++

**Matt Garrish:** can we add this to the a11y section? Just a suggestion to provide the option to allow user to zoom in  

> *Avneesh Singh:* +1 to genrral statement in a11y section of RS

**Gregorio Pellegrino:** maybe link to FXL best practices document?  

> *Deborah Kaplan:* +1 as well, ditto mgarrish and avneesh

**Matt Garrish:** yes, once we get to FPWD we can link to it  

> **Proposed resolution: Add a note to the accessibility section of the reading systems document, add mention in FXL accessibility note, close issue 1776** *(Wendy Reid)*

> *Gregorio Pellegrino:* +1

> *Dave Cramer:* +1

> *Matthew Chan:* +1

> *Wendy Reid:* +1

> *Matt Garrish:* +1

> *Deborah Kaplan:* +1

> *Tzviya Siegman:* +1

> *Toshiaki Koike:* +1

> *Masakazu Kitahara:* +1

> *Ben Schroeter:* +1

> *Dan Lazin:* +1

> *Bill Kasdorf:* +1

> *Brady Duga:* +1

> ***Resolution #4: Add a note to the accessibility section of the reading systems document, add mention in FXL accessibility note, close issue 1776***

> *Dave Cramer:* RRSAgent: bye

---


</details>
