### ISSUE TITLE
Assign multiple roles to one person

### ISSUE THREAD

**Issue by spajak** [w3c/epub-specs#1782]
Sometimes the same person has more than one role.

I would like to write it just like this, using comma:

```xml
<dc:contributor id="producer">Sebastian Pająk</dc:contributor>
    <meta refines="#producer" property="role" scheme="marc:relators">role-1, role-2, role-3</meta>
```

But I guess the above is not valid; one has to repeat the same contributor for every role. It would be nice to simplify this to just one contributor+meta(s) tags.

**Comment by dauwhe** [comment]
See also #1583 and #1129 for related discussions

**Comment by iherman** [comment]
What this means is that, I believe, the following is fine:

```
<dc:contributor id="producer">Sebastian Pająk</dc:contributor>
    <meta refines="#producer" property="role" scheme="marc:relators">role-1</meta>
    <meta refines="#producer" property="role" scheme="marc:relators">role-2</meta>
    <meta refines="#producer" property="role" scheme="marc:relators">role-3</meta>
```

ie, if I understand the remark "one has to repeat the same contributor for every role" then this isn't correct.

Using the comma separated list syntax would mean to formally specify a micro-syntax in the spec which, though not complicated, is an unnecessary extra complexity on the spec (which is already complex enough).

**Comment by mattgarrish** [comment]
> "one has to repeat the same contributor for every role" then this isn't correct

Not after this revision, no. We updated the rules in the earlier issues @dauwhe has pointed to.

> Using the comma separated list syntax would mean to formally specify a micro-syntax in the spec

Right, this is why we avoided this approach. We can specify a syntax, but then people just do what they want anyway, which leaves it to reading systems to have to make sense of the input.

**Comment by dauwhe** [comment]
Are there reading systems that display contributor roles?

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-09-16-epub#section3) on 2021-09-16

List of resolutions:

- ***[Resolution No. 2](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-09-16-epub#resolution2):  Close issue 1782 with maximum prejudice (won't fix)***

<details><summary><i>View the transcript</i></summary>

### 3. Multiple Roles 

_See github issue [#1782](https://github.com/w3c/epub-specs/issues/1782)._




**Dave Cramer:** about package metadata. someone proposed that we be able to assign multiple roles to a person using a comma separate string of different roles  
… but we don't think we want to get involved in parsing  
… but you can already assign multiple roles to a person in the current spec  
… and i'm not aware of many RS that even present this information to user  
… so i would close this issue  

> **Proposed resolution: Close issue 1782 as won't fix. we** *(Wendy Reid)*

**Matt Garrish:** agreed. If we come up with a micro-syntax for the meta tag that could open up a bunch of issues. The one property per tag is a simple system that works.  

> **Proposed resolution: Close issue 1782 with maximum prejudice (won't fix)** *(Wendy Reid)*

> *Dave Cramer:* +1

> *Brady Duga:* +1

> *Shinya Takami (高見真也):* +1

> *Matt Garrish:* +1

> *Matthew Chan:* +1

> *Toshiaki Koike:* +1

> *Wendy Reid:* +1

> ***Resolution #2: Close issue 1782 with maximum prejudice (won't fix)***

</details>
