### ISSUE TITLE
Should EPUB Accessibility 1.1 recommend conformance to WCAG at "Level AA or its equivalent"?

### ISSUE THREAD

**Issue by jasonjgw** [w3c/epub-specs#1800]
EPUB Accessibility 1.1, as drafted, requires conformance to Level A of WCAG 2.0, but RECOMMENDS conformance to the latest version of WCAG at least at Level AA.

It appears likely that WCAG 3.0 will depart from the three-level scheme (A, AA and AAA, respectively) of WCAG 2.x. The exact details of the approach to be taken remain fluid, as WCAG 3 is in early draft form.

EPUB Accessibility could explicitly restrict itself to WCAG 2.x (recognizing the need for revision upon publication of a WCAG 3 Recommendation), , or slightly broaden the requirement to "Level AA or its equivalent", under the assumption that WCAG 3.x will specify a rough equivalence of one of its conformance options with WCAG 2.x level AA. The latter approach would offer greater forward compatibility, but it depends on the assumption that an equivalence is defined in the future between WCAG 2.x Level AA and a given conformance option of WCAG 3.

**Comment by mattgarrish** [comment]
> EPUB Accessibility could explicitly restrict itself to WCAG 2.x

That's implicitly what the section is trying to do, but I agree it's not fully clear from the description. The link is to the latest version of WCAG 2, not to the latest version of WCAG (which would be /TR/WCAG/).

I think we can make this more explicit by saying WCAG 2 in the sentence rather than relying solely on the link.

We decided earlier in the revision that we could only address WCAG 2 in this revision as until there is a stable WCAG 3 there's no predicting what we would require. Whenever that specification arrives, it will require another update.
