### ISSUE TITLE
Determination of the height and width of the ICB for SVG documents in the spine

### ISSUE THREAD

**Issue by GoogleCodeExporter** [w3c/epub-specs#463]
```
Currently, the EPUB 3.0.1 spec states  that size of the SVG ICB for a SVG 
document in the spine should be determined from the viewbox element.

http://www.idpf.org/epub/301/spec/epub-contentdocs.html#sec-fxl-rs-conf

Unfortunately, this very unlikely to produce the correct result in most cases.

The right strategy for sizing the (SVG) ICB is
- fetch the height and width from height and width attributes on the SVG 
element itself
- if these are not present, check if the rendition:viewport is available if so, 
use that
- if this fails, use the actual dimensions of the container (I.e. The window 
frame, etc.)

I believe this last case (#3) represents malformed content that should be 
flagged as an error by EPUBCheck. One problem is that for desktop 
implementations the aspect ratio of the window frame is unlikely to be what the 
author wanted. BTW, in case 3 the RS should also emit an error so applications 
can complain/explain to the user.

I DO NOT believe the viewbox should be used in ANY case. The SVG WG never 
intended for it to be used for that purpose and authoring tools definitely do 
NOT export it with that expectation. The whole point of the viewbox is to map 
the content into a container. The xmin, ymin is the origin of the content  in 
USER SPACE (I.e. The bbox of the portion of the user space that has been 
marked) and the width, height are the dimensions in USER SPACE of the content. 
This way the SVG can be dropped into any container and is automatically scaled 
to fit. This allows the content to be used as whole-page content, floated 
illustrations, etc.

Adobe Illustrator was designed and implemented this way after we did a lot of 
consultation with designers and publishers.  Inkscape also uses this strategy.  
So net net, the viewbox is very unlikely to result in what the author intended.
```

Original issue reported on code.google.com by `rkwri...@geofx.com` on 6 Aug 2014 at 12:19

**Comment by GarthConboy** [comment]
Proposed resolution:  Ric to provide.  Likely order: viewbox, hight/width, maybe window

**Comment by rkwright** [comment]
After a discussion in the WG on June 7 and consulting with some outside experts (notably Peter Sorotokin), I have concluded that using viewBox as the first choice for the ICB is probably the best way – or at least not a problem.  However, I do think we need to clarify what Reading Systems should do, especially in the case where the author did not provide a viewBox OR a height/width.

So, the present verbiage is:

```
2.5.4.2 Expressing ICB Dimensions in SVG
For SVG Content Documents, the ICB dimensions must be expressed using the viewBox 
attribute [SVG].
```

Which we might expand to something like:

```
2.5.4.2  Expressing ICB Dimensions in SVG

For SVG Content Documents (i.e. where the SVG content is not enclosed in a parent HTML 
document), the ICB’s aspect ratio SHOULD be derived from the viewBox attribute, if present.  
As the SVG spec makes the presence of the viewBox optional, if it is missing, the height 
and width attributes  should be used instead.  If they are also not present, then the reading 
system should use the best estimate of the expected aspect ratio, which would typically 
be the bounds of the window into which the content is being rendered.  However, this 
aspect ratio may often not to be what the author expected, so authors are strongly 
encouraged to provide the viewBox or, at least, the expected height and width.
```

Note that EPUB documents with pages wholly in SVG, while allowed, are extremely rare in practice.

I also wonder if we should clarify that due to the wide range of display sizes and resolutions, the dimensions of the ICB are not normally used by Reading Systems as the literal size of the rendered page, but instead are used to compute the desired aspect ratio of the page?

**Comment by mattgarrish** [comment]
Could we condense to:

For SVG Content Documents referenced from the spine, the ICB's aspect ratio SHOULD be derived from the viewBox attribute, if present; otherwise, the height and width attributes SHOULD be used.  If neither is present, Reading Systems SHOULD use the best estimate of the expected aspect ratio, which is typically the bounds of the window into which the content is being rendered.

NOTE
Authors are strongly encouraged to provide the viewBox or height and width attributes, as the Reading System determined aspect ratio is typically device-dependent and can negatively affect the rendering.

**Comment by rkwright** [comment]
That's fine with me.  Not sure it is all that more "condensed" but it is better wording, IMO.

**Comment by GarthConboy** [comment]
Proposed resolution: new wording two comments above.

**Comment by iherman** [comment]
+1 to @mattgarrish's formulation in https://github.com/IDPF/epub-revision/issues/463#issuecomment-224992097

**Comment by mattgarrish** [comment]
Prose updated in commit:
https://github.com/IDPF/epub-revision/commit/c1b4ed1c24b5964e4bc5d9dab6671cf64e3632aa

Change can be reviewed at:
https://rawgit.com/IDPF/epub-revision/master/build/31/spec/epub-contentdocs.html#sec-fxl-icb-svg

Please review and close if no further changes are needed.

**Comment by murata2makoto** [comment]
Matt, is the URI in the above comment correct?  Or, is it now obsolete?

**Comment by mattgarrish** [comment]
No, I had to change the build path because the FXL vocabulary we split out from the specification has a non-standard path (below /epub). If you find some broken links like this, just add /epub after /build, so:

https://rawgit.com/IDPF/epub-revision/master/build/epub/31/spec/epub-contentdocs.html#sec-fxl-icb-svg

**Comment by mattgarrish** [comment]
Correcting my previous remark, the URL above is correct again.

**Comment by GarthConboy** [comment]
LGTM
