### ISSUE TITLE
Access to the epubReadingSystem object

### ISSUE THREAD

**Issue by GoogleCodeExporter** [w3c/epub-specs#474]
```
The widgets group has noticed that the Content Documents definition for the 
epubReadingSystem object does not indicate how all scriptable components get 
access to the object, particularly if they are embedded and in separate 
domains. Only when all components are in the same domain can the object always 
be reached.

The result is that they're looking at passing the object in via the messaging 
protocol in order to ensure the info is available, but this solution would then 
potentially make scripting dependent on the model they define.

```

Original issue reported on code.google.com by `mgarrish` on 22 Oct 2014 at 6:23

**Comment by danielweck** [comment]
Irrespective of scriptable component iframes, here is my viewpoint as a reading system implementer (Readium):

Although the `navigator.epubReadingSystem` object is meant to be shared across all browser "windows" (i.e. reading system iframes, such as top-level HTML spine item containers, and child widgets), the application code conceptually "owns" the object: creates it at startup, populates it with static values (i.e. RS name and version, + read-only hasFeature() accessor method), injects it into every loading iframe (because by default the supposedly-global `navigator` object properties are actually _not_ automatically available to newly-created `window` contexts), and responds to its API calls (granted, right now the API is very limited, but there has been proposals to extend it).

That last point is critical: a `navigator.epubReadingSystem` object that is designed to act as a bridge from iframes (EPUB content) to some RS-specific behaviour (e.g. read and/or write API methods), implies some sort of consistent internal state, effectively shared / reflected across all iframes, even if hosted from different domains. Because of possible cross-origin restrictions, this model does not seem to scale very well, at least on paper. In practice, Readium manages to inject the "live" `navigator.epubReadingSystem` object into every loading iframe, but this does not feel like the "correct way to do things".

It would be easier to create a _copy_ of the RS object into each iframe, and that would be fine assuming the object's data is just static / immutable values (which, in its current form at EPUB v3, pretty much is). But in the case of API function calls that are meant to alter some kind of dynamic internal RS state, the object has to either be a live shared instance, or ... perhaps the said API could consist in convenient wrappers for `postMessage()` calls targeting the RS application's `window`. Side note: `window.top` cannot be assumed to be the reading system, because of iframe-embedding of the RS inside web pages ... so the target RS `window` would have to be determined via a different mean. `window.parent` is not adequate either, as for widgets this would be the hosting EPUB HTML, not the app.

Such `postMessage()` communication protocol between the event-listening app context, and the event-emitting iframes, should be adequate for most APIs (even with the text-only restrictions of the event payload, i.e. no passing of real object instance other than special large binary array references). In fact, this protocol would be a matter of "implementation detail", and the specification would just ensure to define `navigator.epubReadingSystem` APIs that do not require passing object instances (just JSON-like text-only payloads). Speaking of which: http://www.idpf.org/epub/301/spec/epub-contentdocs.html#app-epubReadingSystem

Sorry for the long-winded comment, but I hope this helps formulating the problem more precisely for this issue (which is currently vaguely entitled "Access to the epubReadingSystem object").

Dan

**Comment by danielweck** [comment]
Additional information to my message above, ongoing discussion in the Readium issue tracker (static `navigator.epubReadingSystem` object clones, versus "live" shared object / consistent internal state available across all spine items and widget iframes):
https://github.com/readium/SDKLauncher-Android/issues/52#issuecomment-95485428

**Comment by danielweck** [comment]
@mattgarrish can you please assign me to this? (as agreed on today's concall)

**Comment by danielweck** [comment]
Shared Google doc:
https://docs.google.com/document/d/1aLPwp6bvIki5LHz2yWhypqzajr9jR8CyKqTlpzqUwgs

**Comment by danielweck** [comment]
@bduga 's continued discussion in mailing list:
https://groups.google.com/forum/#!topic/epub-working-group/WsT2G__tMSQ

**Comment by danielweck** [comment]
@mattgarrish updated the 3.1 draft with my proposal:
https://rawgit.com/IDPF/epub-revision/master/build/31/spec/epub-contentdocs.html#app-ers-desc

**Comment by danielweck** [comment]
I have just double-checked the latest draft, it looks good to me:
https://rawgit.com/IDPF/epub-revision/master/build/31/spec/epub-contentdocs.html#app-epubReadingSystem
(I believe this issue can be closed)

**Comment by mattgarrish** [comment]
Link to changes is now:
https://rawgit.com/IDPF/epub-revision/master/build/epub/31/spec/epub-contentdocs.html#app-epubReadingSystem
