### ISSUE TITLE
Use of rendition:spread for reflowable spreads

### ISSUE THREAD

**Issue by GoogleCodeExporter** [w3c/epub-specs#499]
```
Can rendition:spread be used to control reflowable documents?

For example, some reading systems will show two panes in the viewport by 
default for reflowable docs, and flow the document into both, typically with a 
user preference to change to one pane. The idea is that rendition:spread can be 
used to force one or two panes, same as it is used to define pages in an fxl 
spread.

The rendition:spread property is currently defined for fxl documents, however, 
so it's not clear that such use is standard for reflowable documents.

```

Original issue reported on code.google.com by `mgarrish` on 25 Feb 2015 at 11:18

**Comment by GarthConboy** [comment]
Conceivably "rendition:spread" could specify author intent for flowing as well as fixed content documents (both meta and itemref).  As the term "syntehtic spread" implies FXL to me, I think we should go for simplicity here, and designate: 

meta "rendition:spread" values indicates desired spread behavior for pre-paginated documents in the rendition.  Similarly the itemref the various "rendition:spead-*" and "*page-spread-*" properties are valid only when applied to pre-paginated content documents.

Proposed resolution: above paragraph.

**Comment by GarthConboy** [comment]
Proposed resolution: no change to spec; properties are not currently limited to pre-paginated -- stay the course.

**Comment by matt-curtis** [comment]
I agree - the exact behavior of spread properties on reflowable content is unclear in the specification. Since the ePub 3 specification allows reflowable content and fixed-layout content to be interspersed in the spine, what specifies the differences in rendering? Additionally, reflowable content may not specify a viewport. What is the expected behavior of a Reading System in such cases? (Apologies if I'm asking this in the wrong place)

**EDIT:**

Lastly, the documentation states: `"When the rendition:viewport property is specified on a meta element with a refines attribute, it indicates the content dimensions apply only to the referenced XHTML or SVG Content Document, overriding the global value (if set)."` Is this true of all refining meta elements, or is `rendition:viewport` a special case? Meaning I could also write `<meta property="rendition:layout" refines="#spineItem-1">pre-paginated</meta>` to indicate that a specific spine item was fixed layout?

**Comment by mattgarrish** [comment]
The only reason rendition:viewport had to be done that way is because the dimensions are a string value, and there isn't an attribute on spine itemref that takes arbitrary strings for overriding the global setting.

The refines attribute is deprecated in 3.1, as is this rendition:viewport property, so the ugliness introduced in 3.0.1 is gone again.

**Comment by matt-curtis** [comment]
Thanks for the reply! That clears up the `rendition:viewport` part. Any insight on reflowable page spread behavior?

**Comment by mattgarrish** [comment]
I can only assume there will be no consistency between reading systems in what content appears in the slots at any stage in the progression, or even in how a reflowable spread is presented, since the spread would have to defined by the reading system (i.e., the spread is whatever one- or two-page layout it uses for reflowable normally).

**Comment by matt-curtis** [comment]
Thought it was something like that. Thanks for answering my questions.
