### ISSUE TITLE
Mapping document required or optional?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [w3c/epub-specs#510]
```
I didn't think it was the case that mapping documents were required, even if 
incredibly useful. The edupub spec also makes this assumption, noting that they 
"should" be included.

The multiple renditions specification does not have a top-level content 
conformance section, however, which implies that all sections are required.

We need to either clarify that mappings are optional, or, if not, remove the 
prose from edupub.

```

Original issue reported on code.google.com by `mgarrish` on 9 Mar 2015 at 11:04

**Comment by danielweck** [comment]
Originally commented by @danielweck
(now subscribed)

**Comment by murata2makoto** [comment]
I also believe that multiple renditions without mapping documents 
are still useful and easier to create than those with mapping documents.

I certainly think that those with mapping documents are better but we 
should not mandate mapping documents.

Matt, could you provide top-level conformance requirements for 
explicitly making mapping documents optional?

**Comment by mattgarrish** [comment]
I've been pondering how we can make the least intrusive change, as I'd like to avoid having to renumber the entire specification to inject a new section just for this.

Since support for metadata and selection attributes is required, would it make sense to instead clarify in the mapping document RS section that support is optional?

For example, we could change the introductory paragraph in 4.3[1] as follows:

EPUB Reading System support for Rendition Mapping Documents is OPTIONAL, but a Reading System MUST meet all of the following criteria if it supports Mapping Documents:

[1] http://www.idpf.org/epub/renditions/multiple/#h.jw18r94dmi13

**Comment by murata2makoto** [comment]
I hope to close this issue in the next teleconf.

**Comment by mattgarrish** [comment]
Proposed text has been integrated.
