### ISSUE TITLE
encryption.xml provides no way to identify DRM scheme used

### ISSUE THREAD

**Issue by jpritchettLA** [w3c/epub-specs#575]
The current definition of encryption.xml in the OCF (Section 2.5.2, http://www.idpf.org/epub/301/spec/epub-ocf.html#sec-container-metainf-encryption.xml) only provides a way of identifying encryption algorithms and keys used to encrypt Publication Resources. However, it may be necessary to understand other aspects of particular DRM protocols to determine whether those Resources can be decrypted. Currently, there is no way for a Reading System to know that a Publication is protected by Brand X DRM except by inferring from other data (e.g., key locations and types)

There should be a standard, clear way of identifying what DRM system/protocol is being used in the publication. One possibility for this is an attribute added to the encryption element. There are probably other solutions to this problem as well.

**Comment by jpritchettLA** [comment]
See also this issue being tracked in Readium SDK for more background and additional ideas for solutions:

https://github.com/readium/readium-sdk/issues/162

**Comment by danielweck** [comment]
Thanks @jpritchettLA for referencing the Readium SDK issue tracker. I will shortly post a separate issue here at `IDPF/epub-revision`, as the problem has now been discussed in depth with several EPUB3 reading systems implementors (support for OCF encryption.xml in the specific context of Readium-LCP, but the problem is agnostic to the actual encryption scheme).

**Comment by danielweck** [comment]
...and - note to self - I think @jpritchettLA is referring to how "Brand X DRM" can be inferred from these two elements in `encryption.xml`: `EncryptionMethod@Algorithm` (e.g. `http://www.w3.org/2001/04/xmlenc#aes256-cbc`) and `RetrievalMethod@URI` (e.g. `drm_license.json#/encryption/key`) + `RetrievalMethod@Type` (e.g. `http://acme.org/drm#EncryptionKey`).

**Comment by danielweck** [comment]
CC @edrlab @mmenu-mantano @clebeaupin @drminside @nleme @TEA-ebook @RemiBauzac @jpbougie
Hello @jpritchettLA, in LCP land, it looks like none of the developers have faced the issue you are referring to, in the sense that the lack of metadata for DRM vendor / brand has not been a cause for concern. If I am not mistaken, some degree of information can be inferred via
`encryption.xml` by `EncryptionMethod@Algorithm` (e.g. `http://www.w3.org/2001/04/xmlenc#aes256-cbc`) and `RetrievalMethod@URI` (e.g. `drm_license.json#/encryption/key`) + `RetrievalMethod@Type` (e.g. `http://acme.org/drm#EncryptionKey`). Would you recommend an additional field? Would that be a MUST / SHOULD / MAY conformance requirement?
Thanks!
Dan

**Comment by thkim2015** [comment]
If we don't consider type of the profiles in the specific DRM, these information could be enough to figure out the DRM.
But profiles of the DRM may make the decision process not easy.
For example, LCP could have at least 2 profiles. One is based on the current specification and the other is with the common secure key. 
How could we differentiate the 2 profiles without referring the profile ID in the license document?

So DRM Inside uses encryption@xs:ID in the encryption.xml, although @xs:ID is not specified in the document, EPUB Open Container Format (OCF) 3.0.1.
But it is very useful to invoke proper Content Module among several DRM solutions according the Id.

> <?xml version="1.0" encoding="UTF-8"?>
> <encryption xmlns="urn:oasis:names:tc:opendocument:xmlns:container"
>          xmlns:xs="http://www.w3.org/2001/XMLSchema" 
>           xs:ID="http://readium.org/lcp/profile-1.0">
>   <xenc:EncryptedData xmlns:xenc="http://www.w3.org/2001/04/xmlenc#">
>     ...

IMO, @xs:ID attribute is required to be MUST for the seamless interoperability.

**Comment by danielweck** [comment]
Thank you @thkim2015 
So, if I understand correctly, strictly-speaking _no change_ in the EPUB3 OCF specification is required, right? Rationale: Readium LCP is one particular DRM scheme based on EPUB's use of `encryption.xml` (etc.), and in this particular context it is very desirable to add the http://www.w3.org/2001/XMLSchema `xs:ID` attribute on the `encryption` root element. We can define this conformance requirement specifically for the LCP ecosystem, that is to say in the profile document. Other DRM schemes may choose to use a different mechanism to provide additional profile-related information / metadata. Does this sound good enough? @jpritchettLA ?

**Comment by jpritchettLA** [comment]
I only submitted this issue in response to Taehyun's feedback, so if he's
happy, I'm happy.

James

On Wed, Mar 23, 2016 at 10:38 AM, Daniel Weck notifications@github.com
wrote:

> Thank you @thkim2015 https://github.com/thkim2015
> So, if I understand correctly, strictly-speaking _no change_ in the EPUB3
> OCF specification is required, right? Rationale: Readium LCP is one
> particular DRM scheme based on EPUB's use of encryption.xml (etc.), and
> in this particular context it is very desirable to add the
> http://www.w3.org/2001/XMLSchema xs:ID attribute on the encryption root
> element. We can define this conformance requirement specifically for the
> LCP ecosystem, that is to say in the profile document. Other DRM schemes
> may choose to use a different mechanism to provide additional
> profile-related information / metadata. Does this sound good enough?
> @jpritchettLA https://github.com/jpritchettLA ?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/IDPF/epub-revision/issues/575#issuecomment-200372866

## 

_James Pritchett_

Leader, Process Redesign and Analysis

---

_Learning Ally™_Together It’s Possible
20 Roszel Road | Princeton, NJ 08540 | Office: 609.243.7608

jPritchett@LearningAlly.org

www.LearningAlly.org http://www.learningally.org/

Join us in building a community that helps blind, visually impaired &
dyslexic students thrive.

Connect with our community: _Facebook_
https://www.facebook.com/LearningAlly.org | _Twitter_
https://twitter.com/Learning_Ally | _LinkedIn_
https://www.linkedin.com/groups?home=&gid=2644842&trk=anet_ug_hm |
_Explore1in5_ http://www.explore1in5.org/ | _Instagram_
https://instagram.com/Learning_Ally/ | _Sign up for our community
newsletter_ https://go.learningally.org/about-learning-ally/stay-in-touch/

Support us: _Donate_
https://go.learningally.org/about-learning-ally/donate/ | _Volunteer_
https://go.learningally.org/about-learning-ally/volunteers/how-you-can-help/

**Comment by danielweck** [comment]
Would the addition of the `xs:ID` attribute result in invalid EPUBs?

The schemas reference:
http://www.idpf.org/epub/301/spec/epub-ocf.html#app-schema-encryption

...points to a W3C note!
https://www.w3.org/TR/2013/NOTE-xmlsec-rngschema-20130411/

The actual specification is:
https://www.w3.org/TR/xmlenc-core1/

The EPUB-Check schema is based on `Lenient-Encryption11-ghc.rnc`, see:

https://github.com/IDPF/epubcheck/blob/master/src/main/resources/com/adobe/epubcheck/schema/30/ocf-encryption-30.rnc

https://github.com/IDPF/epubcheck/tree/master/src/main/resources/com/adobe/epubcheck/schema/30/mod/security

**Comment by danielweck** [comment]
Okay, I EPUB-Checked the IDPF sample "wasteland-otf-obf" using the online validator http://validator.idpf.org

Results:

```
Detected version: EPUB 3.0.1

The following problems were found in wasteland-otf-obf_XS-ID.epub:

ERROR

META-INF/encryption.xml
Error while parsing file 'found attribute "xs:ID", but no attributes allowed here

Validated using EpubCheck version 4.0.1
`
```

**Comment by mattgarrish** [comment]
xs:ID is a datatype for unique identifiers, not an attribute.

@murata0204 is the best person to ask about what you need to do to extend.

**Comment by thkim2015** [comment]
I wonder which specification is used for the validator. In fact, there is no specific defined schema for the **encryption** element, which is a just holder of the xenc:EncryptedData and xenc:EncryptedKey. I think currently there is no rule, which is not allowed to add a new attribute in the encryption element.

EPUB Open Container Format (OCF) 3.0.1 specification describes just as:

> This file is an XML document **_whose root element is encryption_**. The encryption element contains child elements of type EncryptedKey and EncryptedData as defined by [XML ENC Core]. An EncryptedKey element describes each encryption key used in the container, while an EncryptedData element describes each encrypted file. Each EncryptedData element refers to an EncryptedKey element, as described in XML Encryption.

**Comment by danielweck** [comment]
Thanks @mattgarrish 
Maybe we need another kind of `EncryptionProperty` in LCP? (publication-wide, not resource-specific)

**Comment by danielweck** [comment]
@thkim2015 I detailed the schemas in a message above (including EPUB-Check):
https://github.com/IDPF/epub-revision/issues/575#issuecomment-200811446

**Comment by danielweck** [comment]
@thkim2015 direct EPUB-Check schema link: https://github.com/IDPF/epubcheck/blob/master/src/main/resources/com/adobe/epubcheck/schema/30/ocf-encryption-30.rnc

**Comment by danielweck** [comment]
@thkim2015 `xs:ID` is a datatype for Schema, not meant to be used as an attribute name, right? (as raised by @mattgarrish )

**Comment by jpritchettLA** [comment]
Exactly. My memory is that the encryption element has no attributes, and
its contents are completely defined by the XML Encryption schemas. So if we
want to add any attribute to encryption, we have to have a new schema.

James

On Thu, Mar 24, 2016 at 8:51 AM, Taehyun Kim notifications@github.com
wrote:

> I wonder which specification is used for the validator. In fact, there is
> no specific defined schema for the _encryption_ element, which is a just
> holder of the xenc:EncryptedData and xenc:EncryptedKey. I think currently
> there is no rule, which is not allowed to add a new attribute in the
> encryption element.
> 
> EPUB Open Container Format (OCF) 3.0.1 specification describes just as:
> 
> This file is an XML document _whose root element is encryption_. The
> encryption element contains child elements of type EncryptedKey and
> EncryptedData as defined by [XML ENC Core]. An EncryptedKey element
> describes each encryption key used in the container, while an EncryptedData
> element describes each encrypted file. Each EncryptedData element refers to
> an EncryptedKey element, as described in XML Encryption.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/IDPF/epub-revision/issues/575#issuecomment-200818831

## 

_James Pritchett_

Leader, Process Redesign and Analysis

---

_Learning Ally™_Together It’s Possible
20 Roszel Road | Princeton, NJ 08540 | Office: 609.243.7608

jPritchett@LearningAlly.org

www.LearningAlly.org http://www.learningally.org/

Join us in building a community that helps blind, visually impaired &
dyslexic students thrive.

Connect with our community: _Facebook_
https://www.facebook.com/LearningAlly.org | _Twitter_
https://twitter.com/Learning_Ally | _LinkedIn_
https://www.linkedin.com/groups?home=&gid=2644842&trk=anet_ug_hm |
_Explore1in5_ http://www.explore1in5.org/ | _Instagram_
https://instagram.com/Learning_Ally/ | _Sign up for our community
newsletter_ https://go.learningally.org/about-learning-ally/stay-in-touch/

Support us: _Donate_
https://go.learningally.org/about-learning-ally/donate/ | _Volunteer_
https://go.learningally.org/about-learning-ally/volunteers/how-you-can-help/

**Comment by thkim2015** [comment]
@danielweck 
xs:ID is a datatype, right. I just tried to make simple solution without new schema, But I misunderstood. BTW, we are actually using new schema for the encryption element for the syntax checking like following.

>   <element name="encryption" type="ocf:encryptionType"/>
>     <complexType name="encryptionType" mixed="false">
>         <choice minOccurs="0" maxOccurs="unbounded">
>             <element ref="xenc:EncryptedData" minOccurs="0"/>
>         </choice>
>         <attribute name="ID" type="anyURI" use="optional"/>
>     </complexType>

So we can use as:

> <?xml version="1.0" encoding="UTF-8"?>
> <encryption xmlns="urn:oasis:names:tc:opendocument:xmlns:container"
> ID="http://readium.org/lcp/profile-1.0">

**Comment by thkim2015** [comment]
@jpritchettLA @danielweck 

There is no specific schema for the **encryption** in the W3C XML Encryption specification.
It defines just EncryptedData and EncryptedKey. 

The holder of the W3C XML Encryption, **encryption** is newly defined in the EPUB Open Container Format (OCF) 3.0.1.

Attribute of the encryption element is in the OCF specification space, not W3C Encryption one.

So we have to find the specification for the encryption in the OCF specification.
Even if IDPF defined that the 
https://github.com/IDPF/epubcheck/blob/master/src/main/resources/com/adobe/epubcheck/schema/30/ocf-encryption-30.rnc
is the public schema for the **encryption** element, I have no arguing point.
But IMO it is a kind of application which is based on the adobe's interpretation of the OCF specification.

**Comment by murata2makoto** [comment]
First, A.2 [Schema ](http://www.idpf.org/epub/301/spec/epub-ocf.html#app-schema-encryption) for encryption.xml in OCF 3.0.1 is incorrect.  [That](http://www.idpf.org/epub/30/schema/ocf-encryption-30.rnc) in OCF 3.0 is correct.

It is easy to add an attribute to the root encryption element by modifying /ocf-encryption-30.rnc, if such an attribute is indeed necessary.  But isn't rights.xml good enough?

**Comment by thkim2015** [comment]
@murata0204 
That's very good.

Sometimes the encrypted EPUB could be without rights.xml because the license file is not yet delivered or even some DRM uses other name of the license file rather than rights.xml.
In that case, it is not easy to determine which DRM should be selected with only encryption.xml.

**Comment by murata2makoto** [comment]
Do you intend to allow any RS to determine which DRM is used even 
when it does not know the DRM?

**Comment by thkim2015** [comment]
If encryption.xml has EncryptedData in it, the application should know which DRM should be used to treat the encryption.xml and related license document in order to select proper DRM module.

**Comment by murata2makoto** [comment]
I see your point.  Existing DRM solutions are restricted to closed environments:  RSs already know which DRM is used by which bookstore.  But you would like to provide an open solution: RSs do not know which DRM is used in advance.  RSs have to examine EPUB publications and determine which DRM is used.  Is my interpretation correct?

**Comment by danielweck** [comment]
So it looks like we should keep the EPUB specification as it is now (no revision of OCF in 3.1), but the EpubCheck schema must be updated to allow arbitrary attributes in the root encryption element. Right?

**Comment by murata2makoto** [comment]
If my interpretation is correct, I think that we should update the schema ocf-encryption-30.rnc and introduce an optional attribute at the root element, say DRM.  We might want to create an informative list of URIs for announcing DRMs, but this is not a must.

**Comment by thkim2015** [comment]
@murata0204 
Correct!

@danielweck 
But IMO for the interoperability, at least some document related DRM (including LCP) should mention that the ID attribute MUST be used in the **encryption**  element if encryption.xml has xenc:EncryptedData.

**Comment by danielweck** [comment]
@murata0204 I disagree, as I suggested before, EpubCheck should allow any arbitrary attribute (and the EPUB OCF specification remained unchanged)...
...and @thkim2015 yes of course I totally agree that the actual attribute namespace/name (and values) must be defined in the DRM -specific document (here: LCP basic and ecosystem profiles)
Would you both agree with that?

**Comment by thkim2015** [comment]
@danielweck 
I agree with your second opinion.

Regarding the first one,
Then, do you mean we need to provide autonomy for each DRM with arbitrary attribute name, instead of one specific name e.g. ID or DRM?.

If the attribute is always used for the identification of the DRM in the end, why do we need to maintain arbitrary attribute?

**Comment by danielweck** [comment]
An attribute value (typically: a URI) may not always be sufficient to hold identification information for a specific DRM profile?
But more to the point: isn't this a peripheral aspect of the EPUB specification, that does not need to be interoperable, thus why it is defined outside of OCF?

**Comment by thkim2015** [comment]
@danielweck 

Do you think we don't need to constrain even the number of the attribute, not just name?
If you do, it could be a quite flexible but doesn't it allow autonomy too much?

And in the Readium SDK point of view, Content Module Manager could process the arbitrary attribute well.
But in general, if we don't fix the method to identify the DRM with some fixed metadata,
the application which contains multiple DRM modules seems not to be easy to maintain multiple DRMs dynamically.
To make it possible, each DRM module might be required to provide specific and common function e.g) bool identifyDRM().

Of course, it is possible in the ContentModule architecture.

So if you are thinking the common identification function way is better than specific metadata,
it is also OK as long as the required API for the identification function is specified in somewhere.

**Comment by murata2makoto** [comment]
Re: An attribute value (typically: a URI) may not always be sufficient to hold identification information for a specific DRM profile?

Not at all sufficient.  But we have rights.xml already and some extension points (i.e., no constraints on child elements) within encryption.xml.

It is  impossible for IDPF to standardize the data format of each DRM.  The only thing we can do is to provide an attribute for specifying the name of the DRM, allow RSs to invoke different DRM engines for different values of this attribute, and let DRM engines to handle rights.xml, extension points, or other data.

**Comment by danielweck** [comment]
Okay, so it looks like we are in agreement that:

1) reading systems that implement support for multiple DRM schemes need to be able to discover the exact DRM scheme (e.g. LCP profile) at the time they acquire / ingest an input EPUB publication, so that they can process the publication further (e.g. loading of additional "meta" data from satellite files, acquisition of remote authorization / credentials data, license updates, use of special private secret key, etc.). The actual workflow / protocol depends on the DRM, there is no universal convention.

2) a new single XML attribute with a predefined full-qualified name (including namespace) on the root `encryption` element of `encryption.xml` may indeed be adequate for newly-produced EPUBs based on an LCP profile (for example), but this would effectively not be a useful addition to the specification for any other pre-existing DRM scheme, or any new encryption profile that chooses to use a different identification method. In other words, a well-defined named attribute would not guarantee interoperability, especially as no strict vocabulary would be defined for its possible values. It would seem like a false promise, not worthy of investing time and effort to revise the EPUB OCF `encryption.xml` specification, I think.

3) `META-INF/license.lcpl` (or its standalone equivalent file, outside of the EPUB container) is a clear identification vector for LCP (i.e. immediately discoverable by reading systems as a direct input). As per "7.1 Detecting LCP Protected Publications" in https://docs.google.com/document/d/1oNfXQZRSGqwpexLrhw0-0a2taEvVDXS9cPs8oBKLb0U
However,  the information provided in `encryption.xml` as `EncryptionMethod@Algorithm` (e.g. `http://www.w3.org/2001/04/xmlenc#aes256-cbc`) and `RetrievalMethod@URI` (e.g. `drm_license.json#/encryption/key`) + `RetrievalMethod@Type` (e.g. `http://acme.org/drm#EncryptionKey`) is not sufficient to infer the actual LCP scheme (and this applies to individual encrypted resources anyway, not to the publication as a whole). I would argue that in this case, some extension to `license.lcpl` in the "certified ecosystem" case is needed, like additional "profile" metadata. LCPL already defines the JSON field `encryption > profile` (the basic value is "http://readium.org/lcp/profile-1.0"), but as the name implies: this is the _encryption profile_, it does not seem like the right place to specify the LCP metadata that would allow differentiating the "certified ecosystem" from generic LCP.
@HadrienGardeur @llemeurfr thoughts?

4) At any rate, the EPUB specification for `encryption.xml` does not enforce a strict syntax on the root `encryption` element, yet EPUB-Check's schema is quite restrictive (prevents custom attributes). See:

https://github.com/IDPF/epubcheck/blob/master/src/main/resources/com/adobe/epubcheck/schema/30/ocf-encryption-30.rnc
and:
https://github.com/IDPF/epubcheck/tree/master/src/main/resources/com/adobe/epubcheck/schema/30/mod/security

Note that the XML content inside the `encryption` element is of course well-defined (based on W3C's Lenient-Encryption11-ghc.rnc), see:

http://www.idpf.org/epub/301/spec/epub-ocf.html#app-schema-encryption
=>
https://www.w3.org/TR/2013/NOTE-xmlsec-rngschema-20130411/
=>
https://www.w3.org/TR/xmlenc-core1/

So as a side goal, maybe ask the EPUB-Check developers to relax their schema?

**Comment by danielweck** [comment]
Guys, if you have already read my previous comment via the email notification, please re-read it in the GitHub issue tracker, as I have made a couple of edits to my comment since I posted it.

**Comment by HadrienGardeur** [comment]
@danielweck I think that `encryption > profile` is enough to identify an LCP protected publication that's part of the certified ecosystem, since certification will require the use of a unique encryption profile with its own twist.

"Generic LCP" will use a different value (URI) for that profile.

**Comment by HadrienGardeur** [comment]
Also, just my two cents but I think that EPUB made a big mistake by allowing multiple DRM schemes while keeping the same file extension and media type for the same publication.

Whenever we end up creating a new major version of EPUB without forward compatibility (EPUB 4.0?) we should really address that.

**Comment by danielweck** [comment]
> "Generic LCP" will use a different value (URI) for that profile.

Oh great!

**Comment by danielweck** [comment]
Okay, so for LCP the issue seems solved: the `encryption>profile` JSON property in `license.lcpl` can be used to infer the actual DRM scheme / profile.
@llemeurfr could you please confirm that there is no design conflict with the envisioned "certification ecosystem" profile / URI approach: there's the "basic" encryption profile `http://readium.org/lcp/profile-1.0` as per "6.3. Basic Encryption Profile 1.0" ( https://docs.google.com/document/d/1oNfXQZRSGqwpexLrhw0-0a2taEvVDXS9cPs8oBKLb0U ), and an implementation in the certified-LCP ecosystem would use a _different_ URI, even if the encryption algorithms are the _same_ (would that be okay @HadrienGardeur ?)
What's currently missing is the "LCP Encryption Profiles Registry", which would look similar to existing EPUB registries, e.g. http://www.idpf.org/epub/vocab/package/types/ (relatively trivial addition)

**Comment by HadrienGardeur** [comment]
Yeah and we recently talked about moving the IDPF registries to Github, we might want to do the same thing for LCP.

**Comment by danielweck** [comment]
@mattgarrish this issue can be closed. The EPUB3.1 specification will not introduce new elements / attributes to `encryption.xml` in order to infer some kind of DRM "identifier".
Specifically, the (fresh) LCP implementation in ReadiumSDK does not require such additional data in order to function properly.
Generally-speaking, there is no need for an interoperable mechanism for various Digital Rights Managements schemes to be handled uniformly by EPUB processors.
