### ISSUE TITLE
Complex page layouts

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#588]
I take advantage of the 3.1 update to ask why is there nothing between reflowable and fixed layout format.
- The reflowable is great for all device, allowing the user to change font size, margin, color ...but you can't do any complex page layout.
- On the other hand fixed layout allow a complex layout ...but has a fixed size.

Would it be possible to add a new format with the following features :
- designed for magazines or complex layout book > the user must not be able to change the font, it's size, margin or color
- designed for any device > the content can resize according to the device size using media queries

I found this document http://www.idpf.org/charters/2012/layout/ahl.html#h.eub0wrqgo7eg  although I'm not sure it does include my previous definition.

Thanks in advance for any comment

[See full thread at https://groups.google.com/forum/#!topic/epub-working-group/ybmulvP4eqQ]

**Comment by GarthConboy** [comment]
I think this might be interesting.  But, especially now that we've trimmed down what's going to be in EPUB 3.1, we should not embark on this venture at this time.

Proposed resolution: "Not for EPUB 3.1"

**Comment by andrewgribben** [comment]
My two cents are that this is quite a big one for educational publishers. We, like a lot of others, are building our own readers and extending the specification to deliver this so I consider further postponement dangerous as it will lead to more deviation from the standard. We can provide sample content if required.

**Comment by dauwhe** [comment]
This issue seems to encompass several ideas. 
1. Bill McCoy proposed using rendition:pre-paginated without a viewport, thus getting some "benefits" of FXL (no user overrides) with more flexibility. EPUBCheck does not seem to require viewport meta for pre-paginated documents. So that seems possible, although I'm not sure what reading systems would do with such a document. 
2. I do not like the idea of having metadata to prevent users from changing fonts, etc. 
3. The larger question seems to be AHL-type layouts. This would be a job for the CSS Working Group rather than EPUB 3.1. The good news is that the page floats spec is getting some attention from CSSWG. And much of the IDPF AHL spec is being polyfilled by Vivliostyle. 

Ultimately I agree with Garth that there's nothing to be done in the 3.1 time frame.

**Comment by andrewgribben** [comment]
Thanks, that's fair enough.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-03-04-epub#section3) on 2021-03-04

List of resolutions:

- ***[Resolution No. 3](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-03-04-epub#resolution3):  Close issue 588***

<details><summary><i>View the transcript</i></summary>

### 3. Complex page layouts 

_See github issue [#588](https://github.com/w3c/epub-specs/issues/588)._




**Wendy Reid:** basically asking why nothing exists between reflow and completely fixed layouts  
… e.g. something like fixed, but which could respond to things like media queries  
… now we have things like grid and flexbox  

**Matt Garrish:** we could really get sucked into something big like this  
… it really needs to be fleshed out  
… and could have a seriously negative impact on readability of some epubs  

**Brady Duga:** this also comes from a time when people were trying to do a lot with magazines in epub format  
… not so much of a priority these days  
… may be another feature with lack of implementation support  

**Dave Cramer:** i think its hard to do things without proposed implementations (i.e. how it would work in detail, what it would enable)  
… probably not for our current spec  

**Wendy Reid:** I see the use case, but agree with mgarrish that there could be a big negative impact on a11y if done badly  
… more experimentation is needed first  

**Dave Cramer:** ultimately something other than fxl could help a11y, but we don't know what that is  

**Wendy Reid:** has anyone done any interesting experiments in this area in JP?  

**Shinya Takami (高見真也):** in japan, it is not easy to make fxls  
… fxl content and magazines are mostly made using images  

> **Proposed resolution: Close issue 588** *(Wendy Reid)*

> *Brady Duga:* +1

> *Matt Garrish:* +1

> *Wendy Reid:* +1

> *Matthew Chan:* +1

> *Toshiaki Koike:* +1

> *Shinya Takami (高見真也):* +1

> *Marisa DeMeglio:* +1

> *Masakazu Kitahara:* +1

> ***Resolution #3: Close issue 588***

</details>
