### ISSUE TITLE
CFI assertion correction requirement

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#631]
[opening new issue for report in #629 ]

There is another odd thing I was concerned (from developer view). mismatching **may** and **should**.

| Section | &#32; |
| --- | --- |
| 3.1.2 XML ID Assertion | a Reading System **may** determine that the location referenced by the CFI is not the original intended location, and **may** use the identifier to compute the set of steps that reach the desired destination in the content (see Intended Target Location Correction). |
| 3.1.8 Text Location Assertion ([) | A Reading System **may** determine that the location referenced by the CFI is not the original intended location (due to non-matching text), and **may** use the preceding/trailing text to compute the set of steps that reach the desired destination in the content (see Intended Target Location Correction). |
| 3.5 Intended Target Location Correction | When a Reading System is processing a CFI, it **should** check the correctness of any encountered assertions. For example, given the path /6/4[chap01ref]!…, the Reading System **should** verify that the element has the ID matching chap01ref when processing element 4 (for this example, an itemref in the spine). If not, the Reading System **should** locate the ID chap01ref within the document and correct the CFI (e.g., if a new itemref was inserted before the chap01ref itemref, the desired element number would now be 6 and the corrected CFI would be /6/6[chap01ref]!…). Likewise, text location assertions should be used to check referenced target locations, and used to derive a corrected CFI that targets the desired text location. |

/cc @vtns @danielweck

**Comment by mattgarrish** [comment]
[reply by @danielweck]

@vtns well spotted.
Could you please file a new issue?
I think may is more appropriate, because CFI references can be used in a variety of processing contexts / application domains. For example, robust legal citations / annotations frameworks would definitely need to validate assertions, but implementations of basic navigation / bookmarking (typically, in reading systems that both produce and consume the CFI expressions) are probably not going to bother validating + redirecting inaccurate references to the correct spot. @mattgarrish thoughts?

**Comment by mattgarrish** [comment]
Well, niggling details first, the initial "may" in 3.1.2 and 3.1.8 is not actually a normative requirement. I would change the start of those sentences to "If a Reading System determines ..., it ??? ...".

But to the real question, I thought "may" was used in the 3.1.\* sections because any given assertion might be the failure point and not be useful (e.g., how can you use an id assertion for correction if the id was removed). So 3.5 is telling you you should check each part of the CFI, but any given assertion may or may not be useful in fixing.

That's my best attempt at understanding why we have differing wording, at any rate.

If there is a rationalization like that to make, it would help to be clearer. If we're just repeating requirements, we should see if we can defer to 3.5 without making a normative requirement in the assertion sections.

**Comment by vtns** [comment]
@mattgarrish, 
I agree with you.
With my understanding, section 3.1.2 and 3.1.8 are telling the nature/use of assertions and it is better not to place the requirements for Reading System in those sections, because that requirements are written later in section 3.5.

One thing to be considered is that we have to be very careful about the use of words MAY or SHOULD, since those words in this kind of documents are commonly read as RFC2119 keywords which have their own strict definition. (https://www.ietf.org/rfc/rfc2119.txt) 

> `5. MAY`
>       This word, or the adjective "OPTIONAL", mean that an item is truly optional.  One vendor may choose to include the item because a particular marketplace requires it or because the vendor feels that it enhances the product while another vendor may omit the same item. .....(CONT.)

Can't we use word "can" rather than "may" in section 3.1.2 and 3.1.8, to avoid to mention the requirement nor the absence of requirements in those section?

**Comment by vtns** [comment]
Oh, I'm sorry I forgot to say thank you to file a new issue for me :-)

**Comment by danielweck** [comment]
`can` in informative sections + `should` in normative parts, sounds good to me.

**Comment by danielweck** [comment]
3.1.2 XML ID Assertion ([)
http://www.idpf.org/epub/linking/cfi/epub-cfi.html#sec-path-xmlid

3.1.8 Text Location Assertion ([)
http://www.idpf.org/epub/linking/cfi/epub-cfi.html#sec-path-text-location

3.5 Intended Target Location Correction
http://www.idpf.org/epub/linking/cfi/epub-cfi.html#sec-target-correction

| Section | &#32; |
| --- | --- |
| 3.1.2 XML ID Assertion | a Reading System **may** determine that the location referenced by the CFI is not the original intended location, and **may** use the identifier to compute the set of steps that reach the desired destination in the content (see Intended Target Location Correction). |
| 3.1.8 Text Location Assertion ([) | A Reading System **may** determine that the location referenced by the CFI is not the original intended location (due to non-matching text), and **may** use the preceding/trailing text to compute the set of steps that reach the desired destination in the content (see Intended Target Location Correction). |
| 3.5 Intended Target Location Correction | When a Reading System is processing a CFI, it **should** check the correctness of any encountered assertions. For example, given the path /6/4[chap01ref]!…, the Reading System **should** verify that the element has the ID matching chap01ref when processing element 4 (for this example, an itemref in the spine). If not, the Reading System **should** locate the ID chap01ref within the document and correct the CFI (e.g., if a new itemref was inserted before the chap01ref itemref, the desired element number would now be 6 and the corrected CFI would be /6/6[chap01ref]!…). Likewise, text location assertions should be used to check referenced target locations, and used to derive a corrected CFI that targets the desired text location. |

**Comment by danielweck** [comment]
@mattgarrish could you please replace `may` in non-normative / informative sections with `can`, as per the above references? (`should` remains in normative sections)

**Comment by mattgarrish** [comment]
I've updated the prose as requested in the commit noted above. Please close this issue if no other changes are needed.

**Comment by danielweck** [comment]
Fixed by https://github.com/IDPF/epub-revision/commit/2b8cee497e571d1a0cc8943a089fc73f94bca164
