### ISSUE TITLE
audio labels in navdoc

### ISSUE THREAD

**Issue by mgylling** [w3c/epub-specs#647]
The NCX had audio labels that allowed reading systems to efficiently and unambiguously fetch audio labels for TOC (and other nav) entries, to read to the user primarily while browsing the TOC. 

EPUB Navigation Documents currently do no support the equivalent. This should be added to enable to complete the transition away from NCX without any features being lost.

**Comment by danielweck** [comment]
Google Group `epub-working-group` email discussion: https://groups.google.com/d/msg/epub-working-group/JTB5UI82xIo/oJEyHwzxBAAJ
...originates from Google Doc: https://docs.google.com/document/d/1GcwrWIXSTfQYJlufbceK8utU8KPdOZp2wtj2T23P9hQ
(search for "We should ask Readium people about this specific behaviour")

**Comment by danielweck** [comment]
Quote from the email discussion:

## DANIEL

Well, if the NavDoc is in the spine (to simplify, let's say that it is 
"linear" in the primary content flow), and if it is associated with a 
SMIL file, then synchronized audio will progress from one heading to 
the next, and playback will automatically move into the next spine 
item in the linear reading order. From the user standpoint, that is 
clearly not a satisfactory behavior. However, let's not immediately 
assume that something is missing in the Media Overlay specification. 
For example, it would be tempting to add a new SMIL attribute to infer 
some kind of forced "pause + resume" behavior, but I feel that this 
would be stepping across the dividing line between using SMIL as a 
simple declarative language that defines synchronization points 
between text and audio, and using SMIL to define more complex playback 
patterns (which is what the full-fat version of SMIL does very well, 
but in both DAISY and EPUB we decided to stay away from sophisticated 
timing and sync features). 

If I understand correctly: the use-case for audio-enabled navigation 
labels is valid in both audio-only and full-text-full-audio books. In 
both cases, a text "skeleton" is required so that the SMIL file can 
map document fragments with audio clips. In both cases, the NavDoc can 
optionally be rendered as part of the spine flow, but we've 
established that the default playback behavior is inadequate. 
Furthermore, the user-interaction we want to enable is: keyboard 
tab/arrow navigation inside the hierarchical list of headings, 
accompanied with short audio output for each "landing" spot (i.e. 
narrated heading label), followed by user action to activate the link 
and jump into the desired section. 

So, I see two possible avenues (to be discussed further): 

1) NavDoc in spine, rendered as normal document, but without Media 
Overlays (i.e. no declarative SMIL audio sync). Instead: 
Javascript-driven audio playback is invoked when keyboard focus is 
moved onto hyperlinks. I don't like this, because this places a lot of 
responsibility on authors (risks of bugs in JS implementation, e.g. 
fast-navigation from heading to heading), and potentially requires 
many individual physical audio clips (actual standalone files). The 
need for Javascript could be negated by placing HTML5 audio elements 
directly next to textual labels, but I fear this would lead to a 
really unpleasant user experience (manual trigger of play/pause 
actions). 

2) NavDoc is not in spine, it is rendered by the reading system in its 
dedicated view. There is a SMIL file for the NavDoc (typically, with a 
large single audio file), and it is the responsibility of the reading 
system to build the audio playback experience when heading labels are 
keyboard-focused (such as HTML hyperlinks in web browser apps, or GUI 
list items in native apps). The problem with this approach is that the 
EPUB3 specification cannot express a conformance requirement for such 
behaviour (the spec. is already vague enough regarding how to present 
the TOC). It would be down to the goodwill of reading systems 
implementers.

**Comment by danielweck** [comment]
Quote from the email discussion:

## GEORGE

I hope we can simplify this issue. First, there are EPUB reading systems that can present text only EPUBs, which means that they have TTS onboard. This means that having the NavDoc not in the spine would be just fine. The reader would read through the NavDoc just like they do with any other EPUB, but when they go to the spine item the media overlay would trigger the recorded audio. 

Now, a reading system that does not have TTS onboard would need to be a dedicated player, like some of those distributed by DAISY organizations. 

Could we require that in audio only or in audio synchronized with text titles that there be a Navdoc in the spine with media overlays and also a NavDoc outside the spine that had no associated media overlay? The reading system with no TTS would fall back to the NavDoc in the spine with a media overlay. 

In the edge case of providing materials where the language has no script (aboriginal peoples) there would be no TTS and a dedicated system of some sort would need to be  made available. 

Would this work? The NavDoc would be duplicated in these types of EPUBs. Would this mess up reading systems? Would this allow one type of title to be distributed?

**Comment by danielweck** [comment]
Quote from the email discussion:

## AVNEESH

Just quick rundown. 
1. Regarding Java script solution, it looks less feasible, not only due to 
complexity that you mentioned  but also because execution of Java script is 
not allowed in some conditions. one of the example is education institutes. 
1. Regarding using complex structures of smil. I think that use of smil in 
   EPUB 3 is highly simplified, whereas in DAISY  smil profile we used the 
   attributes and elements to provide pause and stop behaviour 
   http://www.w3.org/TR/REC-smil/smil-daisy-profile.html. It was also a 
   simplified version of smil, but not as simplified as EPUB 3 smil profile. 
   May be a couple of elements and or attributes can be ported to EPUB 3 smil 
   profile to do this job. 

I do not  think that there is a very simple solution for the use case. 
1. Audio element in html is too limited. 
2. Java script is not desired due to various reasons. 
3. Media fragments, which are not supported by browsers, and can lead to 
really unpleasant experience. 
4. Adding a couple of elements and/or attributes from native smil specs. to 
EPUB 3 smil profile. 
5. Use multiple NAV Docs, leading to redundancy as George described. 

Looking at the above list, expanding smil profile a little looks worth 
exploring.

**Comment by danielweck** [comment]
Quote from the email discussion:

## DANIEL

strictly-speaking there is only one mandatory NavDoc, which 
is the one that all compliant reading systems render in an arbitrary 
manner inside a dedicated TOC graphical user interface. A second table 
of contents could indeed be added as a normal spine item (potentially 
with Media Overlays), but there would be no special metadata to 
identify it as some kind of secondary fallback NavDoc. By convention 
it could be the first linear document in the spine, but this is not a 
very robust conformance rule (what if publishers are legally required 
to provide a foreword / dedicace as first pages of the title?). 
And, as I explained in my original comments, the audio playback of TOC 
headings inside a spine item rendered with Media Overlays is not a 
satisfactory user experience, because it just plays continuously, and 
even eventually automatically moves into the next spine item. This is 
not designed for playing individual heading labels each time the 
keyboard focus moves onto the TOC hyperlinks. Conversely, a dedicated 
NavDoc view is a better fit for such audio feedback feature...but the 
problem in this case is that the EPUB specification cannot normatively 
state the expected behaviour of reading systems in terms of user 
interface / experience.

**Comment by danielweck** [comment]
Quote from the email discussion:

## DANIEL

I think that adding SMIL pause/resume semantics would not 
help solve the audio-NavDoc problem, because ; if I understand 
correctly ; what we need is a way for users to step into TOC headings 
(typically, using keyboard focus) and to hear the corresponding audio 
clips. I feel that the ability to successively hear fragments of text 
without actually being able to immediately activate the associated 
navigation links undermines the justification for introducing more 
sophisticated SMIL timing and synchronization features in the EPUB 
specification. Furthermore, based on my experience implementing SMIL 
playback engines (including Readium), I fear that features such as 
"daisy:userResume" (which involves multiple synchronisation arcs and 
event-based graph timing) would require significant refactoring in 
EPUB3 reading systems that support Media Overlays today, making this 
an unrealistic proposal. 
Link to "daisy:userResume": 
https://www.w3.org/TR/REC-smil/smil-daisy-profile.html#DaisyProfileNS-EndAttrSpecialValues

**Comment by danielweck** [comment]
Quote from the email discussion:

## DANIEL

The main requirement is that the playback should stop after the smil node is 
finished. If this can be achieved in any way, it solves the issue.

**Comment by danielweck** [comment]
Quote from the email discussion:

## DANIEL

Please pardon my ignorance ; and I apologize if this has been debated 
in depth before ; but how does this help me (as a user) navigate the 
talking book based on audio feedback? (i.e. narration of heading 
labels) I imagine that "automatic-pause + manual-resume" in Media 
Overlays documents is a feature that has some kind of general-purpose 
utility, but I must admit not understanding its usefulness in the 
audio-NavDoc context. 

At any rate: a new SMIL attribute to declare the pause+resume 
behaviour on "par" or "seq" timing containers would be feasible, but I 
feel uneasy at the thought of implementing support for multi-arc and 
event-based SMIL timing in @begin or @end attributes.

**Comment by danielweck** [comment]
Quote from the email discussion:

## AVNEESH

I think that we can have a call to discuss the details. 
The overview is that the behaviour is roughly like the regular navigation in 
Media Overlays, with some difference. 
Normally, you can play the book, and you can give a command to go to next 
heading, and the playback pauses, then playback moves to the new heading and 
starts again. 
In this case,  when nav doc is navigated, the playback module will move to 
the corresponding smil node and start, and it will auto stop when the 
corresponding smil node is complete.

**Comment by danielweck** [comment]
Quote from the email discussion:

## ROMAIN

I'm only catching up with the thread, but some quick comments on Avneesh's rundown. 

> Just quick rundown. 
> I do not  think that there is a very simple solution for the use case. 
> 1. Audio element in html is too limited. 

Can you summarise why? 
Is it because the audio would show up for everyone? Maybe it's something that can be addressed by mandating the audio to be declared with the HTML hidden attribute. 

> 1. Java script is not desired due to various reasons. 

Agreed. 

> 1. Media fragments, which are not supported by browsers, and can lead to really unpleasant experience. 

Yes. 

> 1. Adding a couple of elements and/or attributes from native smil specs. to EPUB 3 smil profile. 

I don't believe new elements or attributes are needed. All the essential information is there, the issue is one of playback behaviour. 

From my understanding of the discussion, the primary issue is that MO are read continuously, whereas when using the ToC the user only wants to hear the heading and be able to activate the link, without continuing the reading of the next heading. 

One thing to keep in mind is the “dual nature” the Nav Doc (as Dan also reminded us), which can be both an ordinary Content Doc and a specialised Navigation helper. 
- when the Nav Doc is in the spine and accessed as any other there Content Document –as part of the primary reading order– the continuous reading makes sense to me. In this case, reading and activating a link works exactly the same as activating a link in ordinary content. 
- when used as the navigation entry point by the RS (usually a "nav side bar" or any RS-specific chrome), we want the reading to be triggered then stopped for each heading. Maybe the MO spec can further specify this playback behaviour, which only applies to the Nav Doc? 

Also, I'm not sure if there is an issue of link directions for Reading Systems –i.e. currently the SMIL has links to the HTML, not the other way around– (Daniel, thoughts?). 
If there is, it can also be addressed by "hidden" links added only in the Nav Doc. 

> 1. Use multiple NAV Docs, leading to redundancy as George described. 

Yes, this must be avoided.

**Comment by danielweck** [comment]
Quote from the email discussion:

## DANIEL

> - when used as the navigation entry point by the RS (usually a "nav side bar" or any RS-specific chrome), we want the reading to be triggered then stopped for each heading. Maybe the MO spec can further specify this playback behaviour, which only applies to the Nav Doc? 

Could the EPUB specification use prose along the lines of "if the 
navigation document is associated with a SMIL Media Overlays ; and 
regardless of whether or not the nav doc is rendered as an ordinary 
content document as part of the sequence of spine items ; then reading 
systems may support synchronized audio playback of individual 
navigation labels as part of the reading-system -specific presentation 
method used to expose the nav doc links. In which case ; unlike normal 
Media Overlays playback which is continuous as per the linear reading 
flow ; here reading systems may play audio clips associated with each 
navigation labels based upon user interaction triggers, such as 
keyboard focus / mouse hover / touch input, in order to provide users 
with audio feedback when browsing the nav doc." 

> Also, I'm not sure if there is an issue of link directions for Reading Systems –i.e. currently the SMIL has links to the HTML, not the other way around– (Daniel, thoughts?). 

I imagine that reading systems that are compliant with the EPUB3 Media 
Overlays specification build some kind of internal bidirectional map 
between SMIL and target HTML documents. Otherwise, it would be 
impossible to trigger playback based on user-selection of document 
fragment (e.g. mouse-click on text word / sentence / paragraph) ... 

> If there is, it can also be addressed by "hidden" links added only in the Nav Doc. 

...however, I would hazard a guess that such reading-system does not 
support hyperlinking directly into the SMIL timing graph. There is a 
level of indirection through HTML documents. The audio-only type of 
EPUB Media Overlays does not support anchor-linking into SMIL files, 
right? 

That being said, a "smart" audio-NavDoc -aware reading system could 
present the navigation document in its special rendering viewport with 
additional support for audio clip playback, based on user selection 
(all the information is already in the SMIL, it's just a question of 
re-interpreting the playback behaviour). But like I said before, this 
is a UX concern, not something that the EPUB specification can define 
in a systematic normative way.

**Comment by danielweck** [comment]
Dear all,

Yesterday we discussed structured-audio / audio-only talking books
based on EPUB3 Media Overlays, and more specifically: support for
pre-recorded audio in speech-enabled navigation headings (conceptually
similar to the TOC audio labels in DAISY NCX).
To demonstrate the feasibility of this new reading system feature, I
implemented a Readium proof-of-concept based on the online "cloud
reader" (and the offline Chrome extension, as they both share the same
code).

Here is a link to the online prototype:
http://readium-smilnav.surge.sh/?epub=moby-dick-mo-TOC

(note that in this demo, only the TOC labels for chapter _one_ and
_two_ have SMIL audio, so most navigation headings are in fact silent)

Usage instructions:

1) load above link in web browser, wait for publication to load (may
take some time depending on network latency)
2) press keyboard key `t`, or click "table of contents" icon (this
should open navigation pane on left hand side)
3) hit `arrow down` key five times in order to reach "chapter 1"
heading, wait for audio label to start playing automatically, wait for
end of playback (note that HTML5 audio innacurracies may result from
slow network)
4) hit `arrow down` key once to listen to "chapter 2" phrase, hit
`arrow up` key once to interrupt current playback, and wait to hear
audio for previous heading
5) keep `arrow down` or `arrow up` pressed to quickly skim list of
headings, when key released, playback should start for currently
focused heading (if this heading contains audio, naturally)
6) go to chapter 1, and start playing regular Media Overlays (hit key
`m` or use the "play" icon buttons)
7) re-focus keyboard on audio-enabled TOC headings, and see how MO
playback pauses to avoid overlapping audio
8) change MO playback rate from `1` to faster (e.g. `3`), and listen
to TOC audio again (the speed should be identical)

Explanation: there is nothing special about the SMIL or any other
parts in this EPUB3 example. I just used the IDPF Moby Dick sample
that has two chapters with Media Overlays, and I hand-crafted the SMIL
for the navigation document, linked below:
http://readium-smilnav.surge.sh/moby-dick-mo-TOC/OPS/nav.smil
Note that I did not re-create the audio file, I simply copied the clip
being+end timing values that are used for the main HTML content
documents (which contain the same heading texts as the nav-doc, so the
audio narration matches too).
The NavDoc does _not_ need to be in the spine for this feature to
work. All that's needed is the usual association between the HTML
manifest item and its SMIL counterpart, in the OPF package definition.

The code change necessary to implement this new reading system feature
is not complicated, and definitely much simpler than to support SMIL
synchronisation arcs and event-based timing:
https://github.com/readium/readium-js-viewer/compare/develop...feature/smilToc

Regards, Daniel

**Comment by mattgarrish** [comment]
Proposed solution:

Add the following section to the media overlays specification:

5 EPUB Navigation Document

The EPUB Navigation Document is an XHTML Content Document and can therefore be associated with an audio Media Overlay. Unlike traditional XHTML Content Documents, however, Reading Systems are also required to present the EPUB Navigation Document to Users even when it is not included in the spine (see EPUB Navigation Documents — Reading System Conformance [Packages 3.1]). As a result, the method in which an associated Media Overlay behaves can change depending on the context:
- When included in the spine, playback of the EPUB Navigation Document's Media Overlay obeys the same conformance requirements as with any other XHTML Content Document.
- When exposed in a presentation context that allows Users to access and activate the links, Reading Systems may implement additional presentation behaviours to expose audio feedback when navigation links are accessed.

Note
Specific implementation details are beyond the scope of this specification.

**Comment by mattgarrish** [comment]
New section has been added:
https://rawgit.com/IDPF/epub-revision/master/build/31/spec/epub-mediaoverlays.html#sec-nav-doc

Please close this issue if no other changes are needed.
