### ISSUE TITLE
Metadata for announcing whether TTS is needed for each natural language

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#656]
Introduce metadata for announcing which natural language in the EPUB publication requires TTS.  Such metadata helps to avoid downloading what your reading system cannot handle.  It also allows reading systems to launch all required TTS engines at the very beginning.

Consider a Chinese language training book written in Japanese.  There will be no recorded audio for Japanese, and thus you will need Japanese TTS.  For each chunk of Chinese text, there will be recorded audio and you won't need Chinese TTS.  Metadata should say so.

See https://docs.google.com/document/d/1GcwrWIXSTfQYJlufbceK8utU8KPdOZp2wtj2T23P9hQ/edit?pli=1#bookmark=id.9bd8qjof7isy

**Comment by okayama247** [comment]
My name is Nobuya Okayama, Director of Japan Electronic Publishing Association (JEPA).
I talked and consulted to Murata-san about TTS. I'll explain in detail more.

Japanese documents can be various expressions such as Kanji (Chinese characters), katakana, hiragana, Roman letters, and the foreign language (English, French, and German etc.). 
We have two Issues in case of using TTS.

One is that we have cessation of speech for initialized processing of other language TTS when switching to it in the middle of a sentence.  It is acceptable for us if less than one second, but it takes several seconds (about 5 to 10). If we know whether to use any language TTS in the definition part, it will be able to initialize TTS of all language we use in the initial stage. For example, in case of using Japanese, Chinese and English, we declare by a plurality of language tag for TTS if possible.

Another is that it is not possible to start TTS of the most fit the language in every sentence.
It may NOT be so difficult to identify the languages in the phonetic character language such as English, French etc.  However the language identification of sentence does not go well, because Japanese and Chinese have common kanji (ideographic characters). I know xml:lang as metadata is in xhtml file. But I do not think that it goes well to reading playback by TTS in case of the sentence is describe in many language. Kindle App in iPad sometimes reads Japanese sentence as Chinese sentence by VoiceOver. Of course, reading in Chinese!!!

In order to solve these two issues, it is important to be able to define by language attribute tag whether to use TTS in any language in EPUB definition file (.opf file?).  Also in the portion where sentence language changes, by specifying phrase lang tag, we believe TTS is necessary to be able to be properly determined language.

**Comment by mattgarrish** [comment]
I'm not sure how you make a determination that only select languages of those listed in the package document are needed. For example:
- what if the device doesn't support media overlays and only provides tts capabilities? You need to preload all the languages not just some.
- what if the user doesn't want to use media overlays and only selectively wants parts of any of the text voiced by tts? Again, you'd want to preload all, not some.
- what if the user doesn't intend to use media overlays or tts capabilities? You can never know this, so do you always preload?

We've retained dc:language as required metadata, and its supposed to be repeated for each language used, so beyond that we're trying to influence when and where tts engines should be preloaded. That optimization seems better left to the RS to figure out.

It's also selective metadata that only exists in an epub, so o/s level voicing capabilities like voiceover and friends are unlikely to pay attention to any new metadata we add.

Some of the issues sound like bugs/limitations with the tts engine itself. If you've set the language for the document and the tts engine voices it in another language, then there's nothing I see that we can do from within the epub to address.

**Comment by mattgarrish** [comment]
Closing this issue as the accessibility group discussed and recommended the use of dc:language in the package document for this purpose.

**Comment by okayama247** [comment]
Garrish-san,
I am sorry to reply too late. I understand your commnet and appreciate your suggestion.
Nobuya Okayama :)
