### ISSUE TITLE
Consider extending alternate style tags (2.1.3.5)

### ISSUE THREAD

**Issue by laudrain** [w3c/epub-specs#668]
Alternate style tags can be used for DYS people. 
Publisher can prepare specific stylesheets with adapted rendering (fonts, line height, background color, syllabic coloration, ...) for DYS or other kind of impaired people. 
The list of available alternate stylesheets in the EPUB should be displayed by the reading system for the final user to choose.

**Comment by dauwhe** [comment]
Does any existing EPUB Reading System display alternate stylesheets?

**Comment by laudrain** [comment]
I think so but only with "Night" or "Day" modes with predefined UI buttons.
The idea is that RS should expose any alternate style sheets list that the author has implemented in the EPUB.
Last year, Mantano made a beta release of his RS (based on Readium SDK) with that option so that I could demonstrate an EPUB prototype of this for DYS and visually impaired people.

**Comment by dauwhe** [comment]
Firefox exposes this functionality under View > Page Style. Opera 12 also has a menu item to select from alternate stylesheets. As far as I can tell, Chrome and Safari don't support this. 

I'd be interested in input from reading system developers. I think there's a good case to be made from an accessibility point of view for such a feature, and this technique has a long history. Is there any appetite for adding a statement to the spec saying reading systems should or must expose alternate stylesheets to the reader?

**Comment by bduga** [comment]
Google Play Books uses alternate style sheets for vertical content. I think the general idea has not received much traction on the web, hence the lackluster support. I would not support a change that forces RSes to do this for 3.1 as there are likely some interesting implications. For instance, do we have to provide horizontal mode for Japanese content? Seems late to be adding features. Though, I see this was originally reported in Feb, so not really @laudrain's  fault.

**Comment by laudrain** [comment]
@bduga, I do not see this as a new feature for 3.1. It is already available in 3.0.1.
The change would be the RS system activation of the listed alternate stylesheets available in the EPUB file. Instead of predefined buttons ("Night", "Day"), the user would be presented a list with the titles of the different stylesheets prepared by the EPUB author.

Here is a screenshot in Bookari RS form Mantano where this UI is available 
![img_5882](https://cloud.githubusercontent.com/assets/17047162/16525609/838a78ae-3fad-11e6-8947-1a7ff0f54650.PNG)
The selected ligne drives a stylesheet wich colors syllables in word for DYS people.

**Comment by mattgarrish** [comment]
Just to be pedantic, but Alternate Style Tags adds a machine semantic for processing alternate style sheets automatically by the Reading System, so this isn't technically a request to change or extend that specification. It would be wrong to put it under that section, from what I see.

I guess this would belong in the CSS reading system requirements, since presenting alternate style sheets to the User would have to include alternate style sheets without any class attribute, too.

I don't recall the issue of where other alt style tags would be defined being discussed (yet another registry?), but if the goal really is to extend alt style tags then that would need to be worked out.

From an accessibility perspective I appreciate the value of the general and machine capabilities, but it's also been a longstanding problem that there isn't widespread support, people don't know to look for alternatives in browsers that do support them, and authors don't generally provide them. It's bound to the other problem of user-defined style sheets, which is also a useful theory except few users can write style sheets to fix problems they have, browser don't support them, etc.

**Comment by laudrain** [comment]
I agree it belongs to Reading Systems requirements.
When the EPUB author has added a prepared list of stylesheets, the RS should display that list for the user to choose.
The presented use case of accessibility, in particular for DYS people, is an important one, IMHO.

**Comment by TzviyaSiegman** [comment]
The reading system conformance statement about CSS [1] points to the CSS snapshot, which at this point does not mention alternative stylesheets because there is little or no support for them. The spec mentions this only in the section on alternate style tags [2], which points to a document originally written in 2011 [3]. Is this the method that reading systems use to create day/night mode today?  I think if we raised this with CSS WG today, they would point us to Houdini instead of expanding the existing model, /cc @bduga @danielweck 

[1] http://www.idpf.org/epub/31/spec/epub-contentdocs.html#sec-css-rs-conf 
[2] http://www.idpf.org/epub/31/spec/epub-contentdocs.html#sec-html-alternate-style-tags
[3] http://www.idpf.org/epub/altss-tags/

**Comment by bduga** [comment]
Although alternate style sheets are not widely supported, it is possible to polyfill in a RS. I don't think Houdini is an appropriate alternative to alternate style sheets since the alternates are there to represent publisher intent. Today, Play Books does not use them for Day/Night mode, as we feel it isn't robust enough to properly handle the use case. We do use them for applying vertical styling when they are provided.

**Comment by mattgarrish** [comment]
The HTML spec defines the alternate keyword, but it doesn't require any specific behaviour when it is accompanied by 'stylesheet'.[1]

I can't even find anything in UAAG about making alternative style sheets available.

There's nothing stopping someone from exposing alternate style sheets now, so I'm not sure that adding a requirement is likely to influence implementations. Maybe it could go in the accessibility reading system tests for epubtest.org without being called out in the specs, but it would need to be vetted by that group.

[1] https://www.w3.org/TR/2016/CR-html51-20160621/links.html#link-type-alternate

**Comment by danielweck** [comment]
FYI: Readium currently does not support alternate tagged stylesheets. Users can select one of several built-in colour themes (one of which approximates some kind of "night" reading mode), but this is a style "injection" mechanism implemented at the reading system level. There is no specific processing rule for authored alternate stylesheets, with or without class attribute tags.
See: https://github.com/readium/readium-shared-js/issues/71

**Comment by danielweck** [comment]
PS: as @laudrain said ( https://github.com/IDPF/epub-revision/issues/668#issuecomment-229970545 ), Mantano / Bookari supports any _titled_ alternate stylesheets in their Readium-based app, but I do not think that the standardized day/night/etc. restricted vocabulary (i.e. for the `link@class` attribute) is a core feature in their implementation. The whole point ; if I understand correctly ; was to demonstrate support for any _titled_ "class" of alternate authored stylesheet.

**Comment by mattgarrish** [comment]
It was resolved on the July 13 working group call not to enforce access to alternate style sheets, as this feature is only loosely supported right now and it is not clear that more widespread support is coming. Reading systems are not restricted from providing access if they choose.
