### ISSUE TITLE
The EPUB 3.1 spec should address common reader styling scenarios

### ISSUE THREAD

**Issue by ryanackley** [w3c/epub-specs#671]
As an implementor on the Readium EPUB viewer, one thing that was noticeably absent in the spec was how to handle reader preferences. 

For example these three things were configurable in the readium epub reader: font size, background color, and font color. 

There is no one way to deterministically set these properties in every epub content document. This is because the spec does not address this scenario in spite of almost every epub reader allowing users to change these styling properties. 

It's a matter of overriding the author's css which isn't incredibly difficult but there are many edge cases and it feels overall like a very hacky approach.

**Comment by dauwhe** [comment]
Are there issues with the CSS cascade and the concept of user styles which are inadequate to the task at hand?

**Comment by JayPanoz** [comment]
Hi there, just providing a small example of default CSS used for user styles you can find in a RS: 

```
  body {
    margin: {margin}px !important;
  }

  *, * *, *[class], *[class] *[class] {
    background: transparent !important;
    background-color: transparent !important;
    border-color: {foreground-color} !important;
    line-height: {line-height}% !important;
    text-align: none !important
  }

  html, html * {
    color: {foreground-color} !important;
  }

  a[href], a[href] * {
    color: {anchor-color} !important;
    text-decoration: underline !important;
  }
```

That is the most insane I've found for the moment—yep, we are indeed collecting RS' default CSS —but imho, we may have got a bigger than expected problem here… Or in other words, how can we even rely on the concept of cascade if RS are doing that?

**Comment by dauwhe** [comment]
I don't think there's anything we can do in the context of the 3.1 revision. Personalization on the web is a large problem, and will require coordination between CSS, the A11Y community, etc.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-06-24-epub#section3) on 2021-06-24

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

### 3. The EPUB 3.1 spec should address common reader styling scenarios 

_See github issue [#671](https://github.com/w3c/epub-specs/issues/671)._




**Wendy Reid:** i was looking through the issue list and we've only got a few issues still open  
… and most are still recent  
… this one we might be able to close after some brief discussion?  
… someone asked if spec could address common "reader styling scenarios"  
… so, if you have a library of ebooks, how to ensure consistency across that library  
… it's an interesting problem, but probably out of scope for the epub spec  

</details>
