### ISSUE TITLE
Introduce the end attribute of ANSI/NISO Z39.86-2005　

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#677]
Introduce [ the end attribute of ANSI/NISO Z39.86-2005](http://www.daisy.org/z3986/2005/Z3986-2005.html#End-Vals) 
for an additional control over the active duration.  This 
attribute is particularly useful for using MO for examinations.  

Since the end attribute is a bit complicated, we might want 
to simplify it.

**Comment by danielweck** [comment]
The EPUB Media Overlays specification normatively references the latest version of SMIL (v3):
http://www.idpf.org/epub/31/spec/epub-mediaoverlays.html#sec-overview-relationship

There is actually a DAISY Profile:
https://www.w3.org/TR/SMIL/smil-daisy-profile.html#DaisyProfileNS-TheModules

See how the `EventTiming` and `MultiArcTiming` modules (and "syncbase" timing) are used to express complex timing and synchronisation relationships:
https://www.w3.org/TR/SMIL/smil-timing.html#Timing-EventsInteractiveTiming

...such as `DTBuserEscape; DTBuserResume(;childId-value.end + Clock-value)?`, as per the examples in the DAISY 3 specification (NISO Z3986-2005):
http://www.daisy.org/z3986/2005/Z3986-2005.html#End-Vals

So, here is my personal opinion about this issue (for what it's worth: I speak as a co-author of the SMIL standard, and as an implementor of reading systems and authoring tools):
I think that SMIL-in-EPUB (aka Media Overlays) should remain as simple as possible, because I believe that this is what made this functionality "instantly" popular among both reading system developers and content creators. Both `event` and `multiarc` timing are features that would require significant changes in existing reading systems implementations (i.e. a "proper" SMIL playback engine), and it would introduce quite a lot of complexity for production tools / human authors.

Unless this extra complexity is justified by strong use-cases, and backed-up by stakeholder votes, and supported by at least some kind of reference implementation...I would be in favour of rejecting this issue's proposal.

Thoughts?

**Comment by mattgarrish** [comment]
It was resolved not to add the attribute on the June 22 working group call. Closing this issue.
