### ISSUE TITLE
SVG Animation Elements and Animation event attributes

### ISSUE THREAD

**Issue by dauwhe** [w3c/epub-specs#694]
3.0.1 forbids these, but we're seeing some desire on social media for them to be allowed.

**Comment by TzviyaSiegman** [comment]
If the concern was a11y, let's look at https://www.w3.org/TR/svg-aam-1.0/

**Comment by mattgarrish** [comment]
No, it's been lack of support. Ric's addressed the problems previously in the forums:
http://idpf.org/forum/topic-2808

**Comment by Emasoft** [comment]
We need SVG and SMIL support as soon as possible.

**Comment by caraya** [comment]
@Emasoft 

SVG is already supported by the specification: [http://www.idpf.org/epub/31/spec/epub-spec.html#sec-core-media-types](http://www.idpf.org/epub/31/spec/epub-spec.html#sec-core-media-types)

Whether a vendor fully implements the specification is up to the vendor, not the IDPF

Chrome and Opera have deprecated SMIL. See this [blink-dev thread](https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/5o0yiO440LM%5B101-125%5D) for a longer reasoning and discussion. Although this may be less relevant to ebook readers than to browsers it is still important to consider.

We should look at the [web animation API](https://w3c.github.io/web-animations/) instead of SMIL. This will support both CSS and SVG animations in one API and it's currently touted as the replacement for SMIL.  
- [Support is not complete](http://caniuse.com/#feat=web-animation) according to caniuse
- [Demos](http://web-animations.github.io/web-animations-demos/#playback-control)
- [Polyfill](https://github.com/web-animations/web-animations-js)

**Comment by mattgarrish** [comment]
There's also a case to be made that since we're moving to an undated/unversioned reference to SVG moving forward, we should consider dropping this restriction since it's not clear what the future will hold both for animation and support.

**Comment by TzviyaSiegman** [comment]
@mattgarrish 's point about pointing to undated SVG is a good one. Removing the restriction seems logical, but I think we need to ask RS Devs if this is feasible.

**Comment by mattgarrish** [comment]
As resolved on the July 20 call, I made the following changes:

Added the following cautionary note to the start of the section (adapted from the old caution we had for html pre-recommendation):

> CAUTION
> Some features of SVG are not fully supported in Reading Systems, or supported across all platforms on which the Reading Systems run. When utilizing such features, Authors need to consider the inherent risks in terms of the potential impact on interoperability and document longevity.

I also removed this bullet from the restrictions:

> The [SVG] Animation Elements and Animation event attributes must not occur.

I'm less sure about the conformance bullet that said RS must support the SVG-dyanmic feature set minus the animation sets. I reduced it to this:

> It must support the language features of SVG that correspond to the feature string http://www.w3.org/TR/SVG11/feature#SVG-dynamic (see Feature strings) [SVG].

I was looking at SVG 2 and they've removed feature sets, so this won't age well. I'm not sure that we can remove it, though. Maybe it just attests to the inevitability of future spec maintenance. Any thoughts on this @rkwright? 

I also made a couple of minor fixes to change a section/appendix number references to titles.

I'm still going to put into final review, but feedback welcome.

**Comment by rkwright** [comment]
I would just remove the part about feature strings.  In the first place, I am not sure the browsers support it anyway. As @mattgarrish mentions, it may be removed.  Finally, the reading system has no control over it anyway.  
IMO, it's a rather dopey feature (sic) anyway.  What would be it be used for?  Who in the world (besides perhaps Ivan and myself) writes hand-crafted SVG like that?  :-) I wouldn't expect any authoring tool to generate it.

**Comment by mattgarrish** [comment]
It looks like a workaround approach to saying all of SVG has to be supported except the animations. I suppose it was awkward to reference out the unwanted features, but given that we're dropping the restriction, I'll change it to mimic the RS requirement we have for html.

> Unless explicitly defined by this specification as overridden, it must process SVG Content Documents using semantics defined by the [SVG] specification and honor any applicable User Agent conformance constraints expressed therein.

This should make it more future proof.

**Comment by TzviyaSiegman** [comment]
That wording is very clear. I like it.

**Comment by rkwright** [comment]
Works for me.

**Comment by mattgarrish** [comment]
I've updated the bullet as noted above:
https://rawgit.com/IDPF/epub-revision/master/build/31/spec/epub-contentdocs.html#confreq-svg-rs-behavior
