### ISSUE TITLE
The value of the version attribute in EPUB 3.1

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#695]
What should be the permissible value(s) of the version attribute 
of the package document?  In EPUB 3.0.1, the value of this 
attribute must be "3.0".

If the value of this attribute in EPUB 3.1 must be "3.1", existing 
EPUB publications will not conform to EPUB 3.1.  Thus, migration 
from 3.0.1 to 3.1 will not be easy.

If the attribute value must be "3.0",  should epubcheck 
enforce 3.1 requirements or 3.0.1 requirements?  Should we 
introduce command-line options for choosing one of the two?

**Comment by mattgarrish** [comment]
If I'm a vendor, or anyone downstream of the person who created the EPUB, how would I know how to validate such a file?

**Comment by murata2makoto** [comment]
Matt, I believe that everybody will assume 3.1.  This should work in 
most cases.  If switch or other features are found by epubcheck, 
we will try 3.0.1 next.  Alternatively, epubcheck might automatically 
switch from  the 3.1 mode to the 3.0.1 mode.

**Comment by mattgarrish** [comment]
But it's still a guessing game, and that worries me.

How do you know if the content is supposed to conform to 3.1 and you have to throw an error not to use removed features, or whether the content is supposed to be valid 3.0? There's nothing solidly "3.1" that is always guaranteed to be present.

Any tool that validates epub content using epubcheck is also now going to have to expose an option to flag validation because it won't be able to determine the correct version information from the content. How many users will understand what their supposed to do with such an option?

And how does a reading system implemented strictly to 3.1 handle 3.0.1 content that isn't distinguishable?

So long as 3.1 is not a superset of 3.0.1, leaving the version number unchanged is going to cause problems. Even if we were to return all the features and deprecate them, we're still going to cause problems for publishers because all their 3.0(.1) content will suddenly be filled with warnings.

I know there's a potential problem that a 3.0 reading system won't open a 3.1 publication, but maybe that's the problem we need to address.

It might have been more sensible to have the requirement be that a reading system must open any epub publication within the major version it supports (3.0, 3.0.1, 3.1, etc.). Then we wouldn't be stuck in this endless cycle of not being able to touch version numbers. The recommendation to open a higher version should only have applied to higher major revisions. It probably means we'd need to bring back the removed features and deprecate them, but that still seems like the safer more reliable option.

Anyway, I hope we'll get more input on this issue, as it's quite wide-ranging in its potential impact.

**Comment by murata2makoto** [comment]
I agree that guessing remains in rare cases and we need more input from publishers, content  aggregaters, retailers, and end-users.  But I am wondering what happened when we introduced FXL without changing the version attribute.

**Comment by mattgarrish** [comment]
It was a superset of functionality, so we didn't face the same issues with invalidating old content.

But we did have problems bringing it in and also "predefining" the rendition prefix. epubcheck initially was flagging the declaration as an error, so people were being forced to omit it and then discovered that some reading systems didn't recognize the properties without the declaration.

**Comment by TzviyaSiegman** [comment]
I must admit, I was really puzzled when I saw this issue opened. I am very
pleased that epubcheck is capable of validating multiple versions. If an RS
chooses not to support 3.1 (or aspects of 3.1), I don't think maintaining
the version number is the best way to control the problem. If we don't
change the version number, I expect we will increase confusion about the
definition of "EPUB 3" and what RS do and do not support. From a developer
perspective, it will be more difficult to assess validation issues and
troubleshoot.
I am not sure that I understand the comment about FXL, as FXL is already a
part of the master spec.

**Comment by murata2makoto** [comment]
FXL was not a part of EPUB 3.0, but was introduced in EPUB 3.0.1.

**Comment by murata2makoto** [comment]
Tzviya, unlike you, I do not believe that the version attribute is good enough.

EPUB has several modules.  They are not integrated as part of EPUB 3.0 or 3.0.1 (or 3.1), but they are intended to be usable for EPUB 3.0/3.0.1 (or 3.1) publications.  Different modules (e.g. indexes) have different  schemas.  Different modules require different features of EPUB reading systems.  Thus, the version attribute is not good enough for  selecting appropriate schemas and determining which RS feature is required.

One could argue that we need more attributes for announcing which module is used.  But  I think that the best way is to examine the content of a publication.

This topic reminds me of some old debates about MIME parameters.  Some people would like to introduce more parameters about the content, while others would like to have parameters that are absolutely necessary.  The OWP is based on the latter opinion, as I see it.

CSS has many modules, but I am not aware of any mechanism for announcing which version of CSS and which module is used.   Browsers have to parse all CSS stylesheets and determine which module is used.

**Comment by mattgarrish** [comment]
None of the modular specifications is incompatible with the core, and we already have a way for identifying conformance for the ones that add content structuring requirements in the dc:type attribute.

The issue for 3.1 appears to be whether it can be a subset of 3.0.1 features and not change versions, but that doesn't look feasible for the reasons I mentioned above. Even as a continuation of 3.0.1 with a lot of deprecated features it doesn't look very feasible, as it will invalidate existing content.

We still have to respect that epub publications are aggregated and sold to consumers, and validation is not a personal experience like it is when you put content on your own web site. If content gets rejected because a validator is guessing wrong, or people don't know how to or can't validate properly to what vendors want, that has real world impact on livelihoods.

The reading system issue is still the big thing for me, and ibooks wouldn't open a file identified as version 3.1. A better kludge than content guessing or command-line flags might be to add a revision attribute. As painfully redundant as it is next to a version, at least it would provide clear separation and would avoid descending into the world of profiles.

**Comment by murata2makoto** [comment]
EPUB modules do not always provide authoritative flags in package documents.  EPUB indexes provide dc:type, but this is just a recommendation rather than a requirement.  Multiple renditions provide no such flags.

HTML 5 does not make <!doctype html> mandatory, although HTML 5 is not a superset of previous versions of HTML.  The new version of XAdES is not a superset of the old version of XAdES, but it does not provide any mechanisms for indicating the version.  I believe that the same applies to CSS3 (which has old versions).

I am not ready to argue about practical implications, since I have not discussed with Japanese IDPF member about this topic yet.

**Comment by mattgarrish** [comment]
The indexes spec doesn't require dc:type, but that's because it requires identification through the properties attribute on manifest items and/or a role on a collection. Indexes are also never invalid epub 3 content, which makes them a non-issue if you fail to correctly identify them. A validator can't guess when you intended to follow the spec, since the semantics are not required to be used according to the spec, and many can be implied. If it did, it would probably fail, too.

Multiple renditions isn't a useful comparison, as it was a mistake to do it as a separate specification in my opinion. But it's also reasonably easy to spot, unlike the changes we're talking about, as you'll always find the attributes on a rootfile. This is the difference I was getting at above when I said there is nothing reliably 3.1 that will always be present and that is a guaranteed indicator of which version to validate against.

The only additional comment I'll make on HTML validation is that an HTML validator doesn't have to comb through a package document and potentially dozens of content documents trying to find out a way to guess which version might have been specified. It's expensive and not guaranteed to get the right result.

If we have to hack a solution to keep a "3.0" version, I just want to make sure it's 100% reliable.

**Comment by murata2makoto** [comment]
How many EPUB3.0.1 publications use switch/trigger/binding elements?  I would like to know the answer.

**Comment by TzviyaSiegman** [comment]
A few more comments about the value of versioning in epubcheck:
As a publisher, I have thousands of books in my archive. I frequently receive queries about books published at some point in time. One of the first things I do is check which version of EPUB the file is (usually just by running epubcheck). This contextualizes the file for me and allows me to understand which spec-framework I'm working in without having to dig into or remember the nuances of each spec.  
As we shift from one version of EPUB to another, the version number helps me track information in an easy-to-use format. I can inform a system that the files with one number have already moved into the new spec and the files with another number are not yet there. I can essentially build workflow tools around one digit in the files instead of searching for nuance.

**Comment by murata2makoto** [comment]
The history of XML 1.1 is relevant.  XML 1.1 is to XML 1.0 what EPUB 3.1 is to EPUB 3.0.1.

XML 1.1 was a tough sale.  It has some advantages, but no big players cared.  As a result, W3C gave up XML 1.1 and created the 5th edition of XML 1.0.

EPUB 3.1 has some advantages over EPUB 3.0.1.  In particular, switch/trigger/binding is guaranteed to be non-existent.  But these advantages are not significant enough for most users, as I see it. If some (most?) implementations reject EPUB 3.1 publications, most users will stick to EPUB 3.0.1, and thus implementors will not be encouraged to support EPUB 3.1.

**Comment by dauwhe** [comment]
Tzviya and Matt make good points. I think the package version attribute in EPUB 3.1 should be 3.1.

**Comment by laudrain** [comment]
I agree.
Given backwards compatibility, EPUB3 production workflows by publishers will move to 3.1 ASAP.

**Comment by mattgarrish** [comment]
The working group resolved to keep the 3.1 identifier on the July 13.

Makoto did not agree with the decision.
