### ISSUE TITLE
EPUB Accessibility specification

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#711]
The EPUB working group has introduced the new EPUB Accessibility specification.[1]

This specification addresses two key needs in the EPUB ecosystem:
1. evaluation and certification of accessible EPUB Publications;
2. discovery of the accessible qualities of EPUB Publications.

The specification leverages the extensive work done in WCAG 2.0 to establish benchmarks for accessible content. The same four high-level content principles ‒ Perceivable, Operable, Understandable and Robust ‒ are central to creating accessible EPUB Publications.

Feedback about this new specification can be provided as comments to this issue.

[1] http://www.idpf.org/epub/a11y/

**Comment by GeorgeKerscher** [comment]
The accessibility working group for the EPUB Accessibility Conformance and Discovery Specification will monitor the comments on this issue (711) and create necessary issues to track.

**Comment by BenSchroeter** [comment]
"If a metadata record is provided separately from the EPUB Publication (e.g., for ingestion into a vendor system), the record MUST include any corresponding accessibility metadata expressions the format allows." This requirement is restrictive for attempts to remediate content downstream once it has been distributed by a publisher into the wild. Because accessibility metadata can be described in more that one source, e.g. content document and ONIX, would prefer an instruction that in cases of conflict, content metadata trumps any metadata provided separately.

**Comment by mattgarrish** [comment]
There are two problems I see: one is that epub now gives precedence to linked records over internal metadata, which we can't override, and the other is that it's hard to enforce requirements on records that are outside the scope of the publication itself (i.e., that don't even have a link in the metadata). I think we need to spend some more time on records.
