### ISSUE TITLE
Issues with epubReadingSystem object

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#716]
From Daniel Glazman:

The "layout-changes" feature covers far too much scope. The layout for a given element can be drastically changed modifying a class, any attribute, the style attribute, it can even be modified inserting elements before that element or directly tweaking the stylesheets.

In that light, chances are reading systems will always reply true to this if scripting is allowed. If they always reply true, querying that feature is useless.

Similarly, the dom-manipulation feature will always be true if the spine-scripting feature is true because if you can't manipulate the DOM from script, scripting is pretty useless...

(Repetition of issues #691 and #692 elided.)

All in all, |hasFeatures()| seems to me completely useless. My recommendation is simple: drop it. But wait, in that case, |epubReadingSystem| exists only to give us |name|, |version| and |layoutStyle|. Is it really worth it then? Do we really need the bloat of an extra global JS object for that and don't we already have stuff for that in the |navigator| object anyway?

**Comment by danielweck** [comment]
The only use of `navigator.epubReadingSystem` that I am aware of is for EPUB scripted content documents to perform the equivalent of "browser sniffing", for example to detect when the ebook is rendered with either iBooks, or Readium, etc. based on `navigator.epubReadingSystem.name` (akin to checking information contained in the `navigator.userAgent` string), in order to implement subtle script/styling tweaks depending on the host e-reader.

We probably don't want reading systems to mess-up with the `userAgent` string, so I think it is best to keep `navigator.epubReadingSystem.name` and `navigator.epubReadingSystem.version`. As for `hasFeature` and `layoutStyle`, I already expressed concerns in separate issues:

https://github.com/IDPF/epub-revision/issues?q=is%3Aissue+is%3Aopen+label%3ACat-ReadingSystemObject

**Comment by danielweck** [comment]
sorry, wrong issue!

**Comment by mattgarrish** [comment]
Marking this as deferred from 3.1 after discussions about the other issues. Whether to drop the RSO object from a future epub will be returned to.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-04-08-epub#section3) on 2021-04-08

List of resolutions:

- ***[Resolution No. 1](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-04-08-epub#resolution1):  Flag appendix A as at-risk, keep as a normative requirement and test implementation, remove the WebIDL***

<details><summary><i>View the transcript</i></summary>

### 3. WebIDL/epubReading System 

_See github issue [#1610](https://github.com/w3c/epub-specs/issues/1610), [#1420](https://github.com/w3c/epub-specs/issues/1420), [#716](https://github.com/w3c/epub-specs/issues/716)._




> *Wendy Reid:* See [relevant section in the core spec](https://www.w3.org/TR/epub-rs-33/#app-epubReadingSystem)

**Ivan Herman:** we have a separate section with a small webIDL describing the RSO  
… i have two questions  
… first, should it be normative? (it currently is)  
… second, if normative, we may run into the problem that webIDL is considered by browser implementors as something they have to implement  
… other specs I've worked on have used webIDL, and it has gotten us into trouble  
… I'd prefer to avoid this if possible  
… the spec also calls it a JS epubReadingSystem object, but webIDL is supposed to be language independent  

**Dave Cramer:** is there something in W3C policy that says if you use webIDL then all browsers must implement it?  

**Ivan Herman:** no, BUT i'd rather not get into this type of discussion about down the line  
… some other people might disagree with me and say that implementation is required. We do not want this discussions with the AC at voting time.  

**Brady Duga:** i think webIDL is for things intended to be implemented by browsers  
… but it does seem to be a normative requirement because of statements that we make later on in the appendix  

**Wendy Reid:** can someone please explain the importance of webIDL?  

**Brady Duga:** we were just trying to describe the RSO stuff using webIDL  

**Tzviya Siegman:** one of our goals is the define the role of the RS more clearly, and I'm not sure that this section does that?  

**Dave Cramer:** I think it does, webIDL is the industry standard for describing APIs  

**Garth Conboy:** maybe we can just describe it in JS?  

**Ivan Herman:** I think yes  

**Garth Conboy:** so webIDL might be fine to use, but if JS is also fine to use, then maybe we can resolve this small thing by just using JS  

**Matt Garrish:** some time back there was also discussion about maybe dropping RSO entirely...  

**Ivan Herman:** if we turn that section into informative only, then that allows us to bypass formal objections down the line?  

**Dan Lazin:** are we currently just discussing the question of how to DOCUMENT RSO? And how widely implemented is it?  

**Dave Cramer:** some do, some don't  

**Garth Conboy:** do we care about the requireness of this given that support isn't unanimous  

**Brady Duga:** not sure how common this is. We should write a test and try it in some RSes  
… has anyone in this call implemented it?  
… yes it is normative now, and there are MUST statements that point to this, but on the other hand we might spend a lot of time on this only to find out that no one really uses it  
… if no one implements this, then we can decide whether to drop it or make it non-normative etc.  
… and publishers should tell us if they use JS in their epubs, and if yes, then have they relied on this being available  

**Dave Cramer:** we've used this because of the state of epub interoperability  
… we use this to figure out which RS our epub is in  
… e.g. UA sniffing  

**Dan Lazin:** speaking of interop, one of the testing questions is: When we identify that not RS currently supports, e.g. Opus, does that mean that it ought not to be a core media type?  
… my feeling is that giving guidance on where we want to go is a pathway towards future interop  
… but when we mandate things that are not widely used, that leads RS implementors to not know what to trust  
… and I'm happy to write a test about this  

**Ken Jones:** a lot of FXLs with interactive content rely on scripting, so this is important  

**Dave Cramer:** it is possible to support scripting without relying on epubReadingSystem Object  

**Ivan Herman:** for now, do we say that this thing should be implemented by RS?  
… the other possibility is that we keep as normative requirement, but flag as at risk  

**Avneesh Singh:** +1 to ivan, flag at risk and keep as normative requirement for now

**Ivan Herman:** I'm leaning towards the second option, plus, rewording the section using JS  

> **Proposed resolution: Flag appendix A as at-risk, keep as a normative requirement and test implementation, remove the WebIDL** *(Wendy Reid)*

> *Garth Conboy:* +1

> *Gregorio Pellegrino:* +1

> *Brady Duga:* +1

> *Matt Garrish:* +1

> *Deborah Kaplan:* +1

> *Masakazu Kitahara:* +1

> *Avneesh Singh:* +1

> *Dan Lazin:* +1

> *Ben Schroeter:* +1

> *Matthew Chan:* +1

> *Ivan Herman:* +1

> *Tzviya Siegman:* +1

> *George Kerscher:* +1

> *Charles LaPierre:* +1

> ***Resolution #1: Flag appendix A as at-risk, keep as a normative requirement and test implementation, remove the WebIDL***

</details>

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-05-28-epub#section3) on 2021-05-28

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

### 3. Issues with epubReadingSystem object 

_See github issue [#716](https://github.com/w3c/epub-specs/issues/716)._




**dawhe:** not sure what problem we need to solve right now  

**Ivan Herman:** we have a resolution saying scripting is at risk. What more should we do at this point?  

**Dave Cramer:** we have learned that real -world support is spotty, so hard to address. Should we move on?  

</details>
