### ISSUE TITLE
is "widely implemented" problematic for css snapshot RS conformance?

### ISSUE THREAD

**Issue by mgylling** [w3c/epub-specs#723]
I have a question regarding bullet 2 in 5.3 RS conformance (https://rawgit.com/IDPF/epub-revision/master/build/31/spec/epub-contentdocs.html#confreq-css-rs-
modules).

Using "is widely implemented" here means that we will not have objective measurement capabilities and won't be able to validate RS conformance in this regard. What would happen if we simply removed "and are widely implemented" from the sentence? 

Ps. nit pick, but also perhaps the statement "that have reached Candidate Recommentation" should have an "at least" inside it. Ds.

**Comment by dauwhe** [comment]
My concern is that there is stuff in CR that's not widely implemented. For example, I don't believe any browser supports `break-*` properties, but the fragmentation spec is in CR. It's also common for CRs to have "at-risk" properties, which are at risk precisely because there are few implementations. 

So a spec having reached CR _and_ be widely implemented is a good signal that both the working group and the implementors agree on both the design and value of a feature. I agree that this is all difficult for objective measurement. I don't have a good answer for that right now.

**Comment by dauwhe** [comment]
New language decided in June 8 confcall, added via https://github.com/IDPF/epub-revision/commit/ce30ab72afc0fb4cda0dc36ed21eb542a819fb7e
