### ISSUE TITLE
Metadata for total number of pages in paper

### ISSUE THREAD

**Issue by laudrain** [w3c/epub-specs#726]
How to express the total number of paper pages like in the NCX <meta name="dtb:totalPageCount" content="128"/>. 
Simpler than finding the highest value of the nav page list.

**Comment by laudrain** [comment]
For the moment in 3.0.1, at Hachette Livre we ask EPUB3 supplier to add in the nav document
a tag meta with 
 name="schema:numberOfPages" content="194" 
Can it be a solution for 3.1?

**Comment by mattgarrish** [comment]
Are you asking to formalize this as a required piece of metadata?

Like any schema.org metadata, what you have above is valid right now for 3.0.1 and 3.1 using the non-OPF2 meta:

&lt;meta property="schema:numberOfPages">194&lt;/meta>

But is the number you add the aggregate of roman and arabic numbered pages, or just the highest arabic? Does the user want to know how long the body content is, in other words, or the whole book from cover to cover?

**Comment by dauwhe** [comment]
ONIX addresses this in insane detail. Are we aware of a situation where a reading system itself would need to have more information than schema:numberOfPages?

**Comment by laudrain** [comment]
My request is that the spec should recommend that the EPUB file contains an information about the overall number of paper pages, all included.
I think that the highest value in pageList isn't sufficient.

I know that ONIX delivers this information to retailers.
I know that schema:numberOfPages is valid in EPUB and this is what we, at Hachette Livre, ask our suppliers to insert in EPUB3 files.

But for RS, this could be the only direct information to the thickness of the book, the volume of content.

BTW, it was required in NCX :
**dtb:totalPageCount** 
Content: Non-negative integer indicating the number of pageTargets in the pageList. If there are no navigable pages, then dtb:totalPageCount must have a value of zero.
**Occurrence: Required**

**Comment by acabal** [comment]
Why not just infer the length of an epub by having the RS calculate a word count, or character count for non-markup text content, or perform some other calculation based on screen size?

I mean that's kind of what they already do already, right? If you read on a Kindle, it shows a percent complete; if you read on Play Books, it shows a progress bar; iBooks shows a page count; etc.  RS's seem to be managing just fine without explicit content length metadata.

**Comment by laudrain** [comment]
You are right, that's what a reading system do.
But the result may be far from the real total number of pages if the print book.
In case of illustrated books, word count may be very low for table books or children books, even null for Comics or Mangas.
I think we should ask accessibility WG?

**Comment by mattgarrish** [comment]
We could make it a recommendation when there is page-list, but in that case it probably belongs in the accessibility techniques document where including the source is mentioned. It's metadata that's only useful when certain conditions apply, not generally to all EPUBs.

**Comment by laudrain** [comment]
Ok for me, thanks
I consider this as a solution.

**Comment by danielweck** [comment]
For reference: https://schema.org/numberOfPages

**Comment by mattgarrish** [comment]
This issue was discussed on the accessibility call today, and it was pointed out that the NCX metadata was primarily for validity checking the page list, and it wasn't considered a critical piece of accessibility information to have.

A suggestion I made is that perhaps this belongs in the informative metadata properties document that we discussed in the metadata group. That way it would be generally identified for anyone who wants to include the information in an epub publication, without having to require it either in the core or in the accessibility techniques.

It would fit with our desired goal of not expanding the epub specifications with generally useful metadata.

**Comment by mattgarrish** [comment]
For example, see: https://idpf.github.io/epub-guides/package-metadata/

**Comment by laudrain** [comment]
Shouldn't numberOfPages be specified without a reference to "page break markers" in case of an EPUB without them?
I know "page break markers" are a must have for accessibility, but that metadata numberOfPages could be added even when the EPUB author cannot inserted "page break markers" in contents documents.
It could then be phased this way :
"The schema.org numberOfPages property provides the total number of pages of a statically paginated version of the content."

**Comment by mattgarrish** [comment]
Except that @TzviyaSiegman mentioned that they insert page breaks even without a static equivalent. Perhaps:

The schema.org numberOfPages property provides the total number of pages. This number typically represents the page break markers in the EPUB Publication, but may also indicate the page count of a statically-paginated version when markers are not included.

**Comment by laudrain** [comment]
Or we should perhaps not make any reference to page breaks:
The schema.org numberOfPages property provides the total number of pages. This number typically represents the page count of a statically-paginated version.

**Comment by mattgarrish** [comment]
Again, how does this add any clarity for the use case of page breaks in reflowable content without a print equivalent? It's a practice that is also mentioned in the accessibility specification.

**Comment by TzviyaSiegman** [comment]
proposed solution: recommend inclusion of schema:numberofPages in Accessibility Techniques when page-break/list exists

**Comment by mattgarrish** [comment]
We discussed this a few calls back and it's not a requirement for accessibility, that's why we thought it would be better in this metadata guide. (I think you might have missed that call.)

The disagreement Luc and I have is just how to describe what the page count represents. It could perfectly well be used to indicate the number of pages in an FXL publication, which isn't an alternative version.

To try again, would this work:

The schema.org numberOfPages property provides the total number of pages. This number represents a static page count that does not change based on the device or reading system used.

The number reflects one of: 1) the total number of pages in a fixed-layout publication; 2) the static page count from a print equivalent; or 3) the total number of static page break markers in a reflowable publication.

**Comment by TzviyaSiegman** [comment]
That works for me. I don't think we can make this a required property for 3.1 because of tendency to reduce metadata requirements. We can recommend in a11y techniques.

**Comment by mattgarrish** [comment]
No, it's not intended to be a requirement. This document was proposed as part of the metadata subgroup's work -- basically authoring guidelines. Because we've stripped out all the epub refinement metadata, we were going to provide an informative doc with common metadata that you can use to solve problems. I don't think we'd even mention it in the packages spec, or only as a note if we did.

For reference, see the discussion from March:
https://docs.google.com/document/d/1OoepgLPldn0V1dehA4ldzoJLeppQtfYkUQA3vUdOD8Y/edit#bookmark=id.pj19iug3ircc

**Comment by TzviyaSiegman** [comment]
Thanks for the reminder. Yes, it makes sense to add this to the informative document on metadata.

**Comment by laudrain** [comment]
Works well for me, thanks.
Perhaps just open the last paragraph as there may be more use cases in the future.
Like : 
"The number may reflect one of:"

**Comment by mattgarrish** [comment]
Sure, that's fine for me.

I'm going to take off the 3.1 timeline since this document is informative. I'll also create a new label for metadata authoring requests.

**Comment by mattgarrish** [comment]
Prose has been implemented here:
https://idpf.github.io/epub-guides/package-metadata/#schema-numberOfPages

Closing as resolved on the July 20 wg call.
