### ISSUE TITLE
Possibly add reference to DPUB A11Y Note

### ISSUE THREAD

**Issue by clapierre** [w3c/epub-specs#734]
EPUB A11Y Techniques
Helpful Resources

Should we maybe link to the DPUB A11Y Note here as well?
http://www.w3.org/TR/dpub-accessibility/

**Comment by TzviyaSiegman** [comment]
I don't think so because the DPUB A11y note does not provide solutions. It is written to highlight gaps in existing specs.

**Comment by mattgarrish** [comment]
That's why it's not mentioned now, as I'd see solutions implemented in W3C specifications and not needing mention. Or, if they need mention, we could add to the techniques as they become "doable".

Maybe we could mention it in the purpose and scope or about the techniques sections, in the context that there are other issues for which there aren't known suitable techniques.

**Comment by mattgarrish** [comment]
If we want to mention, I'd suggest a paragraph like the following be added to section 2, but let's discuss on the call next week:

This document does not address issues in digital publishing for which no solutions exist. The W3C's Digital Publishing Interest Group maintains a document of such issues at https://www.w3.org/TR/dpub-accessibility/. As solutions become available, they will be incorporated into the appropriate document, whether this one or one it refers to.

**Comment by clapierre** [comment]
I could go either way, bringing light to this document from EPUB accessibility spec couldn't hurt since we do mention EPUB in our Note was why I suggested this.

**Comment by clapierre** [comment]
Yes add this as a note in our spec

**Comment by mattgarrish** [comment]
Added note.
