### ISSUE TITLE
finish identifier scheme registry

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#754]
The metadata group needs to propose the short list of values for this registry:
http://idpf.github.io/epub-registries/identifiers/

Similar to #753, whether the attribute value should be case-insensitive also needs review.

**Comment by mattgarrish** [comment]
To kick this off, I assume the following are in since we often refer to them:
- ISBN (do -10, -13 or -A matter for reading system intepretation?)
- DOI
- UUID

Do we want a "proprietary" scheme, as well, just as a catch-all?

**Comment by laudrain** [comment]
ISBN as ISBN13 is sufficient for today production.
These 3 are enough for me.

**Comment by tkanai** [comment]
- JDCN (Japan Digital Comic/Contents Number)

Many Japanese Manga titles use JDCN as ID. According to some publications, the schema has been designed by [Digital Comic Association](http://www.digital-comic.jp/) in Japan, but I found no official documents in the web site. This [document ](http://www.pubridge.jp/bibli/pdf/common_bibliographi_seminar_store_20150410.pdf)(in Japanese) tells what is JDCN, but I'm not 100% sure whether the original spec more or not..

**Comment by tkanai** [comment]
- GUID ([Globally Unique IDentifier](https://en.wikipedia.org/wiki/Globally_unique_identifier))

Some who work for ebook aggregators told me that there are a number of epub publications saying the ID schema is GUID.  As GUID and UUID are not exactly the same, GUID should be in the list, I think.

**Comment by iherman** [comment]
Interesting re GUID. I must admit I have not met GUID in my practice so far; looking at the Wikipedia page I wonder whether the reason is that I am not a frequent Microsoft user... 

Also: per description, this is to identify _software_. Whether it is widely used for that purpose or not, I am not sure that is relevant for EPUB...

**Comment by laudrain** [comment]
Also GUID seems a variant of UUDI.
Then, as it clearly seems to identify software, I would not recommend it here.

**Comment by mattgarrish** [comment]
Yes, GUID v. UUID came up during development of another specification and UUID was the formal standard. We reference RFC4122 from a number of specifications, which itself states: "This specification defines a Uniform Resource Name namespace for UUIDs (Universally Unique IDentifier), also known as GUIDs (Globally Unique IDentifier)."

By referencing that RFC, is that enough encouragement to use a URN for these? We don't have to invalidate content without a urn:uuid: prefix, if that does exist. Looking at our specifications, I don't see any examples without the prefix, as we've been pretty consistent in following.

**Comment by tkanai** [comment]
I don't know why GUID is used for publication ID, but it is the fact. And we should list up any schemes which are used in existing epubs as much as possible, then let's start thinking how we should deal with them. Until then, we should not judge whether proposed schemes are good or not, because we don't have a concrete registration process yet, besides without understanding ID situation, we may not establish such a process.

**Comment by mattgarrish** [comment]
It's not a question of good, but of redundancy of registration since they are both defined from the same RFC scheme.[1] The only difference of note I can find is in the binary encoding of a GUID, but that's not applicable to epub.

[1] https://msdn.microsoft.com/en-us/library/cc246025.aspx

**Comment by laudrain** [comment]
Yes it's not a judgement... 
I propose that under UUID entry we add a note with GUID as a variant in the same RFC.

**Comment by laudrain** [comment]
Re JDCN, I've found so far that:
- It's 20 characters
- it starts with Publisher ISBN (2 to 7 digits)
- the publisher then complete with an internal identifier
- the last positon seems to be a control character (one digit or 'X' as in ISNI)

Takeshi, could you please have a look at the attached japanese doc : in page 10, there is a decomposition of JDCN in 7 parts.
[mailmagazine_vol.1_2.pdf](https://github.com/IDPF/epub-revision/files/438898/mailmagazine_vol.1_2.pdf)

**Comment by tkanai** [comment]
@laudrain 
It looks that JDCN itself does not say anything about the check digit and whether putting a control character or not depends on each house rule.
The decomposition in the page 10 is just an example, or a proposal, to tell how to build the house rule, but it is interesting for me that it tries to put digital comic "attributes" into the 20 character frames, so let me introduce. The below A-G corresponds to A-G in the page 10.
- A: Publisher ISBN
- B: ISBN publication element, or title element. JDCN recommends putting ISBN publication elements into JDCN, when an ISBN of original print edition is available.
- C:  Separation type. In general, a single volume of Manga title consists of several chapters, and this descriptor will say whether the digital edition is the same content with the print edition or a part of the print edition.
- D: Chapter number or story number. I assume this number is volume, or ISBN, independence, and the first story number of a publication will be assigned, when the title contains several stories in it.
- E: Color flag. This flag describes whether the ebook is colored or not. In general, print version of Manga is a black and white print. In digital, both black/white and color version of the same publication is available and I assume that this flag has been designed to tell them apart.
- F: Reserved area.
- G: Check digit.

**Comment by mattgarrish** [comment]
Is there an example jdcn identifier we can drop into the registry?

Here's how the registry looks so far:
https://rawgit.com/IDPF/epub-registries/master/registries/identifiers/index.html

**Comment by tkanai** [comment]
@mattgarrish 
I'm afraid both `urn:uuid` `urn:doi` are invalid as URN, because those namespaces have not been registered yet. See [URN namespace registry](http://www.iana.org/assignments/urn-namespaces/urn-namespaces.xhtml)

And if ID has been formatted in URN, the scheme should be `opf:scheme="urn"`.
Then the ISBN example is
`<dc:identifier opf:scheme="isbn">9780000000001</dc:identifier>`
or
`<dc:identifier opf:scheme="urn">urn:isbn:9780000000001</dc:identifier>`

And here is an examples of JDCN.
`<dc:identifier opf:scheme="jdcn">915869090000000000DD</dc:identifier>`

**Comment by mattgarrish** [comment]
UUID is listed there (fourth from last).

But, yes, I picked up the URN DOI examples from the specification forgetting that we have errata to fix. I'll correct.

The urn is a namespace on the identifier, so wouldn't you still identify the actual identifier scheme?

**Comment by tkanai** [comment]
Oh, my bad... It was too small to find out for my exhausted eyes..

The reasons why I would like to identify the actual identifier scheme are
1. To use the ID globally
2. To use the ID for scheme specific purpose.

To achieve #1, I think the ID should be written in IRI, or URI, and if `opf:scheme` says `urn`, we can use the given ID as is, but if it does not, we will need to convert it to IRI friendly syntax. Since each non-URN scheme has established on each specification, we might need to apply each conversion rule, and I think the value of `opf:scheme` will help how to convert it.  For example, DOI specifies how to convert DOI IDs into URIs, and we will need to concatenate `"http://doi.org/"` and given ID, so we need to identify the ID is DOI, and it should not be expressed as URN.
To achieve #2, we will need to convert any URN IDs into local identifies, but thanks to URN namespace, we can easily identify the scheme without any helps of `opf:scheme`, and use retrieved IDs for scheme specific purposes. As for non-URN IDs, we can use it as is, but need `opf:scheme` to do scheme specific things.

I might be missing something though...

**Comment by mattgarrish** [comment]
The reason we introduced identifier-type was to allow a reading system to look at it and determine what type of identifier was provided, regardless of whether it was encoded as a URN or not. That's why the specification says:

> To determine whether an identifier conforms to an established system or has been granted by an issuing authority, Reading Systems should attempt to parse the value of the element.

Having this secondary property was a fast way of knowing what type of identifier was inside. If we're pushing people to use URNs, it seems to diminish the point of having this attribute since it means having to parse the value anyway.

**Comment by mattgarrish** [comment]
Or maybe the answer to this is that we shouldn't show examples with URNs, and possibly recommend against using this attribute when a URN is used. That would at least be in keeping with this statement:

> For additional precision (e.g., if the scheme cannot be determined from the value or could lead to an ambiguous result),

**Comment by mattgarrish** [comment]
Anyone want to offer a tiebreaker opinion on whether the use of scheme should give preference to URNs or the actual identifier scheme?

**Comment by mattgarrish** [comment]
I'll add an open issue for the next release and we can continue discussions on this.

**Comment by mattgarrish** [comment]
We still need to wrap this issue up.

Is there a consensus we can come to on whether opf:scheme is the outermost scheme or the more precise identifier scheme?

@TzviyaSiegman @laudrain @iherman @tkanai @BillKasdorf ?

I can go either way on this since the specification recommends parsing the value, anyway. I'd just always interpreted its use as a hint at the identifier, not a precise statement about the encoding.

**Comment by TzviyaSiegman** [comment]
I also interpreted it as a hint at the identifier, not info about the encoding. Is this more of a question for how this is interpreted by RS?

**Comment by mattgarrish** [comment]
Yes, it seems to be a question of what the RS should assume when the attribute is present.

Should we ban the use of opf:scheme when the identifier is a urn? What about doi which has its own prefix? That would make it only useful for values that can't be parsed for meaning, which seems logical, but flaky to maintain.

Do we tacitly allow URNs but not call them out in the examples in the registry? Maybe add a note that the schemes are not needed, but can be used? (What is a doi without the prefix? Is that what we're encouraging?)

From an authoring perspective, letting people put these values on the identifiers regardless of URN/prefix/whatever seems like the simplest solution, and probably what is going to happen anyway. It means the reading system has to parse the value and see whether it is encoded as a URN, but doesn't authoring ease typically win out in these situations. I'm not sure the RS can avoid value parsing, even if it thinks the hint is reliable, and has to whenever a hint isn't there.

**Comment by laudrain** [comment]
I'll let it go for the more practical solution, a hint at the identifier.
Compatibility issues will make the RS parse the value anyway, I suppose.

**Comment by BillKasdorf** [comment]
That's how I interpreted it too, with the added clarification that I expect it to identify (ideally but not necessarily linking to) the authority. I think that's what Tzviya meant by "hint at the identifier" but I just want to be clear.

**Comment by iherman** [comment]
_Not_ to make the registry a hint would really make sense only if the registry was also machine readable, so that an RS could process the value of `opf:scheme` and the value of the original metadata automatically to yield a valid URI. I do not think we want to go down that route now. Ie, art this point, I believe our only option is to use the value of `opf:scheme` as a hint…

**Comment by mattgarrish** [comment]
I think we'd also have to enforce syntax so that the values are predictable. That seems deeper into these identifiers than we want to go.

**Comment by mattgarrish** [comment]
What I've done is add examples of both urn: and non-urn: identifiers to the registry.[1] I also changed the example in the specification to show the attribute used with an ISBN value that isn't a urn:.[2]

That way we better match the recommended usage for additional precision without ruling out any cases.

I'm going to close this issue now, but feel free to open a new issue if you spot anything else.

[1] https://rawgit.com/IDPF/epub-registries/master/registries/identifiers/index.html
[2] https://rawgit.com/IDPF/epub-revision/master/build/31/spec/epub-packages.html#attrdef-opf-scheme
