### ISSUE TITLE
Superseding Open Container Format (OCF) 3.0.1 

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#757]
What does the sentence "This specification supersedes Open Container Format (OCF) 3.0.1 " in OCF 3.1 mean?   In my understanding, IDPF does not intend to withdraw EPUB 3.0.1.  Existing EPUB publications will continue to conform to EPUB 3.0.1 and thus OCF 3.0.1.  

I checked HTML5, but it does not say anything about superseding.

**Comment by mattgarrish** [comment]
It's boilerplate that's been included in all the specifications since at least 3.0. There's no special meaning attached to the word: "take the place of (a person or thing previously in authority or use); supplant." Its value is really only to provide a link back to the previous recommendation and set up the link to the changes document.

I'm fine with dropping the whole paragraph, as we've added links to the previous recommendation and changes and issues to the top.

**Comment by mattgarrish** [comment]
Proposed Solution:

Remove the sentence about superseding as there is already a link to the previous recommendation.

Leave the link to the changes document, as it is more human readable than the github links.

**Comment by rdeltour** [comment]
Sounds wise to me, especially given the loaded "superseded" meaning for spec features.
