### ISSUE TITLE
A document "has" a media type, not "is"

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#760]
In the terminology section of EPUB 3.1 it says, for an 'EPUB Content Document':

> “An EPUB Content Document is a Core Media Type”

But a document is (usually) not the media type, but _has_ a media type. The same comment applies for the term 'Foreign Document'

**Comment by mattgarrish** [comment]
I agree, but I think the problem is that the references to the terminology are inaccurate so the wrong labels have been output. It should say "An EPUB Content Document is a Core Media Type Resource". (Although, technically we could correct either way.)

The usage in Core Media Type Resource is clearly wrong, as it should say "A Publication Resource that has a Core Media Type".

The Core Media Type definition used to say "set of" so it looks like it's been used as a kind of entity to which things belong in places. I'll do some deeper digging into the use of these two terms across the specifications.

**Comment by mattgarrish** [comment]
Proposed Resolution:

Review terminology references to "Core Media Type" for instances that should point to "Core Media Type Resource" as noted above.

Correct valid references that state "is a" to "has a".

**Comment by iherman** [comment]
> Review terminology references to "Core Media Type" for instances that should point to "Core Media Type Resource" as noted above.
> 
> Correct valid references that state "is a" to "has a".

+1
