### ISSUE TITLE
unique-identifier required?

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#766]
(This may be too late at this stage, it is fine if you guys decide to just close this without further action.)

Why is the unique-identifier attribute required in the package element? It strikes me as being unnecessary if there is only one occurrence of the dc:identifier element in the metadata...

**Comment by mattgarrish** [comment]
I think we close without action.

The counter argument I suppose is that you have to look at the package element to see if it's there since you don't know how many identifiers are present, so why not just make it required. Otherwise, you still have to count and then go back if you discover more than one.

I'll let the chairs make the final decision, though.

/cc @TzviyaSiegman @GarthConboy @mgylling

**Comment by iherman** [comment]
Any duplication is a source of error, though

**Comment by mattgarrish** [comment]
Authoring error, yes, but the package document is geared more at reading system efficiency. I doubt the original decision was made for authoring ease.

**Comment by iherman** [comment]
As I said, I won't lie down the road on that one:-)

**Comment by mattgarrish** [comment]
Sure, and this is a case where I'm arguing for something I have no real heart for.

Practically, I wonder what removing would do to older reading systems. I expect they have to error recover for the attribute not being present, but I've never checked to see how draconian they are about such an omission. That's more my hesitation.

**Comment by iherman** [comment]
I understand your hesitation. Let us see what our brave chairs tell us! :-)

**Comment by TzviyaSiegman** [comment]
This does seem like an extra step, but I would like to ask the RSs. @GarthConboy @rkwright @rickjohnson

**Comment by rkwright** [comment]
Well, the Chrome extension parses for the unique-ID but doesn't complain if it isn't found.  OTOH, the SDK parses for it and DOES complain if it isn't found 
![missing-id](https://cloud.githubusercontent.com/assets/3025864/17815997/8bf5acbe-65fc-11e6-9fa6-ba54fccb7d7a.png)

But that's easy enough to change.  Moreover, we don't USE it for anything, we just complain if it isn't there.

In any case, if I understand the proposal is to simply remove the reference in the package element, not the identifier, correct? Because we DO use the dc:identifier, in the library implementation to identify duplicates, etc.

So I am fine with removing it from the package element, but not the requirement that there be a dc:identifier.

**Comment by mattgarrish** [comment]
Right, we're not taking out the requirement for at least one identifier.

unique-identifier would just become an optional attribute. If not present, use the first identifier in the metadata.

**Comment by tkanai** [comment]
@rkwright I'm afraid Readium and almost all RSs use the ID to de-code obfuscated fonts, and I assume they use unique-identifier attribute value to look for a key for the decoding.

**Comment by GarthConboy** [comment]
Indeed Takeshi is correct -- clearly needed for obfuscated fonts.

**Comment by mattgarrish** [comment]
Looks like a case of good idea, wrong time. I'm going to take off the 3.1 timeline but leave open as deferred.

**Comment by mattgarrish** [comment]
Given our mandate not to introduce any potentially backwards-incompatible changes, I believe we can close this issue.
