### ISSUE TITLE
Usage of fragment id in <link> elements

### ISSUE THREAD

**Issue by iherman** [w3c/epub-specs#769]
3.4.5. of the package document says:

> Linked resources are not Publication Resources and must not be listed in the manifest. A linked resource may be embedded in a Publication Resource that is listed in the manifest, however, in which case it must adhere to Core Media Type requirements [EPUB 3.1](e.g., an EPUB Content Document could contain a metadata record serialized as [RDFa 1.1] or [JSON-LD]).

Maybe we can recommend to use a fragment ID to identify the element within the, say, HTML file (when appropriate, e.g., when JSON-LD is used in a `<script>` tag), rather than referring to the HTML file only.

Note that if this is accepted, this has an effect on another item. 3.4.10. 

> The IRI value of the href attribute may have a fragment component to indicate that only a portion or subset of a resource is included in the collection.

which is described as a difference between the usage of `<link>` in collections, and this difference may fall.

**Comment by mattgarrish** [comment]
You can use a fragment identifier without any change to the current prose. This example from 3.0.1 shows an example for the deprecated xml-signature property:

``` HTML
<link refines="#meta-authority-01" rel="xml-signature" href="../META-INF/Signatures.xml#MAI-Signature"/>
```

The collection element use is special, as it's the link element used outside of the metadata element, so I don't think we should change it. The difference is that the collection element might not be referring to the specified element in the same way. In the previews specification, for example, a fragment identifier means all content up to, but not including, the referenced element is included in the preview. Each collection can make its own rules about what the fragment means.

What about adding a new example that shows a reference to an embedded metadata record using a fragment identifier? Or do you still want a recommendation that when a specific container element can be referenced, that it be referenced?

I'm not against such a change, but inevitably it will fall into the machine-untestable bucket.

**Comment by iherman** [comment]
1. I may not have been clear; I knew that fragment identifiers were valid for the `link` element; my goal was rather to draw attention on the fact that addressing a `script` element directly, ie, using a fragment ID, that would include metadata in the form of JSON-LD may be a good idea because it may not be obvious to everyone. (And the text even refers to the fact that one links to the HTML file though processors extract metadata from those files.) Ie, if you add an example, as you propose, making such a link, that is perfectly fine with me and answers my comment.
2. However, I still do not understand what makes the `link` element special in the collection context. The text simply refers to the fact that a fragment id can be used, and that does not seem to be a differentiating factor.

**Comment by mattgarrish** [comment]
It's called out because of the potential for non-standard meanings of the fragment, but I'll concede that's maybe not clear in the wording. A fragment identifier in the metadata link always identifies the specific component or portion related to the relationship, but in the case of collections it's interpretive what the fragment signifies.

A better wording might be:

If the IRI value of the href attribute has a fragment identifier, the identifier does not always indicate that the referenced portion or subset of the resource is included in the collection. Specific implementations MAY define alternative meanings.

But the more I look at it it seems like a lot of verbiage just to handle previews. We do say below that specific implementations can tailor the requirements to their own purpose, which is probably enough. I'm in a throwout-y kind of mood today, anyway.

**Comment by mattgarrish** [comment]
Proposed Solution:
- Add an example showing a reference to an embedded metadata record
- Remove the bullet about allowing the use of a fragment identifier in collection links
