### ISSUE TITLE
Catastrophically?

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#779]
What does this sentence mean?

> It must not fail catastrophically if it encounters two distinct EPUB Packages with the same Unique Identifier.

I would like to drop this sentence, because implementors can always argue that their RSs do not fail catastrophically.

**Comment by mattgarrish** [comment]
It's a legacy statement from 2.0, but it has always struck me as cautioning that the device shouldn't explode in the user's hands.

It's a bit of an oversimplification of the issue, too.

It's perfectly valid to encounter two publications with the same unique identifier, or two renditions. The bigger question is whether they represent the same publication or not, or the same version of the same publication and how the RS should handle this (separate entries in the bookshelf, update in place, something else).

Developers already need to be aware of this situation and account for it, so we'd need more guidance than just to "not fail" if we want to handle it properly.

**Comment by mattgarrish** [comment]
This really boils down to an error handling statement, and I doubt any reading system developers are relying on the uniqueness of the unique identifier across publications given that it cannot be ensured. (It's kind of a worthless value because we can't guarantee uniqueness, but that's a topic for another day.)

Maybe the proposal here should be to delete the bullet and add a paragraph like the following to the end of 4.1.1 Unique Identifier in the Packages spec:

Reading Systems MUST NOT depend on the Unique Identifier being unique to one and only one EPUB Publication. Determining whether two EPUB Publications with the same Unique Identifier represent different versions of the same publication (see Release Identifier), or different publications, might require inspecting other metadata, such as the titles or authors.

But I can also live with just deleting the bullet.

**Comment by mattgarrish** [comment]
Proposed Solution

Delete the bullet about not failing catastrophically.

Add the following paragraph to the end of the unique identifier section:

"Reading Systems MUST NOT depend on the Unique Identifier being unique to one and only one EPUB Publication. Determining whether two EPUB Publications with the same Unique Identifier represent different versions of the same publication (see Release Identifier), or different publications, might require inspecting other metadata, such as the titles or authors."
