### ISSUE TITLE
RSs must not support refines?

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#787]
In Annex A of EPUB 3.1, the 3rd bullet for "superseded"

> Reading Systems must not support the superseded feature in content that conforms to the current version of the specification.

I disagree strongly.  RSs should be allowed to support them.

**Comment by mattgarrish** [comment]
Recommend closing this without any change. Superseded is for features like the NCX in 3.0.1. Reading systems should not support features that only exist for compatibility in older reading systems, otherwise why remove the features at all?

By changing refines to deprecated, we don't have any remaining superseded features. If there is a real need to change support in the future, we can revisit at such time.
