### ISSUE TITLE
EBNF syntax: question mark

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#815]
[EBNF in Packages 3.1](http://www.idpf.org/epub/31/spec/epub-packages.html#sec-property-syntax) uses the question mark.  It is used to reference some set of string, which are defined elsewhere.  But few people know what the question mark means.  Some note would help.

**Comment by mattgarrish** [comment]
The web abounds in information about what ebnf symbols mean. If someone doesn't know, I'm sure they can find a wikipedia page or similar very easily. Otherwise, why draw the line at question marks? I'm sure the use of square brackets, parentheses and curly brackets will be confusing if you don't know the syntax, too.
