### ISSUE TITLE
Why mention nav without mentioning cover-image in Publications 3.1?

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#816]
Drop this sentence from Pub 3.1.

> Exactly one item must be declared as the EPUB Navigation Document using the nav property.

**Comment by TzviyaSiegman** [comment]
`<item properties="cover-image">` is optional. See http://www.idpf.org/epub/30/spec/epub30-publications.html#sec-item-property-values.

**Comment by murata2makoto** [comment]
I understand that cover-image is optional.  But I would argue that it should be mentioned if nav is mentioned.

Perhaps,

> At most one item must be declared as the cover image using the cover-image property.

**Comment by mattgarrish** [comment]
The entire paragraph before the sentence you wanted to drop is about descriptive properties, and includes a link to the manifest vocab. That seems plenty for optional properties.

The only one that has to be specified in every package document in order for the publication to be valid is "nav". That's why it's the only one called out.
