### ISSUE TITLE
Resolving reserved prefixes

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#819]
I don't understand the third para of [4.2.3 Reserved Prefixes](http://www.idpf.org/epub/31/spec/epub-packages.html#sec-metadata-reserved-prefixes)

> Reading Systems must resolve all reserved prefixes used in Package Documents using their pre-defined URIs. Reserved prefixes should not be overridden in the prefix attribute, but Reading Systems must use such local overrides when encountered.

Consider prefix="a11y: http://www.example.com".  Then, will the prefix a11y resolve to "http://www.example.com" or "http://www.idpf.org/epub/vocab/package/a11y/#"?  In my intepretation, the first sentence implies the latter, while the second sentence implies the former.

**Comment by mattgarrish** [comment]
Does this help:

Reading Systems must resolve all reserved prefixes used in Package Documents using their pre-defined URIs _unless a local prefix is declared_.

The issue is that a reserved prefix can be introduced that conflicts with a prefix someone has already been using. In that case, the locally-defined prefix cannot be reinterpreted, as it would invalidate the original intent. If it resolves to the same URI, then there is no issue with a "redeclatation".
