### ISSUE TITLE
HTML Extensions and HTML Deviations

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#836]
[Extensions](http://www.idpf.org/epub/31/spec/epub-contentdocs.html#sec-xhtml-extensions) and [Deviations ](http://www.idpf.org/epub/31/spec/epub-contentdocs.html#sec-xhtml-deviations)sound similar.  What is not an extension but a deviation?

**Comment by mattgarrish** [comment]
I've never really cared for the dual names, but in this case deviation is being used in the sense of a departure from the fully-allowed standards that HTML references (MathML, SVG, Unicode). Constraints are on HTML itself (deprecated constructs, etc.).

An extension is not technically a deviation, since extensions are perfectly valid. A deviation is a change in a non-standard way.

I changed "Extensions and Enhancements" to "Extensions" in 3.0.1. In this case, if we change I'd suggest "HTML Restrictions" as a name as it generally encompasses both needs.

But I'm fine leaving it as is since it hasn't caused any real confusion to date.

**Comment by iherman** [comment]
Personally I do not find these terms confusing. I do not think there is a need for change.

**Comment by mattgarrish** [comment]
Stewing on this for a few days, I agree with @iherman. Let's stay the course and not change. We used those words for a reason.

**Comment by murata2makoto** [comment]
Are deviations restrictions on embedded MathML and SVG?  If so, I would like to have 2.4. HTML Extensions, 2.5 Restrictions on embedded MathML and SVG, and 2.6 HTML Restrictions.

**Comment by mattgarrish** [comment]
How is restricting mathml and svg, which are part of the grammar, not restricting html?

This kind of change also takes rewriting the content and rs conformance requirements.

Again, not worth the effort, IMO.

**Comment by mattgarrish** [comment]
Closing this issue without action.
