### ISSUE TITLE
Encourage use of UTF-8

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#839]
In section 4.3, why UTF-16 ? I think a Note encouraging UTF-8 only, as in the html spec, could be VERY useful for the future of EPUB.

(Submitted by Daniel Glazman)

**Comment by TzviyaSiegman** [comment]
+1

**Comment by mattgarrish** [comment]
utf-16 is mentioned because of its allowance in xml.

The recommendation to use utf-8 for html applies to content documents whatever we say, since that guidance is more specific to their production.

We don't have a lot of custom xml grammars that this applies to. At the same time, recommending utf-8 isn't likely to harm anyone.

Here's some history on the decision:
https://github.com/idpf/epub-revision/issues/50

**Comment by tkanai** [comment]
Could you tell me at where utf-8 is recommended in HTML5 spec? I can't find it.

One big advantages of UTF-16 is it would reduce epub file size. At least three bytes are required for expressing non-ascii characters, and four bytes are required for most of Japanese characters.  Since all web engines and OSs support both utf-8 and utf-16, I can't find any reasons to drop it at this time.

**Comment by mattgarrish** [comment]
From what I see, Daniel was referring to the "should" in 4.2.2.5.[1] The "[ENCODING]" document that is referenced at various points also calls UTF-16 a legacy encoding and recommends UTF-8.[2]

UTF-16 isn't disallowed in HTML, and wouldn't be here either. I'm assuming this is a request just to add an additional statement, like:

> It MUST be encoded in UTF-8 or UTF-16 [Unicode]. For future compatibility with the Open Web Platform, the use of UTF-8 is RECOMMENDED. [Encoding]

[1] https://www.w3.org/TR/html51/document-metadata.html#specifying-the-documents-character-encoding
[2] https://www.w3.org/TR/encoding/

**Comment by tkanai** [comment]
Thank you for the links. I don't think it is necessary to add the statement, especially at this time, because the future compatibility phrase is just out guess. 
Actually, it sounds to me like IDPF is planing to publish the next version of EPUB format and the use of UTF-16 will be prohibited in it. Why don't we just rely on the W3C's spec and make EPUB 3.1 spec maintenance free (as much as possible)?

**Comment by mattgarrish** [comment]
This is why I'm not sure it's particularly relevant. The W3C document already guides their standards where it is referenced.

The XML section we have relates to all XML documents, so the package document, META-INF files, and NCX. I don't think there's anything else EPUB-specific that is guided solely by the section. None of those are really converging with the web in any meaningful sense. They'll be dropped or reformulated in any future integration.

The guidance also applies to XHTML, SVG and MathML to actively disallow other encodings, but if their respective specifications have guidance that says you should use utf-8 then that guidance prevails. So regardless of the fact that we allow XHTML documents to be utf-16 encoding, you could get a warning from an html validator that utf-8 is preferred.

I don't think it's worth doing anything at this point, to be honest.

**Comment by mattgarrish** [comment]
Closing this without action.
