### ISSUE TITLE
Allow multiple instances of dcterms:modified

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-specs#841]
I think it's a pity only one dcterms:modified META is allowed. Allowing multiple dcterms:modified META elements would allow the preservation inside a package of the history of changes and even provide the user with it if necessary.

(Submitted by Daniel Glazman)

**Comment by murata2makoto** [comment]
How do you construct Release Identifiers?  By using the latest modification time?

**Comment by mattgarrish** [comment]
Either the reading system will have to calculate which is the latest or we'd need requirements like the latest modified time must be listed first and reading systems must use the first one encountered.

I suggest we defer, as I'm sure there are better ways we could do revision histories. A date alone isn't going to be all that meaningful to a user.

**Comment by TzviyaSiegman** [comment]
I agree with @mattgarrish

**Comment by laudrain** [comment]
I don't think it is the place and time to manage revision history.
Yes let's defer.

**Comment by mattgarrish** [comment]
Since we've acknowledged that the release identifier hasn't worked out as expected, there's not a strong case to keep restricting dcterms:modified to a single instance.

This would also match the [dc guidance](https://www.dublincore.org/resources/userguide/creating_metadata/#Modified).

We may want to define the first in dom order as the last modification date, though, so it's not open to interpretation.

**Comment by OriKuttner** [comment]
But what about release identifier? I think we still need such identifier.

-- 
Ori Idan CEO Helicon Books
http://www.heliconbooks.com

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-03-04-epub#section2) on 2021-03-04

List of resolutions:

- ***[Resolution No. 2](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-03-04-epub#resolution2):  Close issue 841, will not change usage of dcterms:modified***

<details><summary><i>View the transcript</i></summary>

### 2. Allow multiple instances of `dcterms:modified` 

_See github issue [#841](https://github.com/w3c/epub-specs/issues/841)._




**Wendy Reid:** I believe the initial intent was to allow this to show progression of update to book  

**Matt Garrish:** yeah, a revision history  
… at the time we cared because of Release Identifier  
… but now it doesn't seem to matter as much  
… but if we have multiple, we should define which one is the last modified  

**Brady Duga:** I also don't really care, but what does this enable?  
… you can't add comments to these fields, so it would just be a bunch of ambiguous dates and times  
… not against removing restriction on only having one, but also not really any features that would benefit from doing so  

**Wendy Reid:** in practice, one thing that I've seen publishers do is track the version of the epub on the copyright page  

**Dave Cramer:** all the big trade publishers do that  
… ours is a long string that is unintelligible to outsiders  
… and we'd keep doing this regardless of changes to this field  

> **Proposed resolution: Close issue 841, will not change usage of dcterms:modified** *(Wendy Reid)*

> *Brady Duga:* +1

> *Matthew Chan:* +1

> *Masakazu Kitahara:* +1

> *Matt Garrish:* 0

> *Wendy Reid:* +1

> *Toshiaki Koike:* +1

> *Marisa DeMeglio:* 0

**Wendy Reid:** mgarrish please feel free to refine the language  

> ***Resolution #2: Close issue 841, will not change usage of dcterms:modified***

</details>

**Comment by iherman** [comment]
@mattgarrish, @wareid  it was not clear to me from the minutes if there is an editorial change to do on this based on the discussion, so I did not close the issue. If there is no change to do, one of you can close it I guess...

**Comment by mattgarrish** [comment]
No, there was just a general comment from @wareid that if I see anything in the section that could be improved to feel free to fix. I think it's fine as-is for having only one value.
