### ISSUE TITLE
Content documents cannot allow anything

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-specs#853]
Look at the two sentences  "It must allow ...",  where "It" refers to an XHTML content document.  I don't think that content documents can allow something.

http://www.idpf.org/epub/31/spec/epub-contentdocs.html#confreq-html-microdata
http://www.idpf.org/epub/31/spec/epub-contentdocs.html#confreq-html-rdfa

How about "It MAY contain.."?

**Comment by mattgarrish** [comment]
Does that mean it may contain attributes that don't conform to the standards?

Those two specifications also change the HTML content model -- allowing meta and link in the body when certain attributes are used on them, for example. I don't think the change fully captures that.

I'd suggest that we drop "content conformance" and instead list each technology as a subsection:

> 2.4.2.2 RDFa
> 
> The use of [RDFa 1.1] attributes is allowed in XHTML Content Documents, but any usage MUST conform to the requirements defined in [HTML+RDFa11].
> 
> The [RDFa 1.1] specification defines changes to the HTML content model when RDFa attributes are used. This modified content model is valid in XHTML Content Documents.
> 
> 2.4.2.3 Microdata
> 
> The use of [Microdata] attributes is allowed in XHTML Content Documents, but any usage MUST conform to the requirements defined in that specification.
> 
> The [Microdata] specification defines changes to the HTML content model when Microdata attributes are used. This modified content model is valid in XHTML Content Documents.

**Comment by iherman** [comment]
@mattgarrish I like your formulation. It makes it much clearer indeed.

The only question, though: in contrast to HTML, the Microdata document also defined additional DOM API-s. One could ask: _if_ the RS implements the DOM then should it also implement the Microdata DOM API-s? Note that, afaik, no browser implements those API-s and it is exactly that missing implementation that pushed the Microdata spec into a Note instead of a Recommendation.

My proposal is to make it clear that the DOM API for Microdata is not required even if the RS implements the DOM.

**Comment by mattgarrish** [comment]
Yes, we tried to cover that in the final section about processing:

> Reading Systems may process [Microdata] and [RDFa 1.1] attributes as defined in their respective specifications, but such support is optional.

(Why it's titled "processing requirements" when there aren't any is odd, but anyway.)

If we separate the technologies, we could incorporate this statement into both sections for better transparency. So in Microdata it could state:

"Reading System support for the attribute processing model and DOM API defined in [Microdata] is OPTIONAL."

We could do similar for RDFa without the API reference:

"Reading System support for the attribute processing model defined in [RDFa 1.1] is OPTIONAL."

**Comment by iherman** [comment]
Not exactly... There is a difference between RDFa and Microdata. Sorry if I am a bit pedantic...
- RDFa 1.1 defines a processing model in great (and boring) details on how the HTML attributes are mapped onto RDF triples. So if a reading system understands the RDFa 1.1 attributes, then it has to follow that processing model. So far so good, it is what your text says.
- Microdata "sort of" defines a processing model but it does not separate it very well from the DOM API. In other words, at first glance, these two cannot be separated. But that is not absolutely true: the specification also includes an [appendix](https://www.w3.org/TR/2013/NOTE-microdata-20131029/#converting-html-to-other-formats) to extract the data and turn it into JSON. Furthermore, there is a [separate note](https://www.w3.org/TR/2014/NOTE-microdata-rdf-20141216/) on how the microdata syntax can also be converted into RDF, making it, essentially, a syntax for (a subset of) RDF. I believe that this part is useful. AFAIK, Schema.org uses this algorithm (or a version thereof) in processing microdata alongside the RDFa or JSON-LD encoding of Schema.org terms.

Ie: "Reading System support for the attribute processing model and DOM API defined in [Microdata] is OPTIONAL." is not really o.k., because it binds the two together. I would rather say something like

> Reading System support for the attribute processing model of [Microdata], as well its [Conversion ot RDF] is OPTIONAL. Furthermore, the DOM API of [Microdata] is also optional even if the attribute processing model is supported

(Or something like that...)

**Comment by mattgarrish** [comment]
Sounds good to me.

**Comment by iherman** [comment]
Modulo an update of my franco-hungarian dialect of English:-)

**Comment by mattgarrish** [comment]
Sure, quick assent on my way out the door. I see "conversion to RDF" in the description, but otherwise any changes should be cosmetic.

To compile, we'd replace the current section 2.4.2.2 and 2.4.2.3 with the following (actual reference locations might be adjusted by docbook output):

> 2.4.2.2 RDFa
> 
> The use of [RDFa 1.1] attributes is allowed in XHTML Content Documents, but any usage MUST conform to the requirements defined in [HTML+RDFa11].
> 
> The [RDFa 1.1] specification defines changes to the HTML content model when RDFa attributes are used. This modified content model is valid in XHTML Content Documents.
> 
> Reading System support for the [attribute processing model](https://www.w3.org/TR/2015/REC-rdfa-core-20150317/#s_model) [RDFa 1.1] is OPTIONAL.
> 
> 2.4.2.3 Microdata
> 
> The use of [Microdata] attributes is allowed in XHTML Content Documents, but any usage MUST conform to the requirements defined in that specification.
> 
> The [Microdata] specification defines changes to the HTML content model when Microdata attributes are used. This modified content model is valid in XHTML Content Documents.
> 
> Reading System support for the [attribute processing model](https://www.w3.org/TR/2013/NOTE-microdata-20131029/#encoding-microdata) is OPTIONAL, as is the [conversion to JSON](https://www.w3.org/TR/2013/NOTE-microdata-20131029/#json) [Microdata]. Furthermore, the [DOM API](https://www.w3.org/TR/2013/NOTE-microdata-20131029/#microdata-dom-api) [Microdata] is also OPTIONAL, even if the attribute processing model is supported.

**Comment by mattgarrish** [comment]
Proposed Solution

Rewrite the semantic inflection section as described in the previous comment.
