### ISSUE TITLE
Using HTML instead of XHTML?

### ISSUE THREAD

**Issue by jacqueslelezard** [w3c/epub-specs#883]
I was wondering is it _valid_ to create an epub with only HTML5 file instead of XHTML files since HTML media type is listed there as supported type [https://idpf.github.io/epub-cmt/v3](https://idpf.github.io/epub-cmt/v3) : `text/html` ?

For now (epub 3.0.1) an epub file with the TOC and a fallback in XHTML, and HTML files for content seems to be valid in epubcheck 4.0.1

**Comment by mattgarrish** [comment]
No, adding text/html conformant documents was under consideration for 3.1 (in the first editor's draft), but ultimately got rejected. The entry in the CMT table will be removed before we move to recommendation.

Any resource that isn't a core media type can be included in the spine with a fallback, so that doesn't change.

**Comment by jacqueslelezard** [comment]
Ok it has been rejected, I wasn't sure of that, thanks. So we _can_ use HTML but always with fallback.

**Comment by mattgarrish** [comment]
Yes, until epub 4 or portable web publications come along, it's unfortunately not possible to have text/html stand alone in the spine without a fallback.
