### ISSUE TITLE
A11y: Forced relationships section

### ISSUE THREAD

**Issue by bduga** [w3c/epub-specs#904]
In section 4.4.2.4: "The enhancements to Media Overlay Documents" What enhancements? There aren't even any new requirements. This section seems unnecessary. I assume it is here to match the structure of the document, but it seems like a forced section. I am not sure what information it adds.

**Comment by mattgarrish** [comment]
It's a compromise between adding stricter requirements -- which we shelved because production is non-trivial and they would invalidate otherwise-accessible publications -- and saying nothing. Some members of the group think it's important to highlight the features for those who don't read the MO spec closely.

I had suggested an informative appendix at one point. I'll raise it again with the group.

**Comment by mattgarrish** [comment]
The accessibility group decided today to address this by marking the section as informative, but leaving where it is.

**Comment by mattgarrish** [comment]
Further to my last comment, the intention is to add normative requirements in a next version, as indicated in the note in the section, and the group would prefer to keep the requirement front and center for producers who create media overlay publications.
