### ISSUE TITLE
[3.1] container.xml paths

### ISSUE THREAD

**Issue by therealglazou** [w3c/epub-specs#940]
Paths to renditions from the container.xml file are full paths from the toplevel directory of the uncompressed package. This is, AFAICT, the only occurence of full paths in the package while all other references are realtive URLs from one document instance to another one. From a coding perspective, it forces the UA to have a different treatment for resource references in container.xml. A regular `href` attribute would be better here...

**Comment by murata2makoto** [comment]
Absolute-path references (which begin with "/") are also relative references, as defined in RFC 3986.   I thus think they are allowed anywhere in EPUB.

Usually, it is a good idea to avoid absolute-path references, since they will not work after unzipping.  But it is hard to use container.xml after unzipping.

**Comment by mattgarrish** [comment]
And they're only effectively absolute paths because the base IRI is relative to the root.

Any change would seem to cause problems for opening in older reading systems, and would effect the resolution of all relative paths in all META-INF files, since the base IRI application is not limited to container.xml.

**Comment by therealglazou** [comment]
I am not saying we don't have a backwards compatibility issue if we fix full-paths. But full-paths are in container.xml are heterogeneous with the rest of a package. Seems to me this is something we want to keep in mind for next generation.

**Comment by mattgarrish** [comment]
Sure, it's one of the quirks of OCF. It's also not limited to container.xml or that one attribute:

> Unlike most language specifications, the Base IRIs for all files within the META-INF directory use the Root Directory of the OCF Abstract Container as the default Base IRI.

Beyond the reserved files, it seems to suggest that if you store any file that defines a different base IRI for resolution in the directory, that IRI is overridden by this rule, too.

I'd assumed this was inherited from odf packaging, but I don't see an equivalent there. I'd be happy to see it updated in a next gen. packaging spec, but had read this as for 3.x.

**Comment by dauwhe** [comment]
Consensus on the CG call today was that this can't be changed in EPUB 3.X due to compatibility issues.
