### ISSUE TITLE
Changes in... (3.1) Missing from new W3C site?

### ISSUE THREAD

**Issue by matt-curtis** [w3c/epub-specs#973]
How does this particular document fit into the new W3C site?

**Comment by mattgarrish** [comment]
The specifications I've been moving/converting are documents that are likely to be updated and released by the community group in the near future.

The 3.1 changes document has no specific future since it's specific to each revision. There might be parts of introductory material we pillage when we do a 3.1.1., but it'll be easier to start over from scratch than spend time converting a document that'll be almost whosesale thrown out.

That's assuming we continue the practice of a changes document in w3c, of course. I can't answer that question until we do a revision.

**Comment by matt-curtis** [comment]
OK. The changes in X.X.X vs. X.X.X document is/was incredibly useful, as otherwise one would be forced to manually review all of the specification in order to ascertain major changes. It would be a shame to lose it without further evaluation or a suitable replacement.

Thanks for the fast response and hard work.

**Comment by mattgarrish** [comment]
Closing this issue as there is a changes document in the 3.2 directory for the coming revision to capture all the updates.
