### ISSUE TITLE
Handling of multiple metadata elements

### ISSUE THREAD

**Issue by JayPanoz** [w3c/epub-specs#992]
I encountered quite a significant issue related to metadata when researching and documenting internationalization for Readium CSS. As far as I can tell, there is no guidance for some elements and it’s then up to Reading Systems to decide how they will handle multiple values.

I’ll be focusing on language but couldn’t review all elements so the issue may well apply to others.

Per spec, 

> Additional `language` elements may be included for multilingual Publications, but each element's value must conform to [RFC5646].

Turns out some authors and popular authoring tools got the message, and don’t hesitate to put every language the publication contains, even if it just contains one word in this language. But since handling of those multiple values is not explicitly discussed, Reading Systems don’t manage it the same way when they need to find the primary language of the publication. 

The “primary” issue is discussed for other elements though. For `creator`, you can indeed find the following in the [EPUB 3.0.1](http://www.idpf.org/epub/301/spec/epub-publications.html#sec-opf-dccreator) spec: 

> If no means of establishing the primacy of creators for rendering is identifiable, Reading Systems must use the document order of creator elements in the metadata section (i.e., where the first creator element encountered is the primary creator).

Back to language. Here is some simple case where the publication is english and hindi:

```
<metadata>
  <dc:language>en</dc:language>
  <dc:language>hi</dc:language>
</metadata>
```

Pick the primary language but please choose carefully as it will have a significant impact…

To sum things up, the Reading System won’t necessarily provide the user with the same user settings, depending on the language chosen: you’ll at least offer another selection of fonts in this case (latin vs. Devanagari), but you may also disable some user settings which don’t make sense for the Devanagari script and enable others e.g. a11y-related preferences. 

So if you don’t pick the correct one, the RS user settings won’t handle the publication correctly, and it will probably feel like a bug. 

This can escalate pretty quickly for authors and impact rendition as well. 

@BNGOBooks recently reported quite a bug in iBooks, in which [his EPUB3 file was rendered backwards i.e. as if it were a RTL script](https://twitter.com/BNGOBooks/status/944260033973506048). 

That’s because InDesign output:

```
<metadata>
  <dc:language>en-US</dc:language>
  <dc:language>ar-SA</dc:language>
</metadata>
```

And since iBooks consider the last element is the primary language, it decided to apply a `page-progression-direction` of right to left. 

You may point out that the Reading System should have not done that based on the language, but the `page-progression-direction` of the `spine` item. Now, it is my understanding they’re doing it:

1. when there is no `page-progression-direction` declared;
2. to support RTL scripts in ePub 2 (I can confirm this exists and I could find ePub 2 files in arabic/hebrew since it supports everything but `page-progression-direction` for RTL scripts e.g. `dir` attribute, `direction` CSS property, etc.).

Only it seems they don’t check the version of the EPUB file beforehand, which is quite dirty. So to be fair that should be reported as a bug.

It’s worth noting the RTL scripts + ePub2 is a use case, since you can find the following in the [Kobo guidelines](https://github.com/kobolabs/epub-spec#right-to-left-page-and-text-direction): 

> The "page-progression-direction" attribute was introduced as part of the ePub3 specification. However it can be used in both ePub2 and ePub3 files for Kobo and will pass through processing and display correctly on Kobo's reading platforms despite flags that ePub2 files will generate in ePubCheck.

I can’t speak on their behalf there but I can only assume the “multiple languages edge case” was part of this decision since you can encounter it very quickly when trying to support the RTL scripts + ePub2 use case. Maybe @bdugas can clarify that? 

To sum things up, I’d really find useful to have guidance for this use case (handling of multiple values). It’s been done for `creator` and Reading Systems could really do with guidance for others, whenever issues can arise for this specific case. It would be a first step to improve interoperability imho – it ends up impacting both authors and users, which really is the worst consequence it can be.

**Comment by bdugas** [comment]
Thanks Jiminy. Have a few thoughts/points here:


  1.  There are no shortage of ePub2 files we’ve received that use FXL, SMIL or RTL. There’s not much new content we receive today where this is the case (it’s a slow trickle) but there were enough publishers doing this for a few years that the total number of files is significant.
  2.  Our decision to support this was based on the fact that it wasn’t going to break other properly formatted content and that it was the only way to get this content in our store (when we launched FXL for example there was very little ePub3 FXL content even though it’s now 99%+ of the FXL content we receive).
  3.  For RTL we don’t connect it with language so there’s no situation where the OPF wouldn’t instruct the reading system to display content RTL and it would anyways because of the language. We haven’t seen it come up that often but when we do we simply fail the content and tell the publisher what they need to fix to have the content display correctly.
  4.  The only instances where we’ll build/add support for something that’s done incorrectly or not in the spec is where there’s a significant amount of content it will allow us to ingest and where we’re close to 100% certain it will never break support for other valid content.
  5.  The multiple language case actually had nothing to do with our handling of FXL. It’s actually never come up with regards to client support.
  6.  As a retailer/eBook platform we ignore most OPF metadata of the publication date, author category and only read items that affect content display (rendition spread, RTL, ePub type). This is because we only want to read the ONIX/external metadata. That said if there were a standard for what OPF metadata elements reading systems have to read or display in the reading experience such as language it would be of interest to us.

Cheers,
Ben Dugas,

Manager, Content Display Quality and Production

Toronto, Canada (GMT-5)

[cid:image009.png@01D38643.B571C7E0]<http://www.kobo.com/>

[cid:image010.png@01D38643.B571C7E0]<http://www.facebook.com/Kobo>

[cid:image011.png@01D38643.B571C7E0]<http://www.instagram.com/kobobooks>

[cid:image012.png@01D38643.B571C7E0]<http://twitter.com/kobo>

www.kobo.com<http://www.kobo.com/>

**Comment by JayPanoz** [comment]
I’m taking the liberty to “up” this issue since I raised it in the first place because it creates practical issues Reading Systems have to deal with right now but for some reason, it goes unnoticed and unaddressed, and it ends up hurting the whole ecosystem.

**Comment by dauwhe** [comment]
From CG meeting of 10 May 2018:

> Proposal: If dc:langauge is used as a fallback to determine default page-progression-direction, and their are multiple dc:languages, the first SHOULD be considered primary.

**Comment by JayPanoz** [comment]
[Further data](https://github.com/readium/readium-css/issues/26#issuecomment-353726315) as regards how a handful of RSs currently handle that.

And [an example of authoring guidelines available](https://github.com/readium/readium-css/issues/26#issuecomment-362210298).

With this proposal, “trusted language” would be the first one (instead of `none`). Note that this also and perhaps more importantly impacts User Settings e.g. available fonts, disabling settings that don’t apply in some scripts (hyphenation in CJK), etc.

Note also [the elephant in the room has created a `primary-writing-mode` meta](https://github.com/readium/readium-css/issues/26#issuecomment-383282474).

**Comment by dauwhe** [comment]
Spec says now:

> Additional language elements MAY be included for multilingual Publications, but each element's value MUST conform to [BCP47].

Can we add the following?

> The first `dc:language` element in document order is considered the primary language of the rendition.

Later, the spec says

> The page-progression-direction attribute sets the global direction in which the content flows. Allowed values are ltr (left-to-right), rtl (right-to-left) and default. When the default value is specified, the Author is expressing no preference and the Reading System can choose the rendering direction. The default value MUST be assumed when the attribute is not specified.

How about we insert a sentence after this:

> The reading system should choose a default `page-progression-direction` value based on the first `dc:language` element.

**Comment by GarthConboy** [comment]
I think that's okay, not introducing another requirement, but a recommendation.  The latter `should` should be `SHOULD`, right?  (or is it non-normative?)

Also need to make sure that the latter added sentence is active ONLY in cases where page-progression-direction is NOT explicitly specified.
