### ISSUE TITLE
epub:type="tip" not supported

### ISSUE THREAD

**Issue by johnlourdusamy** [w3c/epub-specs#995]
epubcheck 4.0.2 issues an error for the following:
`aside epub:type="tip"`
Results:
OPF-027, ERROR, [Undefined property: 'tip'.]
However this property is defined in https://idpf.github.io/epub-vocabs/structure/#h_asides

**Comment by mattgarrish** [comment]
This issue is related to https://github.com/IDPF/epubcheck/issues/531

I've added a comment there so the new semantics will hopefully get added whenever epubcheck gets updated next.

If you come across other validation problems, please open issues directly in the epubcheck repository. This one is for issues with the specifications, so the developers are not looking for them here.
